// Generated by CIRCT firtool-1.150.2
module ClosePathAdderF16Pipeline_2(
  input  [10:0] io_adder_op0,
                io_adder_op1,
  output [11:0] io_result
);

  wire
    struct packed {logic [10:0] adder_op0; logic [10:0] adder_op1; logic [11:0] result; }
    io;
  assign io =
    '{adder_op0: io_adder_op0,
      adder_op1: io_adder_op1,
      result: ({io.adder_op0, 1'h0} - {1'h0, io.adder_op1})};
  assign io_result = io.result;
endmodule

