// Generated by CIRCT firtool-1.150.2
module CryptoModule(
  input              clock,
  input  [1:0][63:0] io_src,
  input  [8:0]       io_func,
  input              io_regEnable,
  output [63:0]      io_out
);

  wire [63:0] _blockCipherModule_io_out;
  wire [63:0] _hashModule_io_out;
  wire
    struct packed {logic [1:0][63:0] src; logic [8:0] func; logic regEnable; logic [63:0] out; }
    io;
  reg  [8:0]  funcReg;
  wire [63:0] _io_out_T_1 = funcReg[4] ? _hashModule_io_out : _blockCipherModule_io_out;
  assign io = '{src: io_src, func: io_func, regEnable: io_regEnable, out: _io_out_T_1};
  always @(posedge clock) begin
    if (io.regEnable)
      funcReg <= io.func;
  end // always @(posedge)
  HashModule hashModule (
    .clock        (clock),
    .io_src       (io.src[1'h0]),
    .io_func      (io.func),
    .io_regEnable (io.regEnable),
    .io_out       (_hashModule_io_out)
  );
  BlockCipherModule blockCipherModule (
    .clock        (clock),
    .io_src       (io.src),
    .io_func      (io.func),
    .io_regEnable (io.regEnable),
    .io_out       (_blockCipherModule_io_out)
  );
  assign io_out = io.out;
endmodule

