// Generated by CIRCT firtool-1.150.2
module CSA3to2_152(
  input  [7:0] io_in_a,
               io_in_b,
               io_in_c,
  output [7:0] io_out_sum,
               io_out_car
);

  wire
    struct packed {logic [7:0] in_a; logic [7:0] in_b; logic [7:0] in_c; logic [7:0] out_sum; logic [7:0] out_car; }
    io;
  assign io =
    '{in_a: io_in_a,
      in_b: io_in_b,
      in_c: io_in_c,
      out_sum: (io.in_a ^ io.in_b ^ io.in_c),
      out_car:
        {io.in_a[6:0] & io.in_b[6:0] | io.in_a[6:0] & io.in_c[6:0] | io.in_b[6:0]
           & io.in_c[6:0],
         1'h0}};
  assign io_out_sum = io.out_sum;
  assign io_out_car = io.out_car;
endmodule

