// Generated by CIRCT firtool-1.150.2
module CVT32ModuleS2(
  input  struct packed {logic [31:0] result; logic [4:0] fflags; } io_s2In,
  output struct packed {logic [31:0] result; logic [4:0] fflags; } io_s2Out
);

  wire
    struct packed {struct packed {logic [31:0] result; logic [4:0] fflags; } s2In; struct packed {logic [31:0] result; logic [4:0] fflags; } s2Out; }
    io;
  assign io = '{s2In: io_s2In, s2Out: io.s2In};
  assign io_s2Out = io.s2Out;
endmodule

