// Generated by CIRCT firtool-1.150.2
module DelayN_10(
  input  clock,
         io_in,
  output io_out
);

  wire struct packed {logic in; logic out; } io;
  reg  REG;
  reg  REG_1;
  reg  REG_2;
  assign io = '{in: io_in, out: REG_2};
  always @(posedge clock)
    REG <= io.in;
  always @(posedge clock)
    REG_1 <= REG;
  always @(posedge clock)
    REG_2 <= REG_1;
  assign io_out = io.out;
endmodule

