// Generated by CIRCT firtool-1.150.2
module DelayN_75(
  input                  clock,
  input  [0:0][2:0][1:0] io_in,
  output [0:0][2:0][1:0] io_out
);

  wire struct packed {logic [0:0][2:0][1:0] in; logic [0:0][2:0][1:0] out; } io;
  reg  [0:0][2:0][1:0] REG;
  reg  [0:0][2:0][1:0] REG_1;
  assign io = '{in: io_in, out: REG_1};
  always @(posedge clock)
    REG <= io.in;
  always @(posedge clock)
    REG_1 <= REG;
  assign io_out = io.out;
endmodule

