// Generated by CIRCT firtool-1.150.2
module DummyDPICWrapper_CSRState(
  input                                                                                                                                                                                                                                                                                                                                                                                                                                                                   clock,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          reset,
  input struct packed {logic valid; struct packed {logic [63:0] privilegeMode; logic [63:0] mstatus; logic [63:0] sstatus; logic [63:0] mepc; logic [63:0] sepc; logic [63:0] mtval; logic [63:0] stval; logic [63:0] mtvec; logic [63:0] stvec; logic [63:0] mcause; logic [63:0] scause; logic [63:0] satp; logic [63:0] mip; logic [63:0] mie; logic [63:0] mscratch; logic [63:0] sscratch; logic [63:0] mideleg; logic [63:0] medeleg; logic [7:0] coreid; } bits; } io
);

`ifdef DUMMY
  DiffExtCSRState dpic (
    .clock  (clock),
    .enable (io.valid & ~reset),
    .io     (io.bits)
  );
`endif
endmodule

