// Generated by CIRCT firtool-1.150.2
module FPCVT(
  input         clock,
                reset,
                io_fire,
  input  [63:0] io_src,
  input  [7:0]  io_opType,
  input  [1:0]  io_sew,
  input  [2:0]  io_rm,
  output [63:0] io_result,
  output [4:0]  io_fflags
);

  wire [63:0] _fcvt_io_result;
  wire [4:0]  _fcvt_io_fflags;
  wire
    struct packed {logic fire; logic [63:0] src; logic [7:0] opType; logic [1:0] sew; logic [2:0] rm; logic isFpToVecInst; logic [1:0] isFround; logic isFcvtmod; logic [63:0] result; logic [4:0] fflags; }
    io;
  wire [1:0]  widen = io.opType[4:3];
  wire [3:0]  _output1H_T = {widen, io.sew};
  wire [3:0]  input1H_plaInput;
  assign input1H_plaInput = _output1H_T;
  wire [3:0]  output1H_plaInput;
  assign output1H_plaInput = _output1H_T;
  wire [3:0]  input1H_invInputs = ~input1H_plaInput;
  wire        input1H_andMatrixOutputs_andMatrixInput_0 = input1H_plaInput[0];
  wire        input1H_andMatrixOutputs_andMatrixInput_0_2 = input1H_plaInput[0];
  wire        input1H_andMatrixOutputs_andMatrixInput_0_4 = input1H_plaInput[0];
  wire        input1H_andMatrixOutputs_andMatrixInput_0_6 = input1H_plaInput[0];
  wire        input1H_andMatrixOutputs_andMatrixInput_0_8 = input1H_plaInput[0];
  wire        input1H_andMatrixOutputs_andMatrixInput_1 = input1H_invInputs[1];
  wire        input1H_andMatrixOutputs_andMatrixInput_1_3 = input1H_invInputs[1];
  wire        input1H_andMatrixOutputs_andMatrixInput_1_4 = input1H_invInputs[1];
  wire        input1H_andMatrixOutputs_andMatrixInput_1_5 = input1H_invInputs[1];
  wire        input1H_andMatrixOutputs_andMatrixInput_1_6 = input1H_invInputs[1];
  wire        input1H_andMatrixOutputs_andMatrixInput_2 = input1H_invInputs[3];
  wire        input1H_andMatrixOutputs_andMatrixInput_2_1 = input1H_invInputs[3];
  wire        input1H_andMatrixOutputs_andMatrixInput_3 = input1H_invInputs[3];
  wire        input1H_andMatrixOutputs_andMatrixInput_3_1 = input1H_invInputs[3];
  wire        input1H_andMatrixOutputs_5_2 =
    &{input1H_andMatrixOutputs_andMatrixInput_0,
      input1H_andMatrixOutputs_andMatrixInput_1,
      input1H_andMatrixOutputs_andMatrixInput_2};
  wire        input1H_andMatrixOutputs_andMatrixInput_0_1 = input1H_invInputs[0];
  wire        input1H_andMatrixOutputs_andMatrixInput_0_3 = input1H_invInputs[0];
  wire        input1H_andMatrixOutputs_andMatrixInput_0_5 = input1H_invInputs[0];
  wire        input1H_andMatrixOutputs_andMatrixInput_0_7 = input1H_invInputs[0];
  wire        input1H_andMatrixOutputs_andMatrixInput_1_1 = input1H_plaInput[1];
  wire        input1H_andMatrixOutputs_andMatrixInput_1_2 = input1H_plaInput[1];
  wire        input1H_andMatrixOutputs_andMatrixInput_1_7 = input1H_plaInput[1];
  wire        input1H_andMatrixOutputs_andMatrixInput_1_8 = input1H_plaInput[1];
  wire        input1H_andMatrixOutputs_7_2 =
    &{input1H_andMatrixOutputs_andMatrixInput_0_1,
      input1H_andMatrixOutputs_andMatrixInput_1_1,
      input1H_andMatrixOutputs_andMatrixInput_2_1};
  wire        input1H_andMatrixOutputs_andMatrixInput_2_2 = input1H_invInputs[2];
  wire        input1H_andMatrixOutputs_andMatrixInput_2_5 = input1H_invInputs[2];
  wire        input1H_andMatrixOutputs_andMatrixInput_2_6 = input1H_invInputs[2];
  wire        input1H_andMatrixOutputs_andMatrixInput_2_7 = input1H_invInputs[2];
  wire        input1H_andMatrixOutputs_2_2 =
    &{input1H_andMatrixOutputs_andMatrixInput_0_2,
      input1H_andMatrixOutputs_andMatrixInput_1_2,
      input1H_andMatrixOutputs_andMatrixInput_2_2,
      input1H_andMatrixOutputs_andMatrixInput_3};
  wire        input1H_andMatrixOutputs_andMatrixInput_2_3 = input1H_plaInput[2];
  wire        input1H_andMatrixOutputs_andMatrixInput_2_4 = input1H_plaInput[2];
  wire        input1H_andMatrixOutputs_andMatrixInput_2_8 = input1H_plaInput[2];
  wire        input1H_andMatrixOutputs_6_2 =
    &{input1H_andMatrixOutputs_andMatrixInput_0_3,
      input1H_andMatrixOutputs_andMatrixInput_1_3,
      input1H_andMatrixOutputs_andMatrixInput_2_3,
      input1H_andMatrixOutputs_andMatrixInput_3_1};
  wire        input1H_andMatrixOutputs_4_2 =
    &{input1H_andMatrixOutputs_andMatrixInput_0_4,
      input1H_andMatrixOutputs_andMatrixInput_1_4,
      input1H_andMatrixOutputs_andMatrixInput_2_4};
  wire        input1H_andMatrixOutputs_andMatrixInput_3_2 = input1H_plaInput[3];
  wire        input1H_andMatrixOutputs_andMatrixInput_3_3 = input1H_plaInput[3];
  wire        input1H_andMatrixOutputs_andMatrixInput_3_4 = input1H_plaInput[3];
  wire        input1H_andMatrixOutputs_andMatrixInput_3_5 = input1H_plaInput[3];
  wire        input1H_andMatrixOutputs_3_2 =
    &{input1H_andMatrixOutputs_andMatrixInput_0_5,
      input1H_andMatrixOutputs_andMatrixInput_1_5,
      input1H_andMatrixOutputs_andMatrixInput_2_5,
      input1H_andMatrixOutputs_andMatrixInput_3_2};
  wire        input1H_andMatrixOutputs_1_2 =
    &{input1H_andMatrixOutputs_andMatrixInput_0_6,
      input1H_andMatrixOutputs_andMatrixInput_1_6,
      input1H_andMatrixOutputs_andMatrixInput_2_6,
      input1H_andMatrixOutputs_andMatrixInput_3_3};
  wire        input1H_andMatrixOutputs_0_2 =
    &{input1H_andMatrixOutputs_andMatrixInput_0_7,
      input1H_andMatrixOutputs_andMatrixInput_1_7,
      input1H_andMatrixOutputs_andMatrixInput_2_7,
      input1H_andMatrixOutputs_andMatrixInput_3_4};
  wire        input1H_andMatrixOutputs_8_2 =
    &{input1H_andMatrixOutputs_andMatrixInput_0_8,
      input1H_andMatrixOutputs_andMatrixInput_1_8,
      input1H_andMatrixOutputs_andMatrixInput_2_8,
      input1H_andMatrixOutputs_andMatrixInput_3_5};
  wire [3:0]  input1H_orMatrixOutputs =
    {|{input1H_andMatrixOutputs_2_2,
       input1H_andMatrixOutputs_0_2,
       input1H_andMatrixOutputs_8_2},
     |{input1H_andMatrixOutputs_7_2, input1H_andMatrixOutputs_1_2},
     |{input1H_andMatrixOutputs_5_2,
       input1H_andMatrixOutputs_4_2,
       input1H_andMatrixOutputs_3_2},
     input1H_andMatrixOutputs_6_2};
  wire [3:0]  input1H_invMatrixOutputs = input1H_orMatrixOutputs;
  wire [3:0]  input1H_plaOutput = input1H_invMatrixOutputs;
  wire [3:0]  input1H = input1H_plaOutput;
  wire [3:0]  output1H_invInputs = ~output1H_plaInput;
  wire        output1H_andMatrixOutputs_andMatrixInput_0 = output1H_plaInput[0];
  wire        output1H_andMatrixOutputs_andMatrixInput_0_2 = output1H_plaInput[0];
  wire        output1H_andMatrixOutputs_andMatrixInput_0_4 = output1H_plaInput[0];
  wire        output1H_andMatrixOutputs_andMatrixInput_0_7 = output1H_plaInput[0];
  wire        output1H_andMatrixOutputs_andMatrixInput_0_8 = output1H_plaInput[0];
  wire        output1H_andMatrixOutputs_andMatrixInput_1 = output1H_invInputs[1];
  wire        output1H_andMatrixOutputs_andMatrixInput_1_3 = output1H_invInputs[1];
  wire        output1H_andMatrixOutputs_andMatrixInput_1_4 = output1H_invInputs[1];
  wire        output1H_andMatrixOutputs_andMatrixInput_1_6 = output1H_invInputs[1];
  wire        output1H_andMatrixOutputs_andMatrixInput_1_7 = output1H_invInputs[1];
  wire        output1H_andMatrixOutputs_andMatrixInput_2 = output1H_invInputs[2];
  wire        output1H_andMatrixOutputs_andMatrixInput_2_1 = output1H_invInputs[2];
  wire        output1H_andMatrixOutputs_andMatrixInput_2_2 = output1H_invInputs[2];
  wire        output1H_andMatrixOutputs_andMatrixInput_2_6 = output1H_invInputs[2];
  wire        output1H_andMatrixOutputs_2_2 =
    &{output1H_andMatrixOutputs_andMatrixInput_0,
      output1H_andMatrixOutputs_andMatrixInput_1,
      output1H_andMatrixOutputs_andMatrixInput_2};
  wire        output1H_andMatrixOutputs_andMatrixInput_0_1 = output1H_invInputs[0];
  wire        output1H_andMatrixOutputs_andMatrixInput_0_3 = output1H_invInputs[0];
  wire        output1H_andMatrixOutputs_andMatrixInput_0_5 = output1H_invInputs[0];
  wire        output1H_andMatrixOutputs_andMatrixInput_0_6 = output1H_invInputs[0];
  wire        output1H_andMatrixOutputs_andMatrixInput_1_1 = output1H_plaInput[1];
  wire        output1H_andMatrixOutputs_andMatrixInput_1_2 = output1H_plaInput[1];
  wire        output1H_andMatrixOutputs_andMatrixInput_1_5 = output1H_plaInput[1];
  wire        output1H_andMatrixOutputs_andMatrixInput_1_8 = output1H_plaInput[1];
  wire        output1H_andMatrixOutputs_0_2 =
    &{output1H_andMatrixOutputs_andMatrixInput_0_1,
      output1H_andMatrixOutputs_andMatrixInput_1_1,
      output1H_andMatrixOutputs_andMatrixInput_2_1};
  wire        output1H_andMatrixOutputs_andMatrixInput_3 = output1H_invInputs[3];
  wire        output1H_andMatrixOutputs_andMatrixInput_3_1 = output1H_invInputs[3];
  wire        output1H_andMatrixOutputs_andMatrixInput_3_2 = output1H_invInputs[3];
  wire        output1H_andMatrixOutputs_andMatrixInput_3_3 = output1H_invInputs[3];
  wire        output1H_andMatrixOutputs_1_2 =
    &{output1H_andMatrixOutputs_andMatrixInput_0_2,
      output1H_andMatrixOutputs_andMatrixInput_1_2,
      output1H_andMatrixOutputs_andMatrixInput_2_2,
      output1H_andMatrixOutputs_andMatrixInput_3};
  wire        output1H_andMatrixOutputs_andMatrixInput_2_3 = output1H_plaInput[2];
  wire        output1H_andMatrixOutputs_andMatrixInput_2_4 = output1H_plaInput[2];
  wire        output1H_andMatrixOutputs_andMatrixInput_2_5 = output1H_plaInput[2];
  wire        output1H_andMatrixOutputs_andMatrixInput_2_7 = output1H_plaInput[2];
  wire        output1H_andMatrixOutputs_andMatrixInput_2_8 = output1H_plaInput[2];
  wire        output1H_andMatrixOutputs_5_2 =
    &{output1H_andMatrixOutputs_andMatrixInput_0_3,
      output1H_andMatrixOutputs_andMatrixInput_1_3,
      output1H_andMatrixOutputs_andMatrixInput_2_3,
      output1H_andMatrixOutputs_andMatrixInput_3_1};
  wire        output1H_andMatrixOutputs_4_2 =
    &{output1H_andMatrixOutputs_andMatrixInput_0_4,
      output1H_andMatrixOutputs_andMatrixInput_1_4,
      output1H_andMatrixOutputs_andMatrixInput_2_4,
      output1H_andMatrixOutputs_andMatrixInput_3_2};
  wire        output1H_andMatrixOutputs_8_2 =
    &{output1H_andMatrixOutputs_andMatrixInput_0_5,
      output1H_andMatrixOutputs_andMatrixInput_1_5,
      output1H_andMatrixOutputs_andMatrixInput_2_5,
      output1H_andMatrixOutputs_andMatrixInput_3_3};
  wire        output1H_andMatrixOutputs_andMatrixInput_3_4 = output1H_plaInput[3];
  wire        output1H_andMatrixOutputs_andMatrixInput_3_5 = output1H_plaInput[3];
  wire        output1H_andMatrixOutputs_andMatrixInput_3_6 = output1H_plaInput[3];
  wire        output1H_andMatrixOutputs_3_2 =
    &{output1H_andMatrixOutputs_andMatrixInput_0_6,
      output1H_andMatrixOutputs_andMatrixInput_1_6,
      output1H_andMatrixOutputs_andMatrixInput_2_6,
      output1H_andMatrixOutputs_andMatrixInput_3_4};
  wire        output1H_andMatrixOutputs_6_2 =
    &{output1H_andMatrixOutputs_andMatrixInput_0_7,
      output1H_andMatrixOutputs_andMatrixInput_1_7,
      output1H_andMatrixOutputs_andMatrixInput_2_7,
      output1H_andMatrixOutputs_andMatrixInput_3_5};
  wire        output1H_andMatrixOutputs_7_2 =
    &{output1H_andMatrixOutputs_andMatrixInput_0_8,
      output1H_andMatrixOutputs_andMatrixInput_1_8,
      output1H_andMatrixOutputs_andMatrixInput_2_8,
      output1H_andMatrixOutputs_andMatrixInput_3_6};
  wire [3:0]  output1H_orMatrixOutputs =
    {|{output1H_andMatrixOutputs_1_2,
       output1H_andMatrixOutputs_8_2,
       output1H_andMatrixOutputs_6_2},
     |{output1H_andMatrixOutputs_0_2, output1H_andMatrixOutputs_4_2},
     |{output1H_andMatrixOutputs_2_2,
       output1H_andMatrixOutputs_5_2,
       output1H_andMatrixOutputs_7_2},
     output1H_andMatrixOutputs_3_2};
  wire [3:0]  output1H_invMatrixOutputs = output1H_orMatrixOutputs;
  wire [3:0]  output1H_plaOutput = output1H_invMatrixOutputs;
  wire [3:0]  output1H = output1H_plaOutput;
  assign io =
    '{fire: io_fire,
      src: io_src,
      opType: io_opType,
      sew: io_sew,
      rm: io_rm,
      isFpToVecInst: (1'h1),
      isFround: (2'h0),
      isFcvtmod: (1'h0),
      result: _fcvt_io_result,
      fflags: _fcvt_io_fflags};
  CVT64 fcvt (
    .clock            (clock),
    .reset            (reset),
    .io_fire          (io.fire),
    .io_src           (io.src),
    .io_opType        (io.opType),
    .io_sew           (io.sew),
    .io_rm            (io.rm),
    .io_input1H       (input1H),
    .io_output1H      (output1H),
    .io_isFpToVecInst (1'h1),
    .io_isFround      (2'h0),
    .io_isFcvtmod     (1'h0),
    .io_result        (_fcvt_io_result),
    .io_fflags        (_fcvt_io_fflags)
  );
  assign io_result = io.result;
  assign io_fflags = io.fflags;
endmodule

