// Generated by CIRCT firtool-1.150.2
module FuBusyTableRead(
  input                                                 io_in_fuBusyTable,
  input  [17:0][35:0]                                   io_in_fuTypeRegVec,
  output struct packed {logic [17:0] fuBusyTableMask; } io_out
);

  wire [17:0] readMaskVec_0 = 18'h0;
  wire struct packed {logic [17:0] fuBusyTableMask; } _GEN = '{fuBusyTableMask: 18'h0};
  wire
    struct packed {struct packed {logic fuBusyTable; logic [17:0][35:0] fuTypeRegVec; } in; struct packed {logic [17:0] fuBusyTableMask; } out; }
    io;
  wire struct packed {logic fuBusyTable; logic [17:0][35:0] fuTypeRegVec; } _GEN_0 =
    '{fuBusyTable: io_in_fuBusyTable, fuTypeRegVec: io_in_fuTypeRegVec};
  assign io = '{in: _GEN_0, out: _GEN};
  wire [0:0]  fuBusyVec = {1{io.in.fuBusyTable}};
  assign io_out = _GEN;
endmodule

