// Generated by CIRCT firtool-1.150.2
module LeftShiftWordModule(
  input  [4:0]  io_shamt,
  input  [31:0] io_sllSrc,
  output [31:0] io_sllw
);

  wire struct packed {logic [4:0] shamt; logic [31:0] sllSrc; logic [31:0] sllw; } io;
  wire [31:0] io_sllw_shifted = io.shamt[4] ? {io.sllSrc[15:0], 16'h0} : io.sllSrc;
  wire [31:0] io_sllw_shifted_1 =
    io.shamt[3] ? {io_sllw_shifted[23:0], 8'h0} : io_sllw_shifted;
  wire [31:0] io_sllw_shifted_2 =
    io.shamt[2] ? {io_sllw_shifted_1[27:0], 4'h0} : io_sllw_shifted_1;
  wire [31:0] io_sllw_shifted_3 =
    io.shamt[1] ? {io_sllw_shifted_2[29:0], 2'h0} : io_sllw_shifted_2;
  wire [31:0] io_sllw_shifted_4 =
    io.shamt[0] ? {io_sllw_shifted_3[30:0], 1'h0} : io_sllw_shifted_3;
  assign io = '{shamt: io_shamt, sllSrc: io_sllSrc, sllw: io_sllw_shifted_4};
  assign io_sllw = io.sllw;
endmodule

