// Generated by CIRCT firtool-1.150.2
module MarchidModule(
  input                                                  clock,
                                                         reset,
  input  struct packed {logic wen; logic [63:0] wdata; } w,
  output [63:0]                                          rdata,
  output struct packed {logic [63:0] ALL; }              regOut
);

  struct packed {logic [63:0] ALL; } reg_0;
  wire struct packed {logic [63:0] ALL; } reg_init = '{ALL: 64'h19};
  wire struct packed {logic [63:0] ALL; } wdata = '{ALL: w.wdata};
  always @(posedge clock or posedge reset) begin
    if (reset)
      reg_0 <= reg_init;
    else
      reg_0 <= reg_0;
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset)
        reg_0 = reg_init;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign rdata = reg_0.ALL;
  assign regOut = reg_0;
endmodule

