// Generated by CIRCT firtool-1.150.2
module MedelegModule(
  input                                                                                                                                                                                                                                                                                                                                                    clock,
                                                                                                                                                                                                                                                                                                                                                           reset,
  input  struct packed {logic wen; logic [63:0] wdata; }                                                                                                                                                                                                                                                                                                   w,
  output [63:0]                                                                                                                                                                                                                                                                                                                                            rdata,
  output struct packed {logic EX_IAM; logic EX_IAF; logic EX_II; logic EX_BP; logic EX_LAM; logic EX_LAF; logic EX_SAM; logic EX_SAF; logic EX_UCALL; logic EX_HSCALL; logic EX_VSCALL; logic EX_MCALL; logic EX_IPF; logic EX_LPF; logic EX_SPF; logic EX_DBLTRP; logic EX_SWC; logic EX_HWE; logic EX_IGPF; logic EX_LGPF; logic EX_VI; logic EX_SGPF; } regOut
);

  struct packed {logic EX_IAM; logic EX_IAF; logic EX_II; logic EX_BP; logic EX_LAM; logic EX_LAF; logic EX_SAM; logic EX_SAF; logic EX_UCALL; logic EX_HSCALL; logic EX_VSCALL; logic EX_MCALL; logic EX_IPF; logic EX_LPF; logic EX_SPF; logic EX_DBLTRP; logic EX_SWC; logic EX_HWE; logic EX_IGPF; logic EX_LGPF; logic EX_VI; logic EX_SGPF; }
    reg_0;
  wire
    struct packed {logic EX_IAM; logic EX_IAF; logic EX_II; logic EX_BP; logic EX_LAM; logic EX_LAF; logic EX_SAM; logic EX_SAF; logic EX_UCALL; logic EX_HSCALL; logic EX_VSCALL; logic EX_MCALL; logic EX_IPF; logic EX_LPF; logic EX_SPF; logic EX_DBLTRP; logic EX_SWC; logic EX_HWE; logic EX_IGPF; logic EX_LGPF; logic EX_VI; logic EX_SGPF; }
    reg_init =
    '{EX_IAM: 1'h0,
      EX_IAF: 1'h0,
      EX_II: 1'h0,
      EX_BP: 1'h0,
      EX_LAM: 1'h0,
      EX_LAF: 1'h0,
      EX_SAM: 1'h0,
      EX_SAF: 1'h0,
      EX_UCALL: 1'h0,
      EX_HSCALL: 1'h0,
      EX_VSCALL: 1'h0,
      EX_MCALL: 1'h0,
      EX_IPF: 1'h0,
      EX_LPF: 1'h0,
      EX_SPF: 1'h0,
      EX_DBLTRP: 1'h0,
      EX_SWC: 1'h0,
      EX_HWE: 1'h0,
      EX_IGPF: 1'h0,
      EX_LGPF: 1'h0,
      EX_VI: 1'h0,
      EX_SGPF: 1'h0};
  wire
    struct packed {logic EX_IAM; logic EX_IAF; logic EX_II; logic EX_BP; logic EX_LAM; logic EX_LAF; logic EX_SAM; logic EX_SAF; logic EX_UCALL; logic EX_HSCALL; logic EX_VSCALL; logic EX_MCALL; logic EX_IPF; logic EX_LPF; logic EX_SPF; logic EX_DBLTRP; logic EX_SWC; logic EX_HWE; logic EX_IGPF; logic EX_LGPF; logic EX_VI; logic EX_SGPF; }
    wdata =
    '{EX_IAM: (w.wdata[0]),
      EX_IAF: (w.wdata[1]),
      EX_II: (w.wdata[2]),
      EX_BP: (w.wdata[3]),
      EX_LAM: (w.wdata[4]),
      EX_LAF: (w.wdata[5]),
      EX_SAM: (w.wdata[6]),
      EX_SAF: (w.wdata[7]),
      EX_UCALL: (w.wdata[8]),
      EX_HSCALL: (w.wdata[9]),
      EX_VSCALL: (w.wdata[10]),
      EX_MCALL: (w.wdata[11]),
      EX_IPF: (w.wdata[12]),
      EX_LPF: (w.wdata[13]),
      EX_SPF: (w.wdata[15]),
      EX_DBLTRP: (w.wdata[16]),
      EX_SWC: (w.wdata[18]),
      EX_HWE: (w.wdata[19]),
      EX_IGPF: (w.wdata[20]),
      EX_LGPF: (w.wdata[21]),
      EX_VI: (w.wdata[22]),
      EX_SGPF: (w.wdata[23])};
  always @(posedge clock or posedge reset) begin
    if (reset)
      reg_0 <= reg_init;
    else begin
      automatic logic _GEN;
      automatic logic _GEN_0;
      automatic logic _GEN_1;
      automatic logic _GEN_2;
      automatic logic _GEN_3;
      automatic logic _GEN_4;
      automatic logic _GEN_5;
      automatic logic _GEN_6;
      automatic logic _GEN_7;
      automatic logic _GEN_8;
      automatic logic _GEN_9;
      automatic logic _GEN_10;
      automatic logic _GEN_11;
      automatic logic _GEN_12;
      automatic logic _GEN_13;
      automatic logic _GEN_14;
      automatic logic _GEN_15;
      automatic logic _GEN_16;
      automatic logic _GEN_17;
      automatic logic _GEN_18;
      _GEN = w.wen ? wdata.EX_IAM : reg_0.EX_IAM;
      _GEN_0 = w.wen ? wdata.EX_IAF : reg_0.EX_IAF;
      _GEN_1 = w.wen ? wdata.EX_II : reg_0.EX_II;
      _GEN_2 = w.wen ? wdata.EX_BP : reg_0.EX_BP;
      _GEN_3 = w.wen ? wdata.EX_LAM : reg_0.EX_LAM;
      _GEN_4 = w.wen ? wdata.EX_LAF : reg_0.EX_LAF;
      _GEN_5 = w.wen ? wdata.EX_SAM : reg_0.EX_SAM;
      _GEN_6 = w.wen ? wdata.EX_SAF : reg_0.EX_SAF;
      _GEN_7 = w.wen ? wdata.EX_UCALL : reg_0.EX_UCALL;
      _GEN_8 = w.wen ? wdata.EX_HSCALL : reg_0.EX_HSCALL;
      _GEN_9 = w.wen ? wdata.EX_VSCALL : reg_0.EX_VSCALL;
      _GEN_10 = w.wen ? wdata.EX_IPF : reg_0.EX_IPF;
      _GEN_11 = w.wen ? wdata.EX_LPF : reg_0.EX_LPF;
      _GEN_12 = w.wen ? wdata.EX_SPF : reg_0.EX_SPF;
      _GEN_13 = w.wen ? wdata.EX_SWC : reg_0.EX_SWC;
      _GEN_14 = w.wen ? wdata.EX_HWE : reg_0.EX_HWE;
      _GEN_15 = w.wen ? wdata.EX_IGPF : reg_0.EX_IGPF;
      _GEN_16 = w.wen ? wdata.EX_LGPF : reg_0.EX_LGPF;
      _GEN_17 = w.wen ? wdata.EX_VI : reg_0.EX_VI;
      _GEN_18 = w.wen ? wdata.EX_SGPF : reg_0.EX_SGPF;
      reg_0 <=
        '{EX_IAM: _GEN,
          EX_IAF: _GEN_0,
          EX_II: _GEN_1,
          EX_BP: _GEN_2,
          EX_LAM: _GEN_3,
          EX_LAF: _GEN_4,
          EX_SAM: _GEN_5,
          EX_SAF: _GEN_6,
          EX_UCALL: _GEN_7,
          EX_HSCALL: _GEN_8,
          EX_VSCALL: _GEN_9,
          EX_MCALL: reg_0.EX_MCALL,
          EX_IPF: _GEN_10,
          EX_LPF: _GEN_11,
          EX_SPF: _GEN_12,
          EX_DBLTRP: reg_0.EX_DBLTRP,
          EX_SWC: _GEN_13,
          EX_HWE: _GEN_14,
          EX_IGPF: _GEN_15,
          EX_LGPF: _GEN_16,
          EX_VI: _GEN_17,
          EX_SGPF: _GEN_18};
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset)
        reg_0 = reg_init;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign rdata =
    {40'h0,
     reg_0.EX_SGPF,
     reg_0.EX_VI,
     reg_0.EX_LGPF,
     reg_0.EX_IGPF,
     reg_0.EX_HWE,
     reg_0.EX_SWC,
     1'h0,
     reg_0.EX_DBLTRP,
     reg_0.EX_SPF,
     1'h0,
     reg_0.EX_LPF,
     reg_0.EX_IPF,
     reg_0.EX_MCALL,
     reg_0.EX_VSCALL,
     reg_0.EX_HSCALL,
     reg_0.EX_UCALL,
     reg_0.EX_SAF,
     reg_0.EX_SAM,
     reg_0.EX_LAF,
     reg_0.EX_LAM,
     reg_0.EX_BP,
     reg_0.EX_II,
     reg_0.EX_IAF,
     reg_0.EX_IAM};
  assign regOut = reg_0;
endmodule

