// Generated by CIRCT firtool-1.150.2
module MncauseModule(
  input                                                                                                                                                                                                                                                                                                                                                                                                                              clock,
                                                                                                                                                                                                                                                                                                                                                                                                                                     reset,
  input  struct packed {logic wen; logic [63:0] wdata; }                                                                                                                                                                                                                                                                                                                                                                             w,
  output [63:0]                                                                                                                                                                                                                                                                                                                                                                                                                      rdata,
  output struct packed {logic Interrupt; logic [62:0] ExceptionCode; }                                                                                                                                                                                                                                                                                                                                                               regOut,
  input  struct packed {struct packed {logic valid; struct packed {logic [1:0] PRVM; logic V; } bits; } privState; struct packed {logic valid; struct packed {logic NMIE; logic MNPV; logic MNPELP; logic [1:0] MNPP; } bits; } mnstatus; struct packed {logic valid; struct packed {logic [62:0] epc; } bits; } mnepc; struct packed {logic valid; struct packed {logic Interrupt; logic [62:0] ExceptionCode; } bits; } mncause; } trapToMN
);

  struct packed {logic Interrupt; logic [62:0] ExceptionCode; } reg_0;
  wire struct packed {logic Interrupt; logic [62:0] ExceptionCode; } reg_init =
    '{Interrupt: 1'h0, ExceptionCode: 63'h0};
  wire struct packed {logic Interrupt; logic [62:0] ExceptionCode; } wdata;
  assign wdata = '{Interrupt: (w.wdata[63]), ExceptionCode: (w.wdata[62:0])};
  wire [62:0] _reg_ExceptionCode_T_1 =
    trapToMN.mncause.valid ? trapToMN.mncause.bits.ExceptionCode : 63'h0;
  wire [62:0] _reg_ExceptionCode_T_3 = w.wen ? wdata.ExceptionCode : 63'h0;
  wire [62:0] reg_ExceptionCode_result = _reg_ExceptionCode_T_1 | _reg_ExceptionCode_T_3;
  wire        reg_Interrupt_result =
    trapToMN.mncause.valid & trapToMN.mncause.bits.Interrupt | w.wen & wdata.Interrupt;
  always @(posedge clock or posedge reset) begin
    if (reset)
      reg_0 <= reg_init;
    else begin
      automatic logic        _GEN = w.wen | trapToMN.mncause.valid;
      automatic logic        _GEN_0;
      automatic logic [62:0] _GEN_1;
      _GEN_0 = _GEN ? reg_Interrupt_result : reg_0.Interrupt;
      _GEN_1 = _GEN ? reg_ExceptionCode_result : reg_0.ExceptionCode;
      reg_0 <= '{Interrupt: _GEN_0, ExceptionCode: _GEN_1};
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset)
        reg_0 = reg_init;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign rdata = {reg_0.Interrupt, reg_0.ExceptionCode};
  assign regOut = reg_0;
endmodule

