// Generated by CIRCT firtool-1.150.2
module NewPipelineConnectPipe(
  input                                                                                                                                                                                                                                                                                                                                                  clock,
                                                                                                                                                                                                                                                                                                                                                         reset,
                                                                                                                                                                                                                                                                                                                                                         io_in_valid,
  input  struct packed {logic [35:0] fuType; logic [8:0] fuOpType; logic is0Lat; logic rfWen; logic flushPipe; logic isRVC; struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] value; }[1:0] dataSources; struct packed {logic [3:0] value; }[1:0] exuSources; logic [2:0][1:0] loadDependency; } io_in_bits_ctrl,
  input  struct packed {logic [1:0][63:0] src; logic [63:0] imm; logic [49:0] pc; }                                                                                                                                                                                                                                                                      io_in_bits_data,
  input                                                                                                                                                                                                                                                                                                                                                  io_in_bits_toRobValid,
  input  struct packed {logic flag; logic [8:0] value; }                                                                                                                                                                                                                                                                                                 io_in_bits_robIdx,
  input  struct packed {logic [7:0] pdest; }                                                                                                                                                                                                                                                                                                             io_in_bits_toRF,
  input  [4:0]                                                                                                                                                                                                                                                                                                                                           io_in_bits_iqIdx,
  input                                                                                                                                                                                                                                                                                                                                                  io_in_bits_isFirstIssue,
  output                                                                                                                                                                                                                                                                                                                                                 io_out_valid,
  output struct packed {logic [35:0] fuType; logic [8:0] fuOpType; logic is0Lat; logic rfWen; logic flushPipe; logic isRVC; struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] value; }[1:0] dataSources; struct packed {logic [3:0] value; }[1:0] exuSources; logic [2:0][1:0] loadDependency; } io_out_bits_ctrl,
  output struct packed {logic [1:0][63:0] src; logic [63:0] imm; logic [49:0] pc; }                                                                                                                                                                                                                                                                      io_out_bits_data,
  output                                                                                                                                                                                                                                                                                                                                                 io_out_bits_toRobValid,
  output struct packed {logic flag; logic [8:0] value; }                                                                                                                                                                                                                                                                                                 io_out_bits_robIdx,
  output struct packed {logic [7:0] pdest; }                                                                                                                                                                                                                                                                                                             io_out_bits_toRF,
  output [4:0]                                                                                                                                                                                                                                                                                                                                           io_out_bits_iqIdx,
  output                                                                                                                                                                                                                                                                                                                                                 io_out_bits_isFirstIssue,
  input                                                                                                                                                                                                                                                                                                                                                  io_rightOutFire,
                                                                                                                                                                                                                                                                                                                                                         io_isFlush
);

  wire
    struct packed {logic [35:0] fuType; logic [8:0] fuOpType; logic is0Lat; logic rfWen; logic flushPipe; logic isRVC; struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] value; }[1:0] dataSources; struct packed {logic [3:0] value; }[1:0] exuSources; logic [2:0][1:0] loadDependency; }
    io_in_bits_ctrl_0 = io_in_bits_ctrl;
  wire struct packed {logic [1:0][63:0] src; logic [63:0] imm; logic [49:0] pc; }
    io_in_bits_data_0 = io_in_bits_data;
  wire struct packed {logic flag; logic [8:0] value; } io_in_bits_robIdx_0 =
    io_in_bits_robIdx;
  wire struct packed {logic [7:0] pdest; } io_in_bits_toRF_0 = io_in_bits_toRF;
  wire       io_in_valid_0 = io_in_valid;
  wire       io_in_bits_toRobValid_0 = io_in_bits_toRobValid;
  wire [4:0] io_in_bits_iqIdx_0 = io_in_bits_iqIdx;
  wire       io_in_bits_isFirstIssue_0 = io_in_bits_isFirstIssue;
  wire       io_rightOutFire_0 = io_rightOutFire;
  wire       io_isFlush_0 = io_isFlush;
  wire       io_isOlder = 1'h0;
  wire       io_out_ready = 1'h1;
  wire       io_in_ready = 1'h1;
  reg        valid;
  wire       io_out_valid_0 = valid;
  struct packed {logic [35:0] fuType; logic [8:0] fuOpType; logic is0Lat; logic rfWen; logic flushPipe; logic isRVC; struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] value; }[1:0] dataSources; struct packed {logic [3:0] value; }[1:0] exuSources; logic [2:0][1:0] loadDependency; }
    data_ctrl;
  wire
    struct packed {logic [35:0] fuType; logic [8:0] fuOpType; logic is0Lat; logic rfWen; logic flushPipe; logic isRVC; struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] value; }[1:0] dataSources; struct packed {logic [3:0] value; }[1:0] exuSources; logic [2:0][1:0] loadDependency; }
    io_out_bits_ctrl_0 = data_ctrl;
  struct packed {logic [1:0][63:0] src; logic [63:0] imm; logic [49:0] pc; } data_data;
  wire struct packed {logic [1:0][63:0] src; logic [63:0] imm; logic [49:0] pc; }
    io_out_bits_data_0 = data_data;
  reg        data_toRobValid;
  wire       io_out_bits_toRobValid_0 = data_toRobValid;
  struct packed {logic flag; logic [8:0] value; } data_robIdx;
  wire struct packed {logic flag; logic [8:0] value; } io_out_bits_robIdx_0 = data_robIdx;
  struct packed {logic [7:0] pdest; } data_toRF;
  wire struct packed {logic [7:0] pdest; } io_out_bits_toRF_0 = data_toRF;
  reg  [4:0] data_iqIdx;
  wire [4:0] io_out_bits_iqIdx_0 = data_iqIdx;
  reg        data_isFirstIssue;
  wire       io_out_bits_isFirstIssue_0 = data_isFirstIssue;
  always @(posedge clock or posedge reset) begin
    if (reset)
      valid <= 1'h0;
    else
      valid <= ~io_isFlush_0 & (io_in_valid_0 | ~io_rightOutFire_0 & valid);
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    automatic logic [3:0]      _GEN =
      io_in_valid_0
        ? io_in_bits_ctrl_0.exuSources[1'h1].value
        : data_ctrl.exuSources[1'h1].value;
    automatic       struct packed {logic [3:0] value; } _GEN_0 = '{value: _GEN};
    automatic logic [3:0]      _GEN_1 =
      io_in_valid_0
        ? io_in_bits_ctrl_0.exuSources[1'h0].value
        : data_ctrl.exuSources[1'h0].value;
    automatic       struct packed {logic [3:0] value; } _GEN_2 = '{value: _GEN_1};
    automatic logic [3:0]      _GEN_3 =
      io_in_valid_0
        ? io_in_bits_ctrl_0.dataSources[1'h1].value
        : data_ctrl.dataSources[1'h1].value;
    automatic       struct packed {logic [3:0] value; } _GEN_4 = '{value: _GEN_3};
    automatic logic [3:0]      _GEN_5 =
      io_in_valid_0
        ? io_in_bits_ctrl_0.dataSources[1'h0].value
        : data_ctrl.dataSources[1'h0].value;
    automatic       struct packed {logic [3:0] value; } _GEN_6 = '{value: _GEN_5};
    automatic logic [2:0][1:0] _GEN_7 =
      io_in_valid_0 ? io_in_bits_ctrl_0.loadDependency : data_ctrl.loadDependency;
    automatic logic [5:0]      _GEN_8 =
      io_in_valid_0 ? io_in_bits_ctrl_0.ftqIdx.value : data_ctrl.ftqIdx.value;
    automatic logic            _GEN_9 =
      io_in_valid_0 ? io_in_bits_ctrl_0.ftqIdx.flag : data_ctrl.ftqIdx.flag;
    automatic       struct packed {logic flag; logic [5:0] value; } _GEN_10 =
      '{flag: _GEN_9, value: _GEN_8};
    automatic logic [4:0]      _GEN_11 =
      io_in_valid_0 ? io_in_bits_ctrl_0.ftqOffset : data_ctrl.ftqOffset;
    automatic logic            _GEN_12 =
      io_in_valid_0 ? io_in_bits_ctrl_0.isRVC : data_ctrl.isRVC;
    automatic logic            _GEN_13 =
      io_in_valid_0 ? io_in_bits_ctrl_0.flushPipe : data_ctrl.flushPipe;
    automatic logic            _GEN_14 =
      io_in_valid_0 ? io_in_bits_ctrl_0.rfWen : data_ctrl.rfWen;
    automatic logic            _GEN_15 =
      io_in_valid_0 ? io_in_bits_ctrl_0.is0Lat : data_ctrl.is0Lat;
    automatic logic [8:0]      _GEN_16 =
      io_in_valid_0 ? io_in_bits_ctrl_0.fuOpType : data_ctrl.fuOpType;
    automatic logic [35:0]     _GEN_17 =
      io_in_valid_0 ? io_in_bits_ctrl_0.fuType : data_ctrl.fuType;
    data_ctrl <=
      '{fuType: _GEN_17,
        fuOpType: _GEN_16,
        is0Lat: _GEN_15,
        rfWen: _GEN_14,
        flushPipe: _GEN_13,
        isRVC: _GEN_12,
        ftqIdx: _GEN_10,
        ftqOffset: _GEN_11,
        dataSources: ({{_GEN_4}, {_GEN_6}}),
        exuSources: ({{_GEN_0}, {_GEN_2}}),
        loadDependency: _GEN_7};
  end // always @(posedge)
  always @(posedge clock) begin
    automatic logic [1:0][63:0] _GEN_18 =
      io_in_valid_0 ? io_in_bits_data_0.src : data_data.src;
    automatic logic [49:0]      _GEN_19 =
      io_in_valid_0 ? io_in_bits_data_0.pc : data_data.pc;
    automatic logic [63:0]      _GEN_20 =
      io_in_valid_0 ? io_in_bits_data_0.imm : data_data.imm;
    data_data <= '{src: _GEN_18, imm: _GEN_20, pc: _GEN_19};
  end // always @(posedge)
  always @(posedge clock) begin
    if (io_in_valid_0)
      data_toRobValid <= io_in_bits_toRobValid_0;
  end // always @(posedge)
  always @(posedge clock) begin
    automatic logic [8:0] _GEN_21 =
      io_in_valid_0 ? io_in_bits_robIdx_0.value : data_robIdx.value;
    automatic logic       _GEN_22 =
      io_in_valid_0 ? io_in_bits_robIdx_0.flag : data_robIdx.flag;
    data_robIdx <= '{flag: _GEN_22, value: _GEN_21};
  end // always @(posedge)
  always @(posedge clock) begin
    automatic logic [7:0] _GEN_23 =
      io_in_valid_0 ? io_in_bits_toRF_0.pdest : data_toRF.pdest;
    data_toRF <= '{pdest: _GEN_23};
  end // always @(posedge)
  always @(posedge clock) begin
    if (io_in_valid_0)
      data_iqIdx <= io_in_bits_iqIdx_0;
  end // always @(posedge)
  always @(posedge clock) begin
    if (io_in_valid_0)
      data_isFirstIssue <= io_in_bits_isFirstIssue_0;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset)
        valid = 1'h0;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_valid = io_out_valid_0;
  assign io_out_bits_ctrl = io_out_bits_ctrl_0;
  assign io_out_bits_data = io_out_bits_data_0;
  assign io_out_bits_toRobValid = io_out_bits_toRobValid_0;
  assign io_out_bits_robIdx = io_out_bits_robIdx_0;
  assign io_out_bits_toRF = io_out_bits_toRF_0;
  assign io_out_bits_iqIdx = io_out_bits_iqIdx_0;
  assign io_out_bits_isFirstIssue = io_out_bits_isFirstIssue_0;
endmodule

