// Generated by CIRCT firtool-1.150.2
module NfMappedElemIdx(
  input  struct packed {logic [2:0] nf; logic [3:0] eewOH; }                                      in,
  output struct packed {struct packed {logic [7:0] from; logic [7:0] untilv; }[7:0] idxRangeVec; } out
);

  wire struct packed {logic [7:0] from; logic [7:0] untilv; }[7:0][7:0] _GEN;
  wire struct packed {logic [7:0] from; logic [7:0] untilv; }[7:0][7:0] rangeTable =
    '{'{'{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10}},
      '{'{from: 8'h10, untilv: 8'h20},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10}},
      '{'{from: 8'h10, untilv: 8'h20},
        '{from: 8'h10, untilv: 8'h20},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10}},
      '{'{from: 8'h10, untilv: 8'h20},
        '{from: 8'h10, untilv: 8'h20},
        '{from: 8'h10, untilv: 8'h20},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10}},
      '{'{from: 8'h10, untilv: 8'h20},
        '{from: 8'h10, untilv: 8'h20},
        '{from: 8'h10, untilv: 8'h20},
        '{from: 8'h10, untilv: 8'h20},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10}},
      '{'{from: 8'h20, untilv: 8'h30},
        '{from: 8'h20, untilv: 8'h30},
        '{from: 8'h10, untilv: 8'h20},
        '{from: 8'h10, untilv: 8'h20},
        '{from: 8'h10, untilv: 8'h20},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10}},
      '{'{from: 8'h30, untilv: 8'h40},
        '{from: 8'h30, untilv: 8'h40},
        '{from: 8'h20, untilv: 8'h30},
        '{from: 8'h20, untilv: 8'h30},
        '{from: 8'h10, untilv: 8'h20},
        '{from: 8'h10, untilv: 8'h20},
        '{from: 8'h0, untilv: 8'h10},
        '{from: 8'h0, untilv: 8'h10}},
      '{'{from: 8'h70, untilv: 8'h80},
        '{from: 8'h60, untilv: 8'h70},
        '{from: 8'h50, untilv: 8'h60},
        '{from: 8'h40, untilv: 8'h50},
        '{from: 8'h30, untilv: 8'h40},
        '{from: 8'h20, untilv: 8'h30},
        '{from: 8'h10, untilv: 8'h20},
        '{from: 8'h0, untilv: 8'h10}}};
  wire [7:0] _GEN_0 =
    {3'h0, in.eewOH[0], 4'h0} | {4'h0, in.eewOH[1], 3'h0} | {5'h0, in.eewOH[2], 2'h0}
    | {6'h0, in.eewOH[3], 1'h0};
  wire [7:0] _GEN_1 =
    {2'h0, in.eewOH[0], 5'h0} | {3'h0, in.eewOH[1], 4'h0} | {4'h0, in.eewOH[2], 3'h0}
    | {5'h0, in.eewOH[3], 2'h0};
  wire [7:0] _GEN_2 = in.eewOH[0] ? 8'h30 : 8'h0;
  wire [7:0] _GEN_3 = in.eewOH[1] ? 8'h18 : 8'h0;
  wire [7:0] _GEN_4 = in.eewOH[2] ? 8'hC : 8'h0;
  wire [7:0] _GEN_5 = in.eewOH[3] ? 8'h6 : 8'h0;
  wire [7:0] _GEN_6 = _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5;
  wire [7:0] _GEN_7 =
    {1'h0, in.eewOH[0], 6'h0} | {2'h0, in.eewOH[1], 5'h0} | {3'h0, in.eewOH[2], 4'h0}
    | {4'h0, in.eewOH[3], 3'h0};
  wire [7:0] _GEN_8 = in.eewOH[0] ? 8'h50 : 8'h0;
  wire [7:0] _GEN_9 = in.eewOH[1] ? 8'h28 : 8'h0;
  wire [7:0] _GEN_10 = in.eewOH[2] ? 8'h14 : 8'h0;
  wire [7:0] _GEN_11 = in.eewOH[3] ? 8'hA : 8'h0;
  wire [7:0] _GEN_12 = _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11;
  wire [7:0] _GEN_13 = in.eewOH[0] ? 8'h60 : 8'h0;
  wire [7:0] _GEN_14 = in.eewOH[1] ? 8'h30 : 8'h0;
  wire [7:0] _GEN_15 = in.eewOH[2] ? 8'h18 : 8'h0;
  wire [7:0] _GEN_16 = in.eewOH[3] ? 8'hC : 8'h0;
  wire [7:0] _GEN_17 = _GEN_13 | _GEN_14 | _GEN_15 | _GEN_16;
  wire [7:0] _GEN_18 = in.eewOH[0] ? 8'h70 : 8'h0;
  wire [7:0] _GEN_19 = in.eewOH[1] ? 8'h38 : 8'h0;
  wire [7:0] _GEN_20 = in.eewOH[2] ? 8'h1C : 8'h0;
  wire [7:0] _GEN_21 = in.eewOH[3] ? 8'hE : 8'h0;
  wire [7:0] _GEN_22 = _GEN_18 | _GEN_19 | _GEN_20 | _GEN_21;
  wire struct packed {logic [7:0] from; logic [7:0] untilv; } _GEN_23 =
    '{from: (8'h0), untilv: _GEN_0};
  wire struct packed {logic [7:0] from; logic [7:0] untilv; } _GEN_24 =
    '{from: _GEN_0, untilv: _GEN_1};
  wire struct packed {logic [7:0] from; logic [7:0] untilv; } _GEN_25 =
    '{from: _GEN_1, untilv: _GEN_6};
  wire struct packed {logic [7:0] from; logic [7:0] untilv; } _GEN_26 =
    '{from: _GEN_6, untilv: _GEN_7};
  wire struct packed {logic [7:0] from; logic [7:0] untilv; } _GEN_27 =
    '{from: _GEN_7, untilv: _GEN_12};
  wire struct packed {logic [7:0] from; logic [7:0] untilv; } _GEN_28 =
    '{from: _GEN_12, untilv: _GEN_17};
  wire struct packed {logic [7:0] from; logic [7:0] untilv; } _GEN_29 =
    '{from: _GEN_17, untilv: _GEN_22};
  wire struct packed {logic [7:0] from; logic [7:0] untilv; } _GEN_30 =
    '{from: _GEN_22,
      untilv:
        ({in.eewOH[0], 7'h0} | {1'h0, in.eewOH[1], 6'h0} | {2'h0, in.eewOH[2], 5'h0}
         | {3'h0, in.eewOH[3], 4'h0})};
  assign _GEN =
    {{{{_GEN_23},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23}}},
     {{{_GEN_24},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23}}},
     {{{_GEN_24},
       {_GEN_24},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23}}},
     {{{_GEN_24},
       {_GEN_24},
       {_GEN_24},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23}}},
     {{{_GEN_24},
       {_GEN_24},
       {_GEN_24},
       {_GEN_24},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23}}},
     {{{_GEN_25},
       {_GEN_25},
       {_GEN_24},
       {_GEN_24},
       {_GEN_24},
       {_GEN_23},
       {_GEN_23},
       {_GEN_23}}},
     {{{_GEN_26},
       {_GEN_26},
       {_GEN_25},
       {_GEN_25},
       {_GEN_24},
       {_GEN_24},
       {_GEN_23},
       {_GEN_23}}},
     {{{_GEN_30},
       {_GEN_29},
       {_GEN_28},
       {_GEN_27},
       {_GEN_26},
       {_GEN_25},
       {_GEN_24},
       {_GEN_23}}}};
  assign out = '{idxRangeVec: _GEN[in.nf]};
endmodule
