// Generated by CIRCT firtool-1.150.2
module r4_qds(
  input  [6:0] rem_i,
               m_neg_1_i,
               m_neg_0_i,
               m_pos_1_i,
               m_pos_2_i,
  output [4:0] rt_dig_o
);

  wire [6:0] _qds_sign_T = rem_i + m_pos_2_i;
  wire [6:0] _qds_sign_T_3 = rem_i + m_pos_1_i;
  wire [6:0] _qds_sign_T_6 = rem_i + m_neg_0_i;
  wire [6:0] _qds_sign_T_9 = rem_i + m_neg_1_i;
  wire [3:0] qds_sign =
    {_qds_sign_T[6], _qds_sign_T_3[6], _qds_sign_T_6[6], _qds_sign_T_9[6]};
  assign rt_dig_o =
    {&(qds_sign[1:0]),
     qds_sign[1:0] == 2'h2,
     qds_sign[2:1] == 2'h2,
     qds_sign[3:2] == 2'h2,
     qds_sign[3:2] == 2'h0};
endmodule

