// Generated by CIRCT firtool-1.150.2
module RegCache(
  input                                                      clock,
                                                             reset,
                                                             io_readPorts_0_ren,
  input  [5:0]                                               io_readPorts_0_addr,
  output [63:0]                                              io_readPorts_0_data,
  input                                                      io_readPorts_1_ren,
  input  [5:0]                                               io_readPorts_1_addr,
  output [63:0]                                              io_readPorts_1_data,
  input                                                      io_readPorts_2_ren,
  input  [5:0]                                               io_readPorts_2_addr,
  output [63:0]                                              io_readPorts_2_data,
  input                                                      io_readPorts_3_ren,
  input  [5:0]                                               io_readPorts_3_addr,
  output [63:0]                                              io_readPorts_3_data,
  input                                                      io_readPorts_4_ren,
  input  [5:0]                                               io_readPorts_4_addr,
  output [63:0]                                              io_readPorts_4_data,
  input                                                      io_readPorts_5_ren,
  input  [5:0]                                               io_readPorts_5_addr,
  output [63:0]                                              io_readPorts_5_data,
  input                                                      io_readPorts_6_ren,
  input  [5:0]                                               io_readPorts_6_addr,
  output [63:0]                                              io_readPorts_6_data,
  input                                                      io_readPorts_7_ren,
  input  [5:0]                                               io_readPorts_7_addr,
  output [63:0]                                              io_readPorts_7_data,
  input                                                      io_readPorts_8_ren,
  input  [5:0]                                               io_readPorts_8_addr,
  output [63:0]                                              io_readPorts_8_data,
  input                                                      io_readPorts_9_ren,
  input  [5:0]                                               io_readPorts_9_addr,
  output [63:0]                                              io_readPorts_9_data,
  input                                                      io_readPorts_10_ren,
  input  [5:0]                                               io_readPorts_10_addr,
  output [63:0]                                              io_readPorts_10_data,
  input                                                      io_readPorts_11_ren,
  input  [5:0]                                               io_readPorts_11_addr,
  output [63:0]                                              io_readPorts_11_data,
  input                                                      io_readPorts_12_ren,
  input  [5:0]                                               io_readPorts_12_addr,
  output [63:0]                                              io_readPorts_12_data,
  input                                                      io_readPorts_13_ren,
  input  [5:0]                                               io_readPorts_13_addr,
  output [63:0]                                              io_readPorts_13_data,
  input                                                      io_readPorts_14_ren,
  input  [5:0]                                               io_readPorts_14_addr,
  output [63:0]                                              io_readPorts_14_data,
  input                                                      io_readPorts_15_ren,
  input  [5:0]                                               io_readPorts_15_addr,
  output [63:0]                                              io_readPorts_15_data,
  input                                                      io_readPorts_16_ren,
  input  [5:0]                                               io_readPorts_16_addr,
  output [63:0]                                              io_readPorts_16_data,
  input                                                      io_readPorts_17_ren,
  input  [5:0]                                               io_readPorts_17_addr,
  output [63:0]                                              io_readPorts_17_data,
  input                                                      io_readPorts_18_ren,
  input  [5:0]                                               io_readPorts_18_addr,
  output [63:0]                                              io_readPorts_18_data,
  input                                                      io_readPorts_19_ren,
  input  [5:0]                                               io_readPorts_19_addr,
  output [63:0]                                              io_readPorts_19_data,
  input                                                      io_readPorts_20_ren,
  input  [5:0]                                               io_readPorts_20_addr,
  output [63:0]                                              io_readPorts_20_data,
  input                                                      io_readPorts_21_ren,
  input  [5:0]                                               io_readPorts_21_addr,
  output [63:0]                                              io_readPorts_21_data,
  input                                                      io_readPorts_22_ren,
  input  [5:0]                                               io_readPorts_22_addr,
  output [63:0]                                              io_readPorts_22_data,
  input                                                      io_readPorts_23_ren,
  input  [5:0]                                               io_readPorts_23_addr,
  output [63:0]                                              io_readPorts_23_data,
  input                                                      io_readPorts_24_ren,
  input  [5:0]                                               io_readPorts_24_addr,
  output [63:0]                                              io_readPorts_24_data,
  input                                                      io_writePorts_0_wen,
  input  [5:0]                                               io_writePorts_0_addr,
  input  [63:0]                                              io_writePorts_0_data,
  input                                                      io_writePorts_1_wen,
  input  [5:0]                                               io_writePorts_1_addr,
  input  [63:0]                                              io_writePorts_1_data,
  input                                                      io_writePorts_2_wen,
  input  [5:0]                                               io_writePorts_2_addr,
  input  [63:0]                                              io_writePorts_2_data,
  input                                                      io_writePorts_3_wen,
  input  [5:0]                                               io_writePorts_3_addr,
  input  [63:0]                                              io_writePorts_3_data,
  input                                                      io_writePorts_4_wen,
  input  [5:0]                                               io_writePorts_4_addr,
  input  [63:0]                                              io_writePorts_4_data,
  input                                                      io_writePorts_5_wen,
  input  [5:0]                                               io_writePorts_5_addr,
  input  [63:0]                                              io_writePorts_5_data,
  input                                                      io_writePorts_6_wen,
  input  [5:0]                                               io_writePorts_6_addr,
  input  [63:0]                                              io_writePorts_6_data,
  input                                                      io_writePorts_7_wen,
  input  [5:0]                                               io_writePorts_7_addr,
  input  [63:0]                                              io_writePorts_7_data,
  input                                                      io_writePorts_8_wen,
  input  [5:0]                                               io_writePorts_8_addr,
  input  [63:0]                                              io_writePorts_8_data,
  output [8:0][5:0]                                          io_toWakeupQueueRCIdx,
  input  struct packed {logic wen; logic [5:0] rcIdx; }[8:0] io_diffRcIdx
);

  wire [2:0][3:0]   _age_1_io_out;
  wire [11:0][11:0] _MemRegCacheAgeTimer_io_ageInfo;
  wire [23:0][23:0] _IntRegCacheAgeTimer_io_ageInfo;
  wire [63:0]       _MemRegCache_io_readPorts_0_data;
  wire [63:0]       _MemRegCache_io_readPorts_1_data;
  wire [63:0]       _MemRegCache_io_readPorts_2_data;
  wire [63:0]       _MemRegCache_io_readPorts_3_data;
  wire [63:0]       _MemRegCache_io_readPorts_4_data;
  wire [63:0]       _MemRegCache_io_readPorts_5_data;
  wire [63:0]       _MemRegCache_io_readPorts_6_data;
  wire [63:0]       _MemRegCache_io_readPorts_7_data;
  wire [63:0]       _MemRegCache_io_readPorts_8_data;
  wire [63:0]       _MemRegCache_io_readPorts_9_data;
  wire [63:0]       _MemRegCache_io_readPorts_10_data;
  wire [63:0]       _MemRegCache_io_readPorts_11_data;
  wire [63:0]       _MemRegCache_io_readPorts_12_data;
  wire [63:0]       _MemRegCache_io_readPorts_13_data;
  wire [63:0]       _MemRegCache_io_readPorts_14_data;
  wire [63:0]       _MemRegCache_io_readPorts_15_data;
  wire [63:0]       _MemRegCache_io_readPorts_16_data;
  wire [63:0]       _MemRegCache_io_readPorts_17_data;
  wire [63:0]       _MemRegCache_io_readPorts_18_data;
  wire [63:0]       _MemRegCache_io_readPorts_19_data;
  wire [63:0]       _MemRegCache_io_readPorts_20_data;
  wire [63:0]       _MemRegCache_io_readPorts_21_data;
  wire [63:0]       _MemRegCache_io_readPorts_22_data;
  wire [63:0]       _MemRegCache_io_readPorts_23_data;
  wire [63:0]       _MemRegCache_io_readPorts_24_data;
  wire [11:0]       _MemRegCache_io_validInfo;
  wire [63:0]       _IntRegCache_io_readPorts_0_data;
  wire [63:0]       _IntRegCache_io_readPorts_1_data;
  wire [63:0]       _IntRegCache_io_readPorts_2_data;
  wire [63:0]       _IntRegCache_io_readPorts_3_data;
  wire [63:0]       _IntRegCache_io_readPorts_4_data;
  wire [63:0]       _IntRegCache_io_readPorts_5_data;
  wire [63:0]       _IntRegCache_io_readPorts_6_data;
  wire [63:0]       _IntRegCache_io_readPorts_7_data;
  wire [63:0]       _IntRegCache_io_readPorts_8_data;
  wire [63:0]       _IntRegCache_io_readPorts_9_data;
  wire [63:0]       _IntRegCache_io_readPorts_10_data;
  wire [63:0]       _IntRegCache_io_readPorts_11_data;
  wire [63:0]       _IntRegCache_io_readPorts_12_data;
  wire [63:0]       _IntRegCache_io_readPorts_13_data;
  wire [63:0]       _IntRegCache_io_readPorts_14_data;
  wire [63:0]       _IntRegCache_io_readPorts_15_data;
  wire [63:0]       _IntRegCache_io_readPorts_16_data;
  wire [63:0]       _IntRegCache_io_readPorts_17_data;
  wire [63:0]       _IntRegCache_io_readPorts_18_data;
  wire [63:0]       _IntRegCache_io_readPorts_19_data;
  wire [63:0]       _IntRegCache_io_readPorts_20_data;
  wire [63:0]       _IntRegCache_io_readPorts_21_data;
  wire [63:0]       _IntRegCache_io_readPorts_22_data;
  wire [63:0]       _IntRegCache_io_readPorts_23_data;
  wire [63:0]       _IntRegCache_io_readPorts_24_data;
  wire [23:0]       _IntRegCache_io_validInfo;
  wire
    struct packed {struct packed {logic ren; logic [5:0] addr; logic [63:0] data; }[24:0] readPorts; struct packed {logic wen; logic [5:0] addr; logic [63:0] data; }[8:0] writePorts; logic [8:0][5:0] toWakeupQueueRCIdx; struct packed {logic wen; logic [5:0] rcIdx; }[8:0] diffRcIdx; }
    io;
  wire [5:0][4:0]   IntRegCacheRepRCIdx;
  wire [2:0][4:0]   MemRegCacheRepRCIdx;
  assign MemRegCacheRepRCIdx =
    {{{1'h0, _age_1_io_out[2'h2]}},
     {{1'h0, _age_1_io_out[2'h1]}},
     {{1'h0, _age_1_io_out[2'h0]}}};
  reg  [5:0]        in_addr;
  reg               int_ren_last_REG;
  wire              int_ren = int_ren_last_REG;
  reg               mem_ren_last_REG;
  wire              mem_ren = mem_ren_last_REG;
  wire [63:0]       _io_readPorts_0_data_T_1 =
    in_addr[5] ? _MemRegCache_io_readPorts_0_data : _IntRegCache_io_readPorts_0_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN =
    '{ren: io_readPorts_0_ren, addr: io_readPorts_0_addr, data: _io_readPorts_0_data_T_1};
  reg  [5:0]        in_addr_1;
  reg               int_ren_last_REG_1;
  wire              int_ren_1 = int_ren_last_REG_1;
  reg               mem_ren_last_REG_1;
  wire              mem_ren_1 = mem_ren_last_REG_1;
  wire [63:0]       _io_readPorts_1_data_T_1 =
    in_addr_1[5] ? _MemRegCache_io_readPorts_1_data : _IntRegCache_io_readPorts_1_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_0 =
    '{ren: io_readPorts_1_ren, addr: io_readPorts_1_addr, data: _io_readPorts_1_data_T_1};
  reg  [5:0]        in_addr_2;
  reg               int_ren_last_REG_2;
  wire              int_ren_2 = int_ren_last_REG_2;
  reg               mem_ren_last_REG_2;
  wire              mem_ren_2 = mem_ren_last_REG_2;
  wire [63:0]       _io_readPorts_2_data_T_1 =
    in_addr_2[5] ? _MemRegCache_io_readPorts_2_data : _IntRegCache_io_readPorts_2_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_1 =
    '{ren: io_readPorts_2_ren, addr: io_readPorts_2_addr, data: _io_readPorts_2_data_T_1};
  reg  [5:0]        in_addr_3;
  reg               int_ren_last_REG_3;
  wire              int_ren_3 = int_ren_last_REG_3;
  reg               mem_ren_last_REG_3;
  wire              mem_ren_3 = mem_ren_last_REG_3;
  wire [63:0]       _io_readPorts_3_data_T_1 =
    in_addr_3[5] ? _MemRegCache_io_readPorts_3_data : _IntRegCache_io_readPorts_3_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_2 =
    '{ren: io_readPorts_3_ren, addr: io_readPorts_3_addr, data: _io_readPorts_3_data_T_1};
  reg  [5:0]        in_addr_4;
  reg               int_ren_last_REG_4;
  wire              int_ren_4 = int_ren_last_REG_4;
  reg               mem_ren_last_REG_4;
  wire              mem_ren_4 = mem_ren_last_REG_4;
  wire [63:0]       _io_readPorts_4_data_T_1 =
    in_addr_4[5] ? _MemRegCache_io_readPorts_4_data : _IntRegCache_io_readPorts_4_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_3 =
    '{ren: io_readPorts_4_ren, addr: io_readPorts_4_addr, data: _io_readPorts_4_data_T_1};
  reg  [5:0]        in_addr_5;
  reg               int_ren_last_REG_5;
  wire              int_ren_5 = int_ren_last_REG_5;
  reg               mem_ren_last_REG_5;
  wire              mem_ren_5 = mem_ren_last_REG_5;
  wire [63:0]       _io_readPorts_5_data_T_1 =
    in_addr_5[5] ? _MemRegCache_io_readPorts_5_data : _IntRegCache_io_readPorts_5_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_4 =
    '{ren: io_readPorts_5_ren, addr: io_readPorts_5_addr, data: _io_readPorts_5_data_T_1};
  reg  [5:0]        in_addr_6;
  reg               int_ren_last_REG_6;
  wire              int_ren_6 = int_ren_last_REG_6;
  reg               mem_ren_last_REG_6;
  wire              mem_ren_6 = mem_ren_last_REG_6;
  wire [63:0]       _io_readPorts_6_data_T_1 =
    in_addr_6[5] ? _MemRegCache_io_readPorts_6_data : _IntRegCache_io_readPorts_6_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_5 =
    '{ren: io_readPorts_6_ren, addr: io_readPorts_6_addr, data: _io_readPorts_6_data_T_1};
  reg  [5:0]        in_addr_7;
  reg               int_ren_last_REG_7;
  wire              int_ren_7 = int_ren_last_REG_7;
  reg               mem_ren_last_REG_7;
  wire              mem_ren_7 = mem_ren_last_REG_7;
  wire [63:0]       _io_readPorts_7_data_T_1 =
    in_addr_7[5] ? _MemRegCache_io_readPorts_7_data : _IntRegCache_io_readPorts_7_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_6 =
    '{ren: io_readPorts_7_ren, addr: io_readPorts_7_addr, data: _io_readPorts_7_data_T_1};
  reg  [5:0]        in_addr_8;
  reg               int_ren_last_REG_8;
  wire              int_ren_8 = int_ren_last_REG_8;
  reg               mem_ren_last_REG_8;
  wire              mem_ren_8 = mem_ren_last_REG_8;
  wire [63:0]       _io_readPorts_8_data_T_1 =
    in_addr_8[5] ? _MemRegCache_io_readPorts_8_data : _IntRegCache_io_readPorts_8_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_7 =
    '{ren: io_readPorts_8_ren, addr: io_readPorts_8_addr, data: _io_readPorts_8_data_T_1};
  reg  [5:0]        in_addr_9;
  reg               int_ren_last_REG_9;
  wire              int_ren_9 = int_ren_last_REG_9;
  reg               mem_ren_last_REG_9;
  wire              mem_ren_9 = mem_ren_last_REG_9;
  wire [63:0]       _io_readPorts_9_data_T_1 =
    in_addr_9[5] ? _MemRegCache_io_readPorts_9_data : _IntRegCache_io_readPorts_9_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_8 =
    '{ren: io_readPorts_9_ren, addr: io_readPorts_9_addr, data: _io_readPorts_9_data_T_1};
  reg  [5:0]        in_addr_10;
  reg               int_ren_last_REG_10;
  wire              int_ren_10 = int_ren_last_REG_10;
  reg               mem_ren_last_REG_10;
  wire              mem_ren_10 = mem_ren_last_REG_10;
  wire [63:0]       _io_readPorts_10_data_T_1 =
    in_addr_10[5] ? _MemRegCache_io_readPorts_10_data : _IntRegCache_io_readPorts_10_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_9 =
    '{ren: io_readPorts_10_ren,
      addr: io_readPorts_10_addr,
      data: _io_readPorts_10_data_T_1};
  reg  [5:0]        in_addr_11;
  reg               int_ren_last_REG_11;
  wire              int_ren_11 = int_ren_last_REG_11;
  reg               mem_ren_last_REG_11;
  wire              mem_ren_11 = mem_ren_last_REG_11;
  wire [63:0]       _io_readPorts_11_data_T_1 =
    in_addr_11[5] ? _MemRegCache_io_readPorts_11_data : _IntRegCache_io_readPorts_11_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_10 =
    '{ren: io_readPorts_11_ren,
      addr: io_readPorts_11_addr,
      data: _io_readPorts_11_data_T_1};
  reg  [5:0]        in_addr_12;
  reg               int_ren_last_REG_12;
  wire              int_ren_12 = int_ren_last_REG_12;
  reg               mem_ren_last_REG_12;
  wire              mem_ren_12 = mem_ren_last_REG_12;
  wire [63:0]       _io_readPorts_12_data_T_1 =
    in_addr_12[5] ? _MemRegCache_io_readPorts_12_data : _IntRegCache_io_readPorts_12_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_11 =
    '{ren: io_readPorts_12_ren,
      addr: io_readPorts_12_addr,
      data: _io_readPorts_12_data_T_1};
  reg  [5:0]        in_addr_13;
  reg               int_ren_last_REG_13;
  wire              int_ren_13 = int_ren_last_REG_13;
  reg               mem_ren_last_REG_13;
  wire              mem_ren_13 = mem_ren_last_REG_13;
  wire [63:0]       _io_readPorts_13_data_T_1 =
    in_addr_13[5] ? _MemRegCache_io_readPorts_13_data : _IntRegCache_io_readPorts_13_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_12 =
    '{ren: io_readPorts_13_ren,
      addr: io_readPorts_13_addr,
      data: _io_readPorts_13_data_T_1};
  reg  [5:0]        in_addr_14;
  reg               int_ren_last_REG_14;
  wire              int_ren_14 = int_ren_last_REG_14;
  reg               mem_ren_last_REG_14;
  wire              mem_ren_14 = mem_ren_last_REG_14;
  wire [63:0]       _io_readPorts_14_data_T_1 =
    in_addr_14[5] ? _MemRegCache_io_readPorts_14_data : _IntRegCache_io_readPorts_14_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_13 =
    '{ren: io_readPorts_14_ren,
      addr: io_readPorts_14_addr,
      data: _io_readPorts_14_data_T_1};
  reg  [5:0]        in_addr_15;
  reg               int_ren_last_REG_15;
  wire              int_ren_15 = int_ren_last_REG_15;
  reg               mem_ren_last_REG_15;
  wire              mem_ren_15 = mem_ren_last_REG_15;
  wire [63:0]       _io_readPorts_15_data_T_1 =
    in_addr_15[5] ? _MemRegCache_io_readPorts_15_data : _IntRegCache_io_readPorts_15_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_14 =
    '{ren: io_readPorts_15_ren,
      addr: io_readPorts_15_addr,
      data: _io_readPorts_15_data_T_1};
  reg  [5:0]        in_addr_16;
  reg               int_ren_last_REG_16;
  wire              int_ren_16 = int_ren_last_REG_16;
  reg               mem_ren_last_REG_16;
  wire              mem_ren_16 = mem_ren_last_REG_16;
  wire [63:0]       _io_readPorts_16_data_T_1 =
    in_addr_16[5] ? _MemRegCache_io_readPorts_16_data : _IntRegCache_io_readPorts_16_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_15 =
    '{ren: io_readPorts_16_ren,
      addr: io_readPorts_16_addr,
      data: _io_readPorts_16_data_T_1};
  reg  [5:0]        in_addr_17;
  reg               int_ren_last_REG_17;
  wire              int_ren_17 = int_ren_last_REG_17;
  reg               mem_ren_last_REG_17;
  wire              mem_ren_17 = mem_ren_last_REG_17;
  wire [63:0]       _io_readPorts_17_data_T_1 =
    in_addr_17[5] ? _MemRegCache_io_readPorts_17_data : _IntRegCache_io_readPorts_17_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_16 =
    '{ren: io_readPorts_17_ren,
      addr: io_readPorts_17_addr,
      data: _io_readPorts_17_data_T_1};
  reg  [5:0]        in_addr_18;
  reg               int_ren_last_REG_18;
  wire              int_ren_18 = int_ren_last_REG_18;
  reg               mem_ren_last_REG_18;
  wire              mem_ren_18 = mem_ren_last_REG_18;
  wire [63:0]       _io_readPorts_18_data_T_1 =
    in_addr_18[5] ? _MemRegCache_io_readPorts_18_data : _IntRegCache_io_readPorts_18_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_17 =
    '{ren: io_readPorts_18_ren,
      addr: io_readPorts_18_addr,
      data: _io_readPorts_18_data_T_1};
  reg  [5:0]        in_addr_19;
  reg               int_ren_last_REG_19;
  wire              int_ren_19 = int_ren_last_REG_19;
  reg               mem_ren_last_REG_19;
  wire              mem_ren_19 = mem_ren_last_REG_19;
  wire [63:0]       _io_readPorts_19_data_T_1 =
    in_addr_19[5] ? _MemRegCache_io_readPorts_19_data : _IntRegCache_io_readPorts_19_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_18 =
    '{ren: io_readPorts_19_ren,
      addr: io_readPorts_19_addr,
      data: _io_readPorts_19_data_T_1};
  reg  [5:0]        in_addr_20;
  reg               int_ren_last_REG_20;
  wire              int_ren_20 = int_ren_last_REG_20;
  reg               mem_ren_last_REG_20;
  wire              mem_ren_20 = mem_ren_last_REG_20;
  wire [63:0]       _io_readPorts_20_data_T_1 =
    in_addr_20[5] ? _MemRegCache_io_readPorts_20_data : _IntRegCache_io_readPorts_20_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_19 =
    '{ren: io_readPorts_20_ren,
      addr: io_readPorts_20_addr,
      data: _io_readPorts_20_data_T_1};
  reg  [5:0]        in_addr_21;
  reg               int_ren_last_REG_21;
  wire              int_ren_21 = int_ren_last_REG_21;
  reg               mem_ren_last_REG_21;
  wire              mem_ren_21 = mem_ren_last_REG_21;
  wire [63:0]       _io_readPorts_21_data_T_1 =
    in_addr_21[5] ? _MemRegCache_io_readPorts_21_data : _IntRegCache_io_readPorts_21_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_20 =
    '{ren: io_readPorts_21_ren,
      addr: io_readPorts_21_addr,
      data: _io_readPorts_21_data_T_1};
  reg  [5:0]        in_addr_22;
  reg               int_ren_last_REG_22;
  wire              int_ren_22 = int_ren_last_REG_22;
  reg               mem_ren_last_REG_22;
  wire              mem_ren_22 = mem_ren_last_REG_22;
  wire [63:0]       _io_readPorts_22_data_T_1 =
    in_addr_22[5] ? _MemRegCache_io_readPorts_22_data : _IntRegCache_io_readPorts_22_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_21 =
    '{ren: io_readPorts_22_ren,
      addr: io_readPorts_22_addr,
      data: _io_readPorts_22_data_T_1};
  reg  [5:0]        in_addr_23;
  reg               int_ren_last_REG_23;
  wire              int_ren_23 = int_ren_last_REG_23;
  reg               mem_ren_last_REG_23;
  wire              mem_ren_23 = mem_ren_last_REG_23;
  wire [63:0]       _io_readPorts_23_data_T_1 =
    in_addr_23[5] ? _MemRegCache_io_readPorts_23_data : _IntRegCache_io_readPorts_23_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_22 =
    '{ren: io_readPorts_23_ren,
      addr: io_readPorts_23_addr,
      data: _io_readPorts_23_data_T_1};
  reg  [5:0]        in_addr_24;
  reg               int_ren_last_REG_24;
  wire              int_ren_24 = int_ren_last_REG_24;
  reg               mem_ren_last_REG_24;
  wire              mem_ren_24 = mem_ren_last_REG_24;
  wire [63:0]       _io_readPorts_24_data_T_1 =
    in_addr_24[5] ? _MemRegCache_io_readPorts_24_data : _IntRegCache_io_readPorts_24_data;
  wire struct packed {logic ren; logic [5:0] addr; logic [63:0] data; } _GEN_23 =
    '{ren: io_readPorts_24_ren,
      addr: io_readPorts_24_addr,
      data: _io_readPorts_24_data_T_1};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; }[8:0] writePorts;
  reg  [8:0][5:0]   delayToWakeupQueueRCIdx_REG;
  reg  [8:0][5:0]   delayToWakeupQueueRCIdx_REG_1;
  reg  [8:0][5:0]   delayToWakeupQueueRCIdx;
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_24 =
    '{wen: io.writePorts[4'h0].wen,
      addr: delayToWakeupQueueRCIdx[4'h0],
      data: io.writePorts[4'h0].data};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_25 =
    '{wen: io.writePorts[4'h1].wen,
      addr: delayToWakeupQueueRCIdx[4'h1],
      data: io.writePorts[4'h1].data};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_26 =
    '{wen: io.writePorts[4'h2].wen,
      addr: delayToWakeupQueueRCIdx[4'h2],
      data: io.writePorts[4'h2].data};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_27 =
    '{wen: io.writePorts[4'h3].wen,
      addr: delayToWakeupQueueRCIdx[4'h3],
      data: io.writePorts[4'h3].data};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_28 =
    '{wen: io.writePorts[4'h4].wen,
      addr: delayToWakeupQueueRCIdx[4'h4],
      data: io.writePorts[4'h4].data};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_29 =
    '{wen: io.writePorts[4'h5].wen,
      addr: delayToWakeupQueueRCIdx[4'h5],
      data: io.writePorts[4'h5].data};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_30 =
    '{wen: io.writePorts[4'h6].wen,
      addr: delayToWakeupQueueRCIdx[4'h6],
      data: io.writePorts[4'h6].data};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_31 =
    '{wen: io.writePorts[4'h7].wen,
      addr: delayToWakeupQueueRCIdx[4'h7],
      data: io.writePorts[4'h7].data};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_32 =
    '{wen: io.writePorts[4'h8].wen,
      addr: delayToWakeupQueueRCIdx[4'h8],
      data: io.writePorts[4'h8].data};
  assign writePorts =
    {{_GEN_32},
     {_GEN_31},
     {_GEN_30},
     {_GEN_29},
     {_GEN_28},
     {_GEN_27},
     {_GEN_26},
     {_GEN_25},
     {_GEN_24}};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_33 =
    '{wen: io_writePorts_0_wen, addr: io_writePorts_0_addr, data: io_writePorts_0_data};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_34 =
    '{wen: io_writePorts_1_wen, addr: io_writePorts_1_addr, data: io_writePorts_1_data};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_35 =
    '{wen: io_writePorts_2_wen, addr: io_writePorts_2_addr, data: io_writePorts_2_data};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_36 =
    '{wen: io_writePorts_3_wen, addr: io_writePorts_3_addr, data: io_writePorts_3_data};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_37 =
    '{wen: io_writePorts_4_wen, addr: io_writePorts_4_addr, data: io_writePorts_4_data};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_38 =
    '{wen: io_writePorts_5_wen, addr: io_writePorts_5_addr, data: io_writePorts_5_data};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_39 =
    '{wen: io_writePorts_6_wen, addr: io_writePorts_6_addr, data: io_writePorts_6_data};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_40 =
    '{wen: io_writePorts_7_wen, addr: io_writePorts_7_addr, data: io_writePorts_7_data};
  wire struct packed {logic wen; logic [5:0] addr; logic [63:0] data; } _GEN_41 =
    '{wen: io_writePorts_8_wen, addr: io_writePorts_8_addr, data: io_writePorts_8_data};
  assign io =
    '{readPorts:
        ({{_GEN_23},
          {_GEN_22},
          {_GEN_21},
          {_GEN_20},
          {_GEN_19},
          {_GEN_18},
          {_GEN_17},
          {_GEN_16},
          {_GEN_15},
          {_GEN_14},
          {_GEN_13},
          {_GEN_12},
          {_GEN_11},
          {_GEN_10},
          {_GEN_9},
          {_GEN_8},
          {_GEN_7},
          {_GEN_6},
          {_GEN_5},
          {_GEN_4},
          {_GEN_3},
          {_GEN_2},
          {_GEN_1},
          {_GEN_0},
          {_GEN}}),
      writePorts:
        ({{_GEN_41},
          {_GEN_40},
          {_GEN_39},
          {_GEN_38},
          {_GEN_37},
          {_GEN_36},
          {_GEN_35},
          {_GEN_34},
          {_GEN_33}}),
      toWakeupQueueRCIdx:
        ({{{1'h1, MemRegCacheRepRCIdx[2'h2]}},
          {{1'h1, MemRegCacheRepRCIdx[2'h1]}},
          {{1'h1, MemRegCacheRepRCIdx[2'h0]}},
          {{1'h0, IntRegCacheRepRCIdx[3'h5]}},
          {{1'h0, IntRegCacheRepRCIdx[3'h4]}},
          {{1'h0, IntRegCacheRepRCIdx[3'h3]}},
          {{1'h0, IntRegCacheRepRCIdx[3'h2]}},
          {{1'h0, IntRegCacheRepRCIdx[3'h1]}},
          {{1'h0, IntRegCacheRepRCIdx[3'h0]}}}),
      diffRcIdx: io_diffRcIdx};
  always @(posedge clock) begin
    if (io.readPorts[5'h0].ren)
      in_addr <= io.readPorts[5'h0].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG <= 1'h0;
    else
      int_ren_last_REG <= io.readPorts[5'h0].ren & ~(io.readPorts[5'h0].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG <= 1'h0;
    else
      mem_ren_last_REG <= io.readPorts[5'h0].ren & io.readPorts[5'h0].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h1].ren)
      in_addr_1 <= io.readPorts[5'h1].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_1 <= 1'h0;
    else
      int_ren_last_REG_1 <= io.readPorts[5'h1].ren & ~(io.readPorts[5'h1].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_1 <= 1'h0;
    else
      mem_ren_last_REG_1 <= io.readPorts[5'h1].ren & io.readPorts[5'h1].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h2].ren)
      in_addr_2 <= io.readPorts[5'h2].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_2 <= 1'h0;
    else
      int_ren_last_REG_2 <= io.readPorts[5'h2].ren & ~(io.readPorts[5'h2].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_2 <= 1'h0;
    else
      mem_ren_last_REG_2 <= io.readPorts[5'h2].ren & io.readPorts[5'h2].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h3].ren)
      in_addr_3 <= io.readPorts[5'h3].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_3 <= 1'h0;
    else
      int_ren_last_REG_3 <= io.readPorts[5'h3].ren & ~(io.readPorts[5'h3].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_3 <= 1'h0;
    else
      mem_ren_last_REG_3 <= io.readPorts[5'h3].ren & io.readPorts[5'h3].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h4].ren)
      in_addr_4 <= io.readPorts[5'h4].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_4 <= 1'h0;
    else
      int_ren_last_REG_4 <= io.readPorts[5'h4].ren & ~(io.readPorts[5'h4].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_4 <= 1'h0;
    else
      mem_ren_last_REG_4 <= io.readPorts[5'h4].ren & io.readPorts[5'h4].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h5].ren)
      in_addr_5 <= io.readPorts[5'h5].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_5 <= 1'h0;
    else
      int_ren_last_REG_5 <= io.readPorts[5'h5].ren & ~(io.readPorts[5'h5].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_5 <= 1'h0;
    else
      mem_ren_last_REG_5 <= io.readPorts[5'h5].ren & io.readPorts[5'h5].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h6].ren)
      in_addr_6 <= io.readPorts[5'h6].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_6 <= 1'h0;
    else
      int_ren_last_REG_6 <= io.readPorts[5'h6].ren & ~(io.readPorts[5'h6].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_6 <= 1'h0;
    else
      mem_ren_last_REG_6 <= io.readPorts[5'h6].ren & io.readPorts[5'h6].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h7].ren)
      in_addr_7 <= io.readPorts[5'h7].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_7 <= 1'h0;
    else
      int_ren_last_REG_7 <= io.readPorts[5'h7].ren & ~(io.readPorts[5'h7].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_7 <= 1'h0;
    else
      mem_ren_last_REG_7 <= io.readPorts[5'h7].ren & io.readPorts[5'h7].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h8].ren)
      in_addr_8 <= io.readPorts[5'h8].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_8 <= 1'h0;
    else
      int_ren_last_REG_8 <= io.readPorts[5'h8].ren & ~(io.readPorts[5'h8].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_8 <= 1'h0;
    else
      mem_ren_last_REG_8 <= io.readPorts[5'h8].ren & io.readPorts[5'h8].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h9].ren)
      in_addr_9 <= io.readPorts[5'h9].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_9 <= 1'h0;
    else
      int_ren_last_REG_9 <= io.readPorts[5'h9].ren & ~(io.readPorts[5'h9].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_9 <= 1'h0;
    else
      mem_ren_last_REG_9 <= io.readPorts[5'h9].ren & io.readPorts[5'h9].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'hA].ren)
      in_addr_10 <= io.readPorts[5'hA].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_10 <= 1'h0;
    else
      int_ren_last_REG_10 <= io.readPorts[5'hA].ren & ~(io.readPorts[5'hA].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_10 <= 1'h0;
    else
      mem_ren_last_REG_10 <= io.readPorts[5'hA].ren & io.readPorts[5'hA].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'hB].ren)
      in_addr_11 <= io.readPorts[5'hB].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_11 <= 1'h0;
    else
      int_ren_last_REG_11 <= io.readPorts[5'hB].ren & ~(io.readPorts[5'hB].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_11 <= 1'h0;
    else
      mem_ren_last_REG_11 <= io.readPorts[5'hB].ren & io.readPorts[5'hB].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'hC].ren)
      in_addr_12 <= io.readPorts[5'hC].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_12 <= 1'h0;
    else
      int_ren_last_REG_12 <= io.readPorts[5'hC].ren & ~(io.readPorts[5'hC].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_12 <= 1'h0;
    else
      mem_ren_last_REG_12 <= io.readPorts[5'hC].ren & io.readPorts[5'hC].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'hD].ren)
      in_addr_13 <= io.readPorts[5'hD].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_13 <= 1'h0;
    else
      int_ren_last_REG_13 <= io.readPorts[5'hD].ren & ~(io.readPorts[5'hD].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_13 <= 1'h0;
    else
      mem_ren_last_REG_13 <= io.readPorts[5'hD].ren & io.readPorts[5'hD].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'hE].ren)
      in_addr_14 <= io.readPorts[5'hE].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_14 <= 1'h0;
    else
      int_ren_last_REG_14 <= io.readPorts[5'hE].ren & ~(io.readPorts[5'hE].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_14 <= 1'h0;
    else
      mem_ren_last_REG_14 <= io.readPorts[5'hE].ren & io.readPorts[5'hE].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'hF].ren)
      in_addr_15 <= io.readPorts[5'hF].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_15 <= 1'h0;
    else
      int_ren_last_REG_15 <= io.readPorts[5'hF].ren & ~(io.readPorts[5'hF].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_15 <= 1'h0;
    else
      mem_ren_last_REG_15 <= io.readPorts[5'hF].ren & io.readPorts[5'hF].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h10].ren)
      in_addr_16 <= io.readPorts[5'h10].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_16 <= 1'h0;
    else
      int_ren_last_REG_16 <= io.readPorts[5'h10].ren & ~(io.readPorts[5'h10].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_16 <= 1'h0;
    else
      mem_ren_last_REG_16 <= io.readPorts[5'h10].ren & io.readPorts[5'h10].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h11].ren)
      in_addr_17 <= io.readPorts[5'h11].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_17 <= 1'h0;
    else
      int_ren_last_REG_17 <= io.readPorts[5'h11].ren & ~(io.readPorts[5'h11].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_17 <= 1'h0;
    else
      mem_ren_last_REG_17 <= io.readPorts[5'h11].ren & io.readPorts[5'h11].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h12].ren)
      in_addr_18 <= io.readPorts[5'h12].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_18 <= 1'h0;
    else
      int_ren_last_REG_18 <= io.readPorts[5'h12].ren & ~(io.readPorts[5'h12].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_18 <= 1'h0;
    else
      mem_ren_last_REG_18 <= io.readPorts[5'h12].ren & io.readPorts[5'h12].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h13].ren)
      in_addr_19 <= io.readPorts[5'h13].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_19 <= 1'h0;
    else
      int_ren_last_REG_19 <= io.readPorts[5'h13].ren & ~(io.readPorts[5'h13].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_19 <= 1'h0;
    else
      mem_ren_last_REG_19 <= io.readPorts[5'h13].ren & io.readPorts[5'h13].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h14].ren)
      in_addr_20 <= io.readPorts[5'h14].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_20 <= 1'h0;
    else
      int_ren_last_REG_20 <= io.readPorts[5'h14].ren & ~(io.readPorts[5'h14].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_20 <= 1'h0;
    else
      mem_ren_last_REG_20 <= io.readPorts[5'h14].ren & io.readPorts[5'h14].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h15].ren)
      in_addr_21 <= io.readPorts[5'h15].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_21 <= 1'h0;
    else
      int_ren_last_REG_21 <= io.readPorts[5'h15].ren & ~(io.readPorts[5'h15].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_21 <= 1'h0;
    else
      mem_ren_last_REG_21 <= io.readPorts[5'h15].ren & io.readPorts[5'h15].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h16].ren)
      in_addr_22 <= io.readPorts[5'h16].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_22 <= 1'h0;
    else
      int_ren_last_REG_22 <= io.readPorts[5'h16].ren & ~(io.readPorts[5'h16].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_22 <= 1'h0;
    else
      mem_ren_last_REG_22 <= io.readPorts[5'h16].ren & io.readPorts[5'h16].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h17].ren)
      in_addr_23 <= io.readPorts[5'h17].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_23 <= 1'h0;
    else
      int_ren_last_REG_23 <= io.readPorts[5'h17].ren & ~(io.readPorts[5'h17].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_23 <= 1'h0;
    else
      mem_ren_last_REG_23 <= io.readPorts[5'h17].ren & io.readPorts[5'h17].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io.readPorts[5'h18].ren)
      in_addr_24 <= io.readPorts[5'h18].addr;
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      int_ren_last_REG_24 <= 1'h0;
    else
      int_ren_last_REG_24 <= io.readPorts[5'h18].ren & ~(io.readPorts[5'h18].addr[5]);
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      mem_ren_last_REG_24 <= 1'h0;
    else
      mem_ren_last_REG_24 <= io.readPorts[5'h18].ren & io.readPorts[5'h18].addr[5];
  end // always @(posedge, posedge)
  always @(posedge clock)
    delayToWakeupQueueRCIdx_REG <= io.toWakeupQueueRCIdx;
  always @(posedge clock)
    delayToWakeupQueueRCIdx_REG_1 <= delayToWakeupQueueRCIdx_REG;
  always @(posedge clock)
    delayToWakeupQueueRCIdx <= delayToWakeupQueueRCIdx_REG_1;
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        int_ren_last_REG = 1'h0;
        mem_ren_last_REG = 1'h0;
        int_ren_last_REG_1 = 1'h0;
        mem_ren_last_REG_1 = 1'h0;
        int_ren_last_REG_2 = 1'h0;
        mem_ren_last_REG_2 = 1'h0;
        int_ren_last_REG_3 = 1'h0;
        mem_ren_last_REG_3 = 1'h0;
        int_ren_last_REG_4 = 1'h0;
        mem_ren_last_REG_4 = 1'h0;
        int_ren_last_REG_5 = 1'h0;
        mem_ren_last_REG_5 = 1'h0;
        int_ren_last_REG_6 = 1'h0;
        mem_ren_last_REG_6 = 1'h0;
        int_ren_last_REG_7 = 1'h0;
        mem_ren_last_REG_7 = 1'h0;
        int_ren_last_REG_8 = 1'h0;
        mem_ren_last_REG_8 = 1'h0;
        int_ren_last_REG_9 = 1'h0;
        mem_ren_last_REG_9 = 1'h0;
        int_ren_last_REG_10 = 1'h0;
        mem_ren_last_REG_10 = 1'h0;
        int_ren_last_REG_11 = 1'h0;
        mem_ren_last_REG_11 = 1'h0;
        int_ren_last_REG_12 = 1'h0;
        mem_ren_last_REG_12 = 1'h0;
        int_ren_last_REG_13 = 1'h0;
        mem_ren_last_REG_13 = 1'h0;
        int_ren_last_REG_14 = 1'h0;
        mem_ren_last_REG_14 = 1'h0;
        int_ren_last_REG_15 = 1'h0;
        mem_ren_last_REG_15 = 1'h0;
        int_ren_last_REG_16 = 1'h0;
        mem_ren_last_REG_16 = 1'h0;
        int_ren_last_REG_17 = 1'h0;
        mem_ren_last_REG_17 = 1'h0;
        int_ren_last_REG_18 = 1'h0;
        mem_ren_last_REG_18 = 1'h0;
        int_ren_last_REG_19 = 1'h0;
        mem_ren_last_REG_19 = 1'h0;
        int_ren_last_REG_20 = 1'h0;
        mem_ren_last_REG_20 = 1'h0;
        int_ren_last_REG_21 = 1'h0;
        mem_ren_last_REG_21 = 1'h0;
        int_ren_last_REG_22 = 1'h0;
        mem_ren_last_REG_22 = 1'h0;
        int_ren_last_REG_23 = 1'h0;
        mem_ren_last_REG_23 = 1'h0;
        int_ren_last_REG_24 = 1'h0;
        mem_ren_last_REG_24 = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  RegCacheDataModule IntRegCache (
    .clock                (clock),
    .reset                (reset),
    .io_readPorts_0_ren   (int_ren),
    .io_readPorts_0_addr  (in_addr[4:0]),
    .io_readPorts_0_data  (_IntRegCache_io_readPorts_0_data),
    .io_readPorts_1_ren   (int_ren_1),
    .io_readPorts_1_addr  (in_addr_1[4:0]),
    .io_readPorts_1_data  (_IntRegCache_io_readPorts_1_data),
    .io_readPorts_2_ren   (int_ren_2),
    .io_readPorts_2_addr  (in_addr_2[4:0]),
    .io_readPorts_2_data  (_IntRegCache_io_readPorts_2_data),
    .io_readPorts_3_ren   (int_ren_3),
    .io_readPorts_3_addr  (in_addr_3[4:0]),
    .io_readPorts_3_data  (_IntRegCache_io_readPorts_3_data),
    .io_readPorts_4_ren   (int_ren_4),
    .io_readPorts_4_addr  (in_addr_4[4:0]),
    .io_readPorts_4_data  (_IntRegCache_io_readPorts_4_data),
    .io_readPorts_5_ren   (int_ren_5),
    .io_readPorts_5_addr  (in_addr_5[4:0]),
    .io_readPorts_5_data  (_IntRegCache_io_readPorts_5_data),
    .io_readPorts_6_ren   (int_ren_6),
    .io_readPorts_6_addr  (in_addr_6[4:0]),
    .io_readPorts_6_data  (_IntRegCache_io_readPorts_6_data),
    .io_readPorts_7_ren   (int_ren_7),
    .io_readPorts_7_addr  (in_addr_7[4:0]),
    .io_readPorts_7_data  (_IntRegCache_io_readPorts_7_data),
    .io_readPorts_8_ren   (int_ren_8),
    .io_readPorts_8_addr  (in_addr_8[4:0]),
    .io_readPorts_8_data  (_IntRegCache_io_readPorts_8_data),
    .io_readPorts_9_ren   (int_ren_9),
    .io_readPorts_9_addr  (in_addr_9[4:0]),
    .io_readPorts_9_data  (_IntRegCache_io_readPorts_9_data),
    .io_readPorts_10_ren  (int_ren_10),
    .io_readPorts_10_addr (in_addr_10[4:0]),
    .io_readPorts_10_data (_IntRegCache_io_readPorts_10_data),
    .io_readPorts_11_ren  (int_ren_11),
    .io_readPorts_11_addr (in_addr_11[4:0]),
    .io_readPorts_11_data (_IntRegCache_io_readPorts_11_data),
    .io_readPorts_12_ren  (int_ren_12),
    .io_readPorts_12_addr (in_addr_12[4:0]),
    .io_readPorts_12_data (_IntRegCache_io_readPorts_12_data),
    .io_readPorts_13_ren  (int_ren_13),
    .io_readPorts_13_addr (in_addr_13[4:0]),
    .io_readPorts_13_data (_IntRegCache_io_readPorts_13_data),
    .io_readPorts_14_ren  (int_ren_14),
    .io_readPorts_14_addr (in_addr_14[4:0]),
    .io_readPorts_14_data (_IntRegCache_io_readPorts_14_data),
    .io_readPorts_15_ren  (int_ren_15),
    .io_readPorts_15_addr (in_addr_15[4:0]),
    .io_readPorts_15_data (_IntRegCache_io_readPorts_15_data),
    .io_readPorts_16_ren  (int_ren_16),
    .io_readPorts_16_addr (in_addr_16[4:0]),
    .io_readPorts_16_data (_IntRegCache_io_readPorts_16_data),
    .io_readPorts_17_ren  (int_ren_17),
    .io_readPorts_17_addr (in_addr_17[4:0]),
    .io_readPorts_17_data (_IntRegCache_io_readPorts_17_data),
    .io_readPorts_18_ren  (int_ren_18),
    .io_readPorts_18_addr (in_addr_18[4:0]),
    .io_readPorts_18_data (_IntRegCache_io_readPorts_18_data),
    .io_readPorts_19_ren  (int_ren_19),
    .io_readPorts_19_addr (in_addr_19[4:0]),
    .io_readPorts_19_data (_IntRegCache_io_readPorts_19_data),
    .io_readPorts_20_ren  (int_ren_20),
    .io_readPorts_20_addr (in_addr_20[4:0]),
    .io_readPorts_20_data (_IntRegCache_io_readPorts_20_data),
    .io_readPorts_21_ren  (int_ren_21),
    .io_readPorts_21_addr (in_addr_21[4:0]),
    .io_readPorts_21_data (_IntRegCache_io_readPorts_21_data),
    .io_readPorts_22_ren  (int_ren_22),
    .io_readPorts_22_addr (in_addr_22[4:0]),
    .io_readPorts_22_data (_IntRegCache_io_readPorts_22_data),
    .io_readPorts_23_ren  (int_ren_23),
    .io_readPorts_23_addr (in_addr_23[4:0]),
    .io_readPorts_23_data (_IntRegCache_io_readPorts_23_data),
    .io_readPorts_24_ren  (int_ren_24),
    .io_readPorts_24_addr (in_addr_24[4:0]),
    .io_readPorts_24_data (_IntRegCache_io_readPorts_24_data),
    .io_writePorts_0_wen  (writePorts[4'h0].wen),
    .io_writePorts_0_addr (writePorts[4'h0].addr[4:0]),
    .io_writePorts_0_data (writePorts[4'h0].data),
    .io_writePorts_1_wen  (writePorts[4'h1].wen),
    .io_writePorts_1_addr (writePorts[4'h1].addr[4:0]),
    .io_writePorts_1_data (writePorts[4'h1].data),
    .io_writePorts_2_wen  (writePorts[4'h2].wen),
    .io_writePorts_2_addr (writePorts[4'h2].addr[4:0]),
    .io_writePorts_2_data (writePorts[4'h2].data),
    .io_writePorts_3_wen  (writePorts[4'h3].wen),
    .io_writePorts_3_addr (writePorts[4'h3].addr[4:0]),
    .io_writePorts_3_data (writePorts[4'h3].data),
    .io_writePorts_4_wen  (writePorts[4'h4].wen),
    .io_writePorts_4_addr (writePorts[4'h4].addr[4:0]),
    .io_writePorts_4_data (writePorts[4'h4].data),
    .io_writePorts_5_wen  (writePorts[4'h5].wen),
    .io_writePorts_5_addr (writePorts[4'h5].addr[4:0]),
    .io_writePorts_5_data (writePorts[4'h5].data),
    .io_validInfo         (_IntRegCache_io_validInfo)
  );
  RegCacheDataModule_1 MemRegCache (
    .clock                (clock),
    .reset                (reset),
    .io_readPorts_0_ren   (mem_ren),
    .io_readPorts_0_addr  (in_addr[4:0]),
    .io_readPorts_0_data  (_MemRegCache_io_readPorts_0_data),
    .io_readPorts_1_ren   (mem_ren_1),
    .io_readPorts_1_addr  (in_addr_1[4:0]),
    .io_readPorts_1_data  (_MemRegCache_io_readPorts_1_data),
    .io_readPorts_2_ren   (mem_ren_2),
    .io_readPorts_2_addr  (in_addr_2[4:0]),
    .io_readPorts_2_data  (_MemRegCache_io_readPorts_2_data),
    .io_readPorts_3_ren   (mem_ren_3),
    .io_readPorts_3_addr  (in_addr_3[4:0]),
    .io_readPorts_3_data  (_MemRegCache_io_readPorts_3_data),
    .io_readPorts_4_ren   (mem_ren_4),
    .io_readPorts_4_addr  (in_addr_4[4:0]),
    .io_readPorts_4_data  (_MemRegCache_io_readPorts_4_data),
    .io_readPorts_5_ren   (mem_ren_5),
    .io_readPorts_5_addr  (in_addr_5[4:0]),
    .io_readPorts_5_data  (_MemRegCache_io_readPorts_5_data),
    .io_readPorts_6_ren   (mem_ren_6),
    .io_readPorts_6_addr  (in_addr_6[4:0]),
    .io_readPorts_6_data  (_MemRegCache_io_readPorts_6_data),
    .io_readPorts_7_ren   (mem_ren_7),
    .io_readPorts_7_addr  (in_addr_7[4:0]),
    .io_readPorts_7_data  (_MemRegCache_io_readPorts_7_data),
    .io_readPorts_8_ren   (mem_ren_8),
    .io_readPorts_8_addr  (in_addr_8[4:0]),
    .io_readPorts_8_data  (_MemRegCache_io_readPorts_8_data),
    .io_readPorts_9_ren   (mem_ren_9),
    .io_readPorts_9_addr  (in_addr_9[4:0]),
    .io_readPorts_9_data  (_MemRegCache_io_readPorts_9_data),
    .io_readPorts_10_ren  (mem_ren_10),
    .io_readPorts_10_addr (in_addr_10[4:0]),
    .io_readPorts_10_data (_MemRegCache_io_readPorts_10_data),
    .io_readPorts_11_ren  (mem_ren_11),
    .io_readPorts_11_addr (in_addr_11[4:0]),
    .io_readPorts_11_data (_MemRegCache_io_readPorts_11_data),
    .io_readPorts_12_ren  (mem_ren_12),
    .io_readPorts_12_addr (in_addr_12[4:0]),
    .io_readPorts_12_data (_MemRegCache_io_readPorts_12_data),
    .io_readPorts_13_ren  (mem_ren_13),
    .io_readPorts_13_addr (in_addr_13[4:0]),
    .io_readPorts_13_data (_MemRegCache_io_readPorts_13_data),
    .io_readPorts_14_ren  (mem_ren_14),
    .io_readPorts_14_addr (in_addr_14[4:0]),
    .io_readPorts_14_data (_MemRegCache_io_readPorts_14_data),
    .io_readPorts_15_ren  (mem_ren_15),
    .io_readPorts_15_addr (in_addr_15[4:0]),
    .io_readPorts_15_data (_MemRegCache_io_readPorts_15_data),
    .io_readPorts_16_ren  (mem_ren_16),
    .io_readPorts_16_addr (in_addr_16[4:0]),
    .io_readPorts_16_data (_MemRegCache_io_readPorts_16_data),
    .io_readPorts_17_ren  (mem_ren_17),
    .io_readPorts_17_addr (in_addr_17[4:0]),
    .io_readPorts_17_data (_MemRegCache_io_readPorts_17_data),
    .io_readPorts_18_ren  (mem_ren_18),
    .io_readPorts_18_addr (in_addr_18[4:0]),
    .io_readPorts_18_data (_MemRegCache_io_readPorts_18_data),
    .io_readPorts_19_ren  (mem_ren_19),
    .io_readPorts_19_addr (in_addr_19[4:0]),
    .io_readPorts_19_data (_MemRegCache_io_readPorts_19_data),
    .io_readPorts_20_ren  (mem_ren_20),
    .io_readPorts_20_addr (in_addr_20[4:0]),
    .io_readPorts_20_data (_MemRegCache_io_readPorts_20_data),
    .io_readPorts_21_ren  (mem_ren_21),
    .io_readPorts_21_addr (in_addr_21[4:0]),
    .io_readPorts_21_data (_MemRegCache_io_readPorts_21_data),
    .io_readPorts_22_ren  (mem_ren_22),
    .io_readPorts_22_addr (in_addr_22[4:0]),
    .io_readPorts_22_data (_MemRegCache_io_readPorts_22_data),
    .io_readPorts_23_ren  (mem_ren_23),
    .io_readPorts_23_addr (in_addr_23[4:0]),
    .io_readPorts_23_data (_MemRegCache_io_readPorts_23_data),
    .io_readPorts_24_ren  (mem_ren_24),
    .io_readPorts_24_addr (in_addr_24[4:0]),
    .io_readPorts_24_data (_MemRegCache_io_readPorts_24_data),
    .io_writePorts_0_wen  (writePorts[4'h6].wen),
    .io_writePorts_0_addr (writePorts[4'h6].addr[4:0]),
    .io_writePorts_0_data (writePorts[4'h6].data),
    .io_writePorts_1_wen  (writePorts[4'h7].wen),
    .io_writePorts_1_addr (writePorts[4'h7].addr[4:0]),
    .io_writePorts_1_data (writePorts[4'h7].data),
    .io_writePorts_2_wen  (writePorts[4'h8].wen),
    .io_writePorts_2_addr (writePorts[4'h8].addr[4:0]),
    .io_writePorts_2_data (writePorts[4'h8].data),
    .io_validInfo         (_MemRegCache_io_validInfo)
  );
  RegCacheAgeTimer IntRegCacheAgeTimer (
    .clock                (clock),
    .reset                (reset),
    .io_readPorts_0_ren   (int_ren),
    .io_readPorts_0_addr  (in_addr[4:0]),
    .io_readPorts_1_ren   (int_ren_1),
    .io_readPorts_1_addr  (in_addr_1[4:0]),
    .io_readPorts_2_ren   (int_ren_2),
    .io_readPorts_2_addr  (in_addr_2[4:0]),
    .io_readPorts_3_ren   (int_ren_3),
    .io_readPorts_3_addr  (in_addr_3[4:0]),
    .io_readPorts_4_ren   (int_ren_4),
    .io_readPorts_4_addr  (in_addr_4[4:0]),
    .io_readPorts_5_ren   (int_ren_5),
    .io_readPorts_5_addr  (in_addr_5[4:0]),
    .io_readPorts_6_ren   (int_ren_6),
    .io_readPorts_6_addr  (in_addr_6[4:0]),
    .io_readPorts_7_ren   (int_ren_7),
    .io_readPorts_7_addr  (in_addr_7[4:0]),
    .io_readPorts_8_ren   (int_ren_8),
    .io_readPorts_8_addr  (in_addr_8[4:0]),
    .io_readPorts_9_ren   (int_ren_9),
    .io_readPorts_9_addr  (in_addr_9[4:0]),
    .io_readPorts_10_ren  (int_ren_10),
    .io_readPorts_10_addr (in_addr_10[4:0]),
    .io_readPorts_11_ren  (int_ren_11),
    .io_readPorts_11_addr (in_addr_11[4:0]),
    .io_readPorts_12_ren  (int_ren_12),
    .io_readPorts_12_addr (in_addr_12[4:0]),
    .io_readPorts_13_ren  (int_ren_13),
    .io_readPorts_13_addr (in_addr_13[4:0]),
    .io_readPorts_14_ren  (int_ren_14),
    .io_readPorts_14_addr (in_addr_14[4:0]),
    .io_readPorts_15_ren  (int_ren_15),
    .io_readPorts_15_addr (in_addr_15[4:0]),
    .io_readPorts_16_ren  (int_ren_16),
    .io_readPorts_16_addr (in_addr_16[4:0]),
    .io_readPorts_17_ren  (int_ren_17),
    .io_readPorts_17_addr (in_addr_17[4:0]),
    .io_readPorts_18_ren  (int_ren_18),
    .io_readPorts_18_addr (in_addr_18[4:0]),
    .io_readPorts_19_ren  (int_ren_19),
    .io_readPorts_19_addr (in_addr_19[4:0]),
    .io_readPorts_20_ren  (int_ren_20),
    .io_readPorts_20_addr (in_addr_20[4:0]),
    .io_readPorts_21_ren  (int_ren_21),
    .io_readPorts_21_addr (in_addr_21[4:0]),
    .io_readPorts_22_ren  (int_ren_22),
    .io_readPorts_22_addr (in_addr_22[4:0]),
    .io_readPorts_23_ren  (int_ren_23),
    .io_readPorts_23_addr (in_addr_23[4:0]),
    .io_readPorts_24_ren  (int_ren_24),
    .io_readPorts_24_addr (in_addr_24[4:0]),
    .io_writePorts_0_wen  (writePorts[4'h0].wen),
    .io_writePorts_0_addr (writePorts[4'h0].addr[4:0]),
    .io_writePorts_1_wen  (writePorts[4'h1].wen),
    .io_writePorts_1_addr (writePorts[4'h1].addr[4:0]),
    .io_writePorts_2_wen  (writePorts[4'h2].wen),
    .io_writePorts_2_addr (writePorts[4'h2].addr[4:0]),
    .io_writePorts_3_wen  (writePorts[4'h3].wen),
    .io_writePorts_3_addr (writePorts[4'h3].addr[4:0]),
    .io_writePorts_4_wen  (writePorts[4'h4].wen),
    .io_writePorts_4_addr (writePorts[4'h4].addr[4:0]),
    .io_writePorts_5_wen  (writePorts[4'h5].wen),
    .io_writePorts_5_addr (writePorts[4'h5].addr[4:0]),
    .io_validInfo         (_IntRegCache_io_validInfo),
    .io_ageInfo           (_IntRegCacheAgeTimer_io_ageInfo)
  );
  RegCacheAgeTimer_1 MemRegCacheAgeTimer (
    .clock                (clock),
    .reset                (reset),
    .io_readPorts_0_ren   (mem_ren),
    .io_readPorts_0_addr  (in_addr[4:0]),
    .io_readPorts_1_ren   (mem_ren_1),
    .io_readPorts_1_addr  (in_addr_1[4:0]),
    .io_readPorts_2_ren   (mem_ren_2),
    .io_readPorts_2_addr  (in_addr_2[4:0]),
    .io_readPorts_3_ren   (mem_ren_3),
    .io_readPorts_3_addr  (in_addr_3[4:0]),
    .io_readPorts_4_ren   (mem_ren_4),
    .io_readPorts_4_addr  (in_addr_4[4:0]),
    .io_readPorts_5_ren   (mem_ren_5),
    .io_readPorts_5_addr  (in_addr_5[4:0]),
    .io_readPorts_6_ren   (mem_ren_6),
    .io_readPorts_6_addr  (in_addr_6[4:0]),
    .io_readPorts_7_ren   (mem_ren_7),
    .io_readPorts_7_addr  (in_addr_7[4:0]),
    .io_readPorts_8_ren   (mem_ren_8),
    .io_readPorts_8_addr  (in_addr_8[4:0]),
    .io_readPorts_9_ren   (mem_ren_9),
    .io_readPorts_9_addr  (in_addr_9[4:0]),
    .io_readPorts_10_ren  (mem_ren_10),
    .io_readPorts_10_addr (in_addr_10[4:0]),
    .io_readPorts_11_ren  (mem_ren_11),
    .io_readPorts_11_addr (in_addr_11[4:0]),
    .io_readPorts_12_ren  (mem_ren_12),
    .io_readPorts_12_addr (in_addr_12[4:0]),
    .io_readPorts_13_ren  (mem_ren_13),
    .io_readPorts_13_addr (in_addr_13[4:0]),
    .io_readPorts_14_ren  (mem_ren_14),
    .io_readPorts_14_addr (in_addr_14[4:0]),
    .io_readPorts_15_ren  (mem_ren_15),
    .io_readPorts_15_addr (in_addr_15[4:0]),
    .io_readPorts_16_ren  (mem_ren_16),
    .io_readPorts_16_addr (in_addr_16[4:0]),
    .io_readPorts_17_ren  (mem_ren_17),
    .io_readPorts_17_addr (in_addr_17[4:0]),
    .io_readPorts_18_ren  (mem_ren_18),
    .io_readPorts_18_addr (in_addr_18[4:0]),
    .io_readPorts_19_ren  (mem_ren_19),
    .io_readPorts_19_addr (in_addr_19[4:0]),
    .io_readPorts_20_ren  (mem_ren_20),
    .io_readPorts_20_addr (in_addr_20[4:0]),
    .io_readPorts_21_ren  (mem_ren_21),
    .io_readPorts_21_addr (in_addr_21[4:0]),
    .io_readPorts_22_ren  (mem_ren_22),
    .io_readPorts_22_addr (in_addr_22[4:0]),
    .io_readPorts_23_ren  (mem_ren_23),
    .io_readPorts_23_addr (in_addr_23[4:0]),
    .io_readPorts_24_ren  (mem_ren_24),
    .io_readPorts_24_addr (in_addr_24[4:0]),
    .io_writePorts_0_wen  (writePorts[4'h6].wen),
    .io_writePorts_0_addr (writePorts[4'h6].addr[4:0]),
    .io_writePorts_1_wen  (writePorts[4'h7].wen),
    .io_writePorts_1_addr (writePorts[4'h7].addr[4:0]),
    .io_writePorts_2_wen  (writePorts[4'h8].wen),
    .io_writePorts_2_addr (writePorts[4'h8].addr[4:0]),
    .io_validInfo         (_MemRegCache_io_validInfo),
    .io_ageInfo           (_MemRegCacheAgeTimer_io_ageInfo)
  );
  RegCacheAgeDetector age (
    .clock      (clock),
    .reset      (reset),
    .io_ageInfo (_IntRegCacheAgeTimer_io_ageInfo),
    .io_out     (IntRegCacheRepRCIdx)
  );
  RegCacheAgeDetector_1 age_1 (
    .clock      (clock),
    .reset      (reset),
    .io_ageInfo (_MemRegCacheAgeTimer_io_ageInfo),
    .io_out     (_age_1_io_out)
  );
  assign io_readPorts_0_data = io.readPorts[5'h0].data;
  assign io_readPorts_1_data = io.readPorts[5'h1].data;
  assign io_readPorts_2_data = io.readPorts[5'h2].data;
  assign io_readPorts_3_data = io.readPorts[5'h3].data;
  assign io_readPorts_4_data = io.readPorts[5'h4].data;
  assign io_readPorts_5_data = io.readPorts[5'h5].data;
  assign io_readPorts_6_data = io.readPorts[5'h6].data;
  assign io_readPorts_7_data = io.readPorts[5'h7].data;
  assign io_readPorts_8_data = io.readPorts[5'h8].data;
  assign io_readPorts_9_data = io.readPorts[5'h9].data;
  assign io_readPorts_10_data = io.readPorts[5'hA].data;
  assign io_readPorts_11_data = io.readPorts[5'hB].data;
  assign io_readPorts_12_data = io.readPorts[5'hC].data;
  assign io_readPorts_13_data = io.readPorts[5'hD].data;
  assign io_readPorts_14_data = io.readPorts[5'hE].data;
  assign io_readPorts_15_data = io.readPorts[5'hF].data;
  assign io_readPorts_16_data = io.readPorts[5'h10].data;
  assign io_readPorts_17_data = io.readPorts[5'h11].data;
  assign io_readPorts_18_data = io.readPorts[5'h12].data;
  assign io_readPorts_19_data = io.readPorts[5'h13].data;
  assign io_readPorts_20_data = io.readPorts[5'h14].data;
  assign io_readPorts_21_data = io.readPorts[5'h15].data;
  assign io_readPorts_22_data = io.readPorts[5'h16].data;
  assign io_readPorts_23_data = io.readPorts[5'h17].data;
  assign io_readPorts_24_data = io.readPorts[5'h18].data;
  assign io_toWakeupQueueRCIdx = io.toWakeupQueueRCIdx;
endmodule

