// Generated by CIRCT firtool-1.150.2
module ScountinhibitModule(
  input                                                                                              clock,
                                                                                                     reset,
  input  struct packed {logic wen; logic [63:0] wdata; }                                             w,
  output [63:0]                                                                                      rdata,
  output struct packed {logic CY; logic IR; logic [28:0] HPM3; }                                     regOut,
  input  struct packed {logic CY; logic TM; logic IR; logic [28:0] HPM; }                            mcounteren,
  input  struct packed {logic CY; logic IR; logic [28:0] HPM3; }                                     fromMcntinhibit,
  output struct packed {logic valid; struct packed {logic CY; logic IR; logic [28:0] HPM3; } bits; } toMcntinhibit
);

  wire        _regOut_CY_WIRE_1;
  wire [31:0] _GEN;
  wire struct packed {logic CY; logic IR; logic [28:0] HPM3; } reg_init =
    '{CY: 1'h0, IR: 1'h0, HPM3: 29'h0};
  struct packed {logic CY; logic IR; logic [28:0] HPM3; } reg_0;
  wire struct packed {logic CY; logic IR; logic [28:0] HPM3; } wdata;
  assign wdata = '{CY: (w.wdata[0]), IR: (w.wdata[2]), HPM3: (w.wdata[31:3])};
  wire [31:0] delegMask = {mcounteren.HPM, mcounteren.IR, 1'h0, mcounteren.CY};
  wire [31:0] _GEN_0 =
    {fromMcntinhibit.HPM3, fromMcntinhibit.IR, 1'h0, fromMcntinhibit.CY};
  wire [31:0] _GEN_1 =
    {wdata.HPM3, wdata.IR, 1'h0, wdata.CY} & delegMask | _GEN_0 & ~delegMask;
  assign _GEN = _GEN_0 & delegMask;
  assign _regOut_CY_WIRE_1 = _GEN[0];
  wire struct packed {logic CY; logic IR; logic [28:0] HPM3; } _GEN_2 =
    '{CY: (_GEN_1[0]), IR: (_GEN_1[2]), HPM3: (_GEN_1[31:3])};
  always @(posedge clock or posedge reset) begin
    if (reset)
      reg_0 <= reg_init;
    else begin
      automatic logic        _GEN_3;
      automatic logic        _GEN_4;
      automatic logic [28:0] _GEN_5;
      _GEN_3 = w.wen ? wdata.CY : reg_0.CY;
      _GEN_4 = w.wen ? wdata.IR : reg_0.IR;
      _GEN_5 = w.wen ? wdata.HPM3 : reg_0.HPM3;
      reg_0 <= '{CY: _GEN_3, IR: _GEN_4, HPM3: _GEN_5};
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset)
        reg_0 = reg_init;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign rdata = {32'h0, _GEN[31:2], 1'h0, _regOut_CY_WIRE_1};
  assign regOut = '{CY: _regOut_CY_WIRE_1, IR: (_GEN[2]), HPM3: (_GEN[31:3])};
  assign toMcntinhibit = '{valid: w.wen, bits: _GEN_2};
endmodule

