// Generated by CIRCT firtool-1.150.2
module SenvcfgModule(
  input                                                                                                                                                                            clock,
                                                                                                                                                                                   reset,
  input  struct packed {logic wen; logic [63:0] wdata; }                                                                                                                           w,
  output [63:0]                                                                                                                                                                    rdata,
  output struct packed {logic STCE; logic PBMTE; logic ADUE; logic CDE; logic DTE; logic [1:0] PMM; logic CBZE; logic CBCFE; logic [1:0] CBIE; logic SSE; logic LPE; logic FIOM; } regOut
);

  struct packed {logic STCE; logic PBMTE; logic ADUE; logic CDE; logic DTE; logic [1:0] PMM; logic CBZE; logic CBCFE; logic [1:0] CBIE; logic SSE; logic LPE; logic FIOM; }
    reg_0;
  wire
    struct packed {logic STCE; logic PBMTE; logic ADUE; logic CDE; logic DTE; logic [1:0] PMM; logic CBZE; logic CBCFE; logic [1:0] CBIE; logic SSE; logic LPE; logic FIOM; }
    reg_init =
    '{STCE: 1'h0,
      PBMTE: 1'h0,
      ADUE: 1'h0,
      CDE: 1'h0,
      DTE: 1'h0,
      PMM: 2'h0,
      CBZE: 1'h1,
      CBCFE: 1'h1,
      CBIE: 2'h3,
      SSE: 1'h0,
      LPE: 1'h0,
      FIOM: 1'h0};
  wire
    struct packed {logic STCE; logic PBMTE; logic ADUE; logic CDE; logic DTE; logic [1:0] PMM; logic CBZE; logic CBCFE; logic [1:0] CBIE; logic SSE; logic LPE; logic FIOM; }
    wdata =
    '{STCE: (w.wdata[63]),
      PBMTE: (w.wdata[62]),
      ADUE: (w.wdata[61]),
      CDE: (w.wdata[60]),
      DTE: (w.wdata[59]),
      PMM: (w.wdata[33:32]),
      CBZE: (w.wdata[7]),
      CBCFE: (w.wdata[6]),
      CBIE: (w.wdata[5:4]),
      SSE: (w.wdata[3]),
      LPE: (w.wdata[2]),
      FIOM: (w.wdata[0])};
  always @(posedge clock or posedge reset) begin
    if (reset)
      reg_0 <= reg_init;
    else begin
      automatic logic [1:0] _GEN;
      automatic logic       _GEN_0;
      automatic logic       _GEN_1;
      automatic logic [1:0] _GEN_2;
      _GEN =
        w.wen & (wdata.PMM == 2'h0 | wdata.PMM == 2'h2 | (&wdata.PMM))
          ? wdata.PMM
          : reg_0.PMM;
      _GEN_0 = w.wen ? wdata.CBZE : reg_0.CBZE;
      _GEN_1 = w.wen ? wdata.CBCFE : reg_0.CBCFE;
      _GEN_2 =
        w.wen & (wdata.CBIE == 2'h0 | wdata.CBIE == 2'h1 | (&wdata.CBIE))
          ? wdata.CBIE
          : reg_0.CBIE;
      reg_0 <=
        '{STCE: reg_0.STCE,
          PBMTE: reg_0.PBMTE,
          ADUE: reg_0.ADUE,
          CDE: reg_0.CDE,
          DTE: reg_0.DTE,
          PMM: _GEN,
          CBZE: _GEN_0,
          CBCFE: _GEN_1,
          CBIE: _GEN_2,
          SSE: reg_0.SSE,
          LPE: reg_0.LPE,
          FIOM: reg_0.FIOM};
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset)
        reg_0 = reg_init;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign rdata =
    {reg_0.STCE,
     reg_0.PBMTE,
     reg_0.ADUE,
     reg_0.CDE,
     reg_0.DTE,
     25'h0,
     reg_0.PMM,
     24'h0,
     reg_0.CBZE,
     reg_0.CBCFE,
     reg_0.CBIE,
     reg_0.SSE,
     reg_0.LPE,
     1'h0,
     reg_0.FIOM};
  assign regOut = reg_0;
endmodule

