// Generated by CIRCT firtool-1.150.2
module SnapshotGenerator_14(
  input                                                                                                        clock,
                                                                                                               reset,
                                                                                                               io_enq,
  input  struct packed {struct packed {logic flag; logic [8:0] value; }[7:0] robIdx; logic [7:0] isCFI; }      io_enqData,
  input                                                                                                        io_deq,
                                                                                                               io_redirect,
  input  [3:0]                                                                                                 io_flushVec,
  output struct packed {struct packed {logic flag; logic [8:0] value; }[7:0] robIdx; logic [7:0] isCFI; }[3:0] io_snapshots,
  output struct packed {logic flag; logic [1:0] value; }                                                       io_enqPtr,
                                                                                                               io_deqPtr,
  output [3:0]                                                                                                 io_valids
);

  wire
    struct packed {logic enq; struct packed {struct packed {logic flag; logic [8:0] value; }[7:0] robIdx; logic [7:0] isCFI; } enqData; logic deq; logic redirect; logic [3:0] flushVec; struct packed {struct packed {logic flag; logic [8:0] value; }[7:0] robIdx; logic [7:0] isCFI; }[3:0] snapshots; struct packed {logic flag; logic [1:0] value; } enqPtr; struct packed {logic flag; logic [1:0] value; } deqPtr; logic [3:0] valids; }
    io;
  struct packed {struct packed {logic flag; logic [8:0] value; }[7:0] robIdx; logic [7:0] isCFI; }[3:0]
    snapshots;
  struct packed {logic flag; logic [1:0] value; } snptEnqPtr;
  struct packed {logic flag; logic [1:0] value; } snptDeqPtr;
  wire struct packed {logic flag; logic [1:0] value; } newEnqPtrCandidate_0 = snptDeqPtr;
  reg  [3:0] snptValids;
  wire       _GEN =
    ~io.redirect
    & ~(snptEnqPtr.flag != snptDeqPtr.flag & snptEnqPtr.value == snptDeqPtr.value)
    & io.enq;
  wire       _GEN_0 = _GEN & snptEnqPtr.value == 2'h0;
  wire       _GEN_1 = _GEN & snptEnqPtr.value == 2'h1;
  wire       _GEN_2 = _GEN & snptEnqPtr.value == 2'h2;
  wire       _GEN_3 = _GEN & (&snptEnqPtr.value);
  wire [2:0] _snptEnqPtr_new_ptr_T_1 = {snptEnqPtr.flag, snptEnqPtr.value} + 3'h1;
  wire       _GEN_4 = ~io.redirect & io.deq;
  wire [2:0] _GEN_5 = {snptDeqPtr.flag, snptDeqPtr.value};
  wire [2:0] _snptDeqPtr_new_ptr_T_1 = _GEN_5 + 3'h1;
  wire struct packed {logic flag; logic [1:0] value; } newEnqPtrCandidate_1;
  wire [2:0] _newEnqPtrCandidate_new_ptr_T_7 = _GEN_5 + 3'h1;
  wire struct packed {logic flag; logic [1:0] value; } newEnqPtrCandidate_2;
  wire [2:0] _newEnqPtrCandidate_new_ptr_T_13 = _GEN_5 + 3'h2;
  wire struct packed {logic flag; logic [1:0] value; } newEnqPtrCandidate_3;
  wire [2:0] _newEnqPtrCandidate_new_ptr_T_19 = _GEN_5 + 3'h3;
  wire       _GEN_6 = snptValids[newEnqPtrCandidate_1.value];
  wire       _GEN_7 = snptValids[newEnqPtrCandidate_2.value];
  wire       _GEN_8 = snptValids[newEnqPtrCandidate_3.value];
  wire [3:0] newEnqPtrQualified =
    {{_GEN_8 & (~_GEN_8 | io.flushVec[newEnqPtrCandidate_3.value])},
     {_GEN_7 & (~_GEN_7 | io.flushVec[newEnqPtrCandidate_2.value])},
     {_GEN_6 & (~_GEN_6 | io.flushVec[newEnqPtrCandidate_1.value])},
     {~snptValids[newEnqPtrCandidate_0.value] | io.flushVec[newEnqPtrCandidate_0.value]}};
  wire struct packed {logic flag; logic [1:0] value; } snptEnqPtr_new_ptr =
    '{flag: (_snptEnqPtr_new_ptr_T_1[2]), value: (_snptEnqPtr_new_ptr_T_1[1:0])};
  wire struct packed {logic flag; logic [1:0] value; } snptDeqPtr_new_ptr =
    '{flag: (_snptDeqPtr_new_ptr_T_1[2]), value: (_snptDeqPtr_new_ptr_T_1[1:0])};
  assign newEnqPtrCandidate_1 =
    '{flag: (_newEnqPtrCandidate_new_ptr_T_7[2]),
      value: (_newEnqPtrCandidate_new_ptr_T_7[1:0])};
  assign newEnqPtrCandidate_2 =
    '{flag: (_newEnqPtrCandidate_new_ptr_T_13[2]),
      value: (_newEnqPtrCandidate_new_ptr_T_13[1:0])};
  assign newEnqPtrCandidate_3 =
    '{flag: (_newEnqPtrCandidate_new_ptr_T_19[2]),
      value: (_newEnqPtrCandidate_new_ptr_T_19[1:0])};
  assign io =
    '{enq: io_enq,
      enqData: io_enqData,
      deq: io_deq,
      redirect: io_redirect,
      flushVec: io_flushVec,
      snapshots: snapshots,
      enqPtr: snptEnqPtr,
      deqPtr: snptDeqPtr,
      valids: snptValids};
  always @(posedge clock) begin
    automatic logic [8:0] _GEN_9;
    automatic logic       _GEN_10;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_11;
    automatic logic [8:0] _GEN_12;
    automatic logic       _GEN_13;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_14;
    automatic logic [8:0] _GEN_15;
    automatic logic       _GEN_16;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_17;
    automatic logic [8:0] _GEN_18;
    automatic logic       _GEN_19;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_20;
    automatic logic [8:0] _GEN_21;
    automatic logic       _GEN_22;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_23;
    automatic logic [8:0] _GEN_24;
    automatic logic       _GEN_25;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_26;
    automatic logic [8:0] _GEN_27;
    automatic logic       _GEN_28;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_29;
    automatic logic [8:0] _GEN_30;
    automatic logic       _GEN_31;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_32;
    automatic logic [7:0] _GEN_33;
    automatic logic [8:0] _GEN_34;
    automatic logic       _GEN_35;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_36;
    automatic logic [8:0] _GEN_37;
    automatic logic       _GEN_38;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_39;
    automatic logic [8:0] _GEN_40;
    automatic logic       _GEN_41;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_42;
    automatic logic [8:0] _GEN_43;
    automatic logic       _GEN_44;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_45;
    automatic logic [8:0] _GEN_46;
    automatic logic       _GEN_47;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_48;
    automatic logic [8:0] _GEN_49;
    automatic logic       _GEN_50;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_51;
    automatic logic [8:0] _GEN_52;
    automatic logic       _GEN_53;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_54;
    automatic logic [8:0] _GEN_55;
    automatic logic       _GEN_56;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_57;
    automatic logic [7:0] _GEN_58;
    automatic logic [8:0] _GEN_59;
    automatic logic       _GEN_60;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_61;
    automatic logic [8:0] _GEN_62;
    automatic logic       _GEN_63;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_64;
    automatic logic [8:0] _GEN_65;
    automatic logic       _GEN_66;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_67;
    automatic logic [8:0] _GEN_68;
    automatic logic       _GEN_69;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_70;
    automatic logic [8:0] _GEN_71;
    automatic logic       _GEN_72;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_73;
    automatic logic [8:0] _GEN_74;
    automatic logic       _GEN_75;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_76;
    automatic logic [8:0] _GEN_77;
    automatic logic       _GEN_78;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_79;
    automatic logic [8:0] _GEN_80;
    automatic logic       _GEN_81;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_82;
    automatic logic [7:0] _GEN_83;
    automatic logic [8:0] _GEN_84;
    automatic logic       _GEN_85;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_86;
    automatic logic [8:0] _GEN_87;
    automatic logic       _GEN_88;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_89;
    automatic logic [8:0] _GEN_90;
    automatic logic       _GEN_91;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_92;
    automatic logic [8:0] _GEN_93;
    automatic logic       _GEN_94;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_95;
    automatic logic [8:0] _GEN_96;
    automatic logic       _GEN_97;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_98;
    automatic logic [8:0] _GEN_99;
    automatic logic       _GEN_100;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_101;
    automatic logic [8:0] _GEN_102;
    automatic logic       _GEN_103;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_104;
    automatic logic [8:0] _GEN_105;
    automatic logic       _GEN_106;
    automatic       struct packed {logic flag; logic [8:0] value; } _GEN_107;
    automatic logic [7:0] _GEN_108;
    _GEN_9 = _GEN_3 ? io.enqData.robIdx[3'h7].value : snapshots[2'h3].robIdx[3'h7].value;
    _GEN_10 = _GEN_3 ? io.enqData.robIdx[3'h7].flag : snapshots[2'h3].robIdx[3'h7].flag;
    _GEN_11 = '{flag: _GEN_10, value: _GEN_9};
    _GEN_12 = _GEN_3 ? io.enqData.robIdx[3'h6].value : snapshots[2'h3].robIdx[3'h6].value;
    _GEN_13 = _GEN_3 ? io.enqData.robIdx[3'h6].flag : snapshots[2'h3].robIdx[3'h6].flag;
    _GEN_14 = '{flag: _GEN_13, value: _GEN_12};
    _GEN_15 = _GEN_3 ? io.enqData.robIdx[3'h5].value : snapshots[2'h3].robIdx[3'h5].value;
    _GEN_16 = _GEN_3 ? io.enqData.robIdx[3'h5].flag : snapshots[2'h3].robIdx[3'h5].flag;
    _GEN_17 = '{flag: _GEN_16, value: _GEN_15};
    _GEN_18 = _GEN_3 ? io.enqData.robIdx[3'h4].value : snapshots[2'h3].robIdx[3'h4].value;
    _GEN_19 = _GEN_3 ? io.enqData.robIdx[3'h4].flag : snapshots[2'h3].robIdx[3'h4].flag;
    _GEN_20 = '{flag: _GEN_19, value: _GEN_18};
    _GEN_21 = _GEN_3 ? io.enqData.robIdx[3'h3].value : snapshots[2'h3].robIdx[3'h3].value;
    _GEN_22 = _GEN_3 ? io.enqData.robIdx[3'h3].flag : snapshots[2'h3].robIdx[3'h3].flag;
    _GEN_23 = '{flag: _GEN_22, value: _GEN_21};
    _GEN_24 = _GEN_3 ? io.enqData.robIdx[3'h2].value : snapshots[2'h3].robIdx[3'h2].value;
    _GEN_25 = _GEN_3 ? io.enqData.robIdx[3'h2].flag : snapshots[2'h3].robIdx[3'h2].flag;
    _GEN_26 = '{flag: _GEN_25, value: _GEN_24};
    _GEN_27 = _GEN_3 ? io.enqData.robIdx[3'h1].value : snapshots[2'h3].robIdx[3'h1].value;
    _GEN_28 = _GEN_3 ? io.enqData.robIdx[3'h1].flag : snapshots[2'h3].robIdx[3'h1].flag;
    _GEN_29 = '{flag: _GEN_28, value: _GEN_27};
    _GEN_30 = _GEN_3 ? io.enqData.robIdx[3'h0].value : snapshots[2'h3].robIdx[3'h0].value;
    _GEN_31 = _GEN_3 ? io.enqData.robIdx[3'h0].flag : snapshots[2'h3].robIdx[3'h0].flag;
    _GEN_32 = '{flag: _GEN_31, value: _GEN_30};
    _GEN_33 = _GEN_3 ? io.enqData.isCFI : snapshots[2'h3].isCFI;
    snapshots[2'h3] <=
      '{robIdx:
          ({{_GEN_11},
            {_GEN_14},
            {_GEN_17},
            {_GEN_20},
            {_GEN_23},
            {_GEN_26},
            {_GEN_29},
            {_GEN_32}}),
        isCFI: _GEN_33};
    _GEN_34 = _GEN_2 ? io.enqData.robIdx[3'h7].value : snapshots[2'h2].robIdx[3'h7].value;
    _GEN_35 = _GEN_2 ? io.enqData.robIdx[3'h7].flag : snapshots[2'h2].robIdx[3'h7].flag;
    _GEN_36 = '{flag: _GEN_35, value: _GEN_34};
    _GEN_37 = _GEN_2 ? io.enqData.robIdx[3'h6].value : snapshots[2'h2].robIdx[3'h6].value;
    _GEN_38 = _GEN_2 ? io.enqData.robIdx[3'h6].flag : snapshots[2'h2].robIdx[3'h6].flag;
    _GEN_39 = '{flag: _GEN_38, value: _GEN_37};
    _GEN_40 = _GEN_2 ? io.enqData.robIdx[3'h5].value : snapshots[2'h2].robIdx[3'h5].value;
    _GEN_41 = _GEN_2 ? io.enqData.robIdx[3'h5].flag : snapshots[2'h2].robIdx[3'h5].flag;
    _GEN_42 = '{flag: _GEN_41, value: _GEN_40};
    _GEN_43 = _GEN_2 ? io.enqData.robIdx[3'h4].value : snapshots[2'h2].robIdx[3'h4].value;
    _GEN_44 = _GEN_2 ? io.enqData.robIdx[3'h4].flag : snapshots[2'h2].robIdx[3'h4].flag;
    _GEN_45 = '{flag: _GEN_44, value: _GEN_43};
    _GEN_46 = _GEN_2 ? io.enqData.robIdx[3'h3].value : snapshots[2'h2].robIdx[3'h3].value;
    _GEN_47 = _GEN_2 ? io.enqData.robIdx[3'h3].flag : snapshots[2'h2].robIdx[3'h3].flag;
    _GEN_48 = '{flag: _GEN_47, value: _GEN_46};
    _GEN_49 = _GEN_2 ? io.enqData.robIdx[3'h2].value : snapshots[2'h2].robIdx[3'h2].value;
    _GEN_50 = _GEN_2 ? io.enqData.robIdx[3'h2].flag : snapshots[2'h2].robIdx[3'h2].flag;
    _GEN_51 = '{flag: _GEN_50, value: _GEN_49};
    _GEN_52 = _GEN_2 ? io.enqData.robIdx[3'h1].value : snapshots[2'h2].robIdx[3'h1].value;
    _GEN_53 = _GEN_2 ? io.enqData.robIdx[3'h1].flag : snapshots[2'h2].robIdx[3'h1].flag;
    _GEN_54 = '{flag: _GEN_53, value: _GEN_52};
    _GEN_55 = _GEN_2 ? io.enqData.robIdx[3'h0].value : snapshots[2'h2].robIdx[3'h0].value;
    _GEN_56 = _GEN_2 ? io.enqData.robIdx[3'h0].flag : snapshots[2'h2].robIdx[3'h0].flag;
    _GEN_57 = '{flag: _GEN_56, value: _GEN_55};
    _GEN_58 = _GEN_2 ? io.enqData.isCFI : snapshots[2'h2].isCFI;
    snapshots[2'h2] <=
      '{robIdx:
          ({{_GEN_36},
            {_GEN_39},
            {_GEN_42},
            {_GEN_45},
            {_GEN_48},
            {_GEN_51},
            {_GEN_54},
            {_GEN_57}}),
        isCFI: _GEN_58};
    _GEN_59 = _GEN_1 ? io.enqData.robIdx[3'h7].value : snapshots[2'h1].robIdx[3'h7].value;
    _GEN_60 = _GEN_1 ? io.enqData.robIdx[3'h7].flag : snapshots[2'h1].robIdx[3'h7].flag;
    _GEN_61 = '{flag: _GEN_60, value: _GEN_59};
    _GEN_62 = _GEN_1 ? io.enqData.robIdx[3'h6].value : snapshots[2'h1].robIdx[3'h6].value;
    _GEN_63 = _GEN_1 ? io.enqData.robIdx[3'h6].flag : snapshots[2'h1].robIdx[3'h6].flag;
    _GEN_64 = '{flag: _GEN_63, value: _GEN_62};
    _GEN_65 = _GEN_1 ? io.enqData.robIdx[3'h5].value : snapshots[2'h1].robIdx[3'h5].value;
    _GEN_66 = _GEN_1 ? io.enqData.robIdx[3'h5].flag : snapshots[2'h1].robIdx[3'h5].flag;
    _GEN_67 = '{flag: _GEN_66, value: _GEN_65};
    _GEN_68 = _GEN_1 ? io.enqData.robIdx[3'h4].value : snapshots[2'h1].robIdx[3'h4].value;
    _GEN_69 = _GEN_1 ? io.enqData.robIdx[3'h4].flag : snapshots[2'h1].robIdx[3'h4].flag;
    _GEN_70 = '{flag: _GEN_69, value: _GEN_68};
    _GEN_71 = _GEN_1 ? io.enqData.robIdx[3'h3].value : snapshots[2'h1].robIdx[3'h3].value;
    _GEN_72 = _GEN_1 ? io.enqData.robIdx[3'h3].flag : snapshots[2'h1].robIdx[3'h3].flag;
    _GEN_73 = '{flag: _GEN_72, value: _GEN_71};
    _GEN_74 = _GEN_1 ? io.enqData.robIdx[3'h2].value : snapshots[2'h1].robIdx[3'h2].value;
    _GEN_75 = _GEN_1 ? io.enqData.robIdx[3'h2].flag : snapshots[2'h1].robIdx[3'h2].flag;
    _GEN_76 = '{flag: _GEN_75, value: _GEN_74};
    _GEN_77 = _GEN_1 ? io.enqData.robIdx[3'h1].value : snapshots[2'h1].robIdx[3'h1].value;
    _GEN_78 = _GEN_1 ? io.enqData.robIdx[3'h1].flag : snapshots[2'h1].robIdx[3'h1].flag;
    _GEN_79 = '{flag: _GEN_78, value: _GEN_77};
    _GEN_80 = _GEN_1 ? io.enqData.robIdx[3'h0].value : snapshots[2'h1].robIdx[3'h0].value;
    _GEN_81 = _GEN_1 ? io.enqData.robIdx[3'h0].flag : snapshots[2'h1].robIdx[3'h0].flag;
    _GEN_82 = '{flag: _GEN_81, value: _GEN_80};
    _GEN_83 = _GEN_1 ? io.enqData.isCFI : snapshots[2'h1].isCFI;
    snapshots[2'h1] <=
      '{robIdx:
          ({{_GEN_61},
            {_GEN_64},
            {_GEN_67},
            {_GEN_70},
            {_GEN_73},
            {_GEN_76},
            {_GEN_79},
            {_GEN_82}}),
        isCFI: _GEN_83};
    _GEN_84 = _GEN_0 ? io.enqData.robIdx[3'h7].value : snapshots[2'h0].robIdx[3'h7].value;
    _GEN_85 = _GEN_0 ? io.enqData.robIdx[3'h7].flag : snapshots[2'h0].robIdx[3'h7].flag;
    _GEN_86 = '{flag: _GEN_85, value: _GEN_84};
    _GEN_87 = _GEN_0 ? io.enqData.robIdx[3'h6].value : snapshots[2'h0].robIdx[3'h6].value;
    _GEN_88 = _GEN_0 ? io.enqData.robIdx[3'h6].flag : snapshots[2'h0].robIdx[3'h6].flag;
    _GEN_89 = '{flag: _GEN_88, value: _GEN_87};
    _GEN_90 = _GEN_0 ? io.enqData.robIdx[3'h5].value : snapshots[2'h0].robIdx[3'h5].value;
    _GEN_91 = _GEN_0 ? io.enqData.robIdx[3'h5].flag : snapshots[2'h0].robIdx[3'h5].flag;
    _GEN_92 = '{flag: _GEN_91, value: _GEN_90};
    _GEN_93 = _GEN_0 ? io.enqData.robIdx[3'h4].value : snapshots[2'h0].robIdx[3'h4].value;
    _GEN_94 = _GEN_0 ? io.enqData.robIdx[3'h4].flag : snapshots[2'h0].robIdx[3'h4].flag;
    _GEN_95 = '{flag: _GEN_94, value: _GEN_93};
    _GEN_96 = _GEN_0 ? io.enqData.robIdx[3'h3].value : snapshots[2'h0].robIdx[3'h3].value;
    _GEN_97 = _GEN_0 ? io.enqData.robIdx[3'h3].flag : snapshots[2'h0].robIdx[3'h3].flag;
    _GEN_98 = '{flag: _GEN_97, value: _GEN_96};
    _GEN_99 = _GEN_0 ? io.enqData.robIdx[3'h2].value : snapshots[2'h0].robIdx[3'h2].value;
    _GEN_100 = _GEN_0 ? io.enqData.robIdx[3'h2].flag : snapshots[2'h0].robIdx[3'h2].flag;
    _GEN_101 = '{flag: _GEN_100, value: _GEN_99};
    _GEN_102 =
      _GEN_0 ? io.enqData.robIdx[3'h1].value : snapshots[2'h0].robIdx[3'h1].value;
    _GEN_103 = _GEN_0 ? io.enqData.robIdx[3'h1].flag : snapshots[2'h0].robIdx[3'h1].flag;
    _GEN_104 = '{flag: _GEN_103, value: _GEN_102};
    _GEN_105 =
      _GEN_0 ? io.enqData.robIdx[3'h0].value : snapshots[2'h0].robIdx[3'h0].value;
    _GEN_106 = _GEN_0 ? io.enqData.robIdx[3'h0].flag : snapshots[2'h0].robIdx[3'h0].flag;
    _GEN_107 = '{flag: _GEN_106, value: _GEN_105};
    _GEN_108 = _GEN_0 ? io.enqData.isCFI : snapshots[2'h0].isCFI;
    snapshots[2'h0] <=
      '{robIdx:
          ({{_GEN_86},
            {_GEN_89},
            {_GEN_92},
            {_GEN_95},
            {_GEN_98},
            {_GEN_101},
            {_GEN_104},
            {_GEN_107}}),
        isCFI: _GEN_108};
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      snptEnqPtr <= '{flag: 1'h0, value: 2'h0};
    else begin
      automatic logic       _GEN_109;
      automatic       struct packed {logic flag; logic [1:0] value; } _snptEnqPtr_T =
        newEnqPtrQualified[2'h2] ? newEnqPtrCandidate_2 : newEnqPtrCandidate_3;
      automatic       struct packed {logic flag; logic [1:0] value; } _snptEnqPtr_T_1 =
        newEnqPtrQualified[2'h1] ? newEnqPtrCandidate_1 : _snptEnqPtr_T;
      automatic       struct packed {logic flag; logic [1:0] value; } _snptEnqPtr_T_2 =
        newEnqPtrQualified[2'h0] ? newEnqPtrCandidate_0 : _snptEnqPtr_T_1;
      automatic logic [1:0] _GEN_110;
      automatic logic [1:0] _GEN_111;
      automatic logic       _GEN_112;
      automatic logic       _GEN_113;
      _GEN_109 =
        |({io.flushVec[2'h0], io.flushVec[2'h1], io.flushVec[2'h2], io.flushVec[2'h3]}
          & {snptValids[2'h0], snptValids[2'h1], snptValids[2'h2], snptValids[2'h3]});
      _GEN_110 = _GEN ? snptEnqPtr_new_ptr.value : snptEnqPtr.value;
      _GEN_111 = _GEN_109 ? _snptEnqPtr_T_2.value : _GEN_110;
      _GEN_112 = _GEN ? snptEnqPtr_new_ptr.flag : snptEnqPtr.flag;
      _GEN_113 = _GEN_109 ? _snptEnqPtr_T_2.flag : _GEN_112;
      snptEnqPtr <= '{flag: _GEN_113, value: _GEN_111};
    end
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      snptDeqPtr <= '{flag: 1'h0, value: 2'h0};
    else begin
      automatic logic [1:0] _GEN_114;
      automatic logic       _GEN_115;
      _GEN_114 = _GEN_4 ? snptDeqPtr_new_ptr.value : snptDeqPtr.value;
      _GEN_115 = _GEN_4 ? snptDeqPtr_new_ptr.flag : snptDeqPtr.flag;
      snptDeqPtr <= '{flag: _GEN_115, value: _GEN_114};
    end
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      snptValids <= '{1'h0, 1'h0, 1'h0, 1'h0};
    else begin
      snptValids[2'h3] <=
        ~(io.flushVec[2'h3] | _GEN_4 & (&snptDeqPtr.value)) & (_GEN_3 | snptValids[2'h3]);
      snptValids[2'h2] <=
        ~(io.flushVec[2'h2] | _GEN_4 & snptDeqPtr.value == 2'h2)
        & (_GEN_2 | snptValids[2'h2]);
      snptValids[2'h1] <=
        ~(io.flushVec[2'h1] | _GEN_4 & snptDeqPtr.value == 2'h1)
        & (_GEN_1 | snptValids[2'h1]);
      snptValids[2'h0] <=
        ~(io.flushVec[2'h0] | _GEN_4 & snptDeqPtr.value == 2'h0)
        & (_GEN_0 | snptValids[2'h0]);
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        automatic struct packed {logic flag; logic [1:0] value; } _snptEnqPtr_WIRE =
          '{flag: 1'h0, value: 2'h0};
        snptEnqPtr = _snptEnqPtr_WIRE;
        snptDeqPtr = _snptEnqPtr_WIRE;
        snptValids = '{1'h0, 1'h0, 1'h0, 1'h0};
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_snapshots = io.snapshots;
  assign io_enqPtr = io.enqPtr;
  assign io_deqPtr = io.deqPtr;
  assign io_valids = io.valids;
endmodule

