// Generated by CIRCT firtool-1.150.2
module SstcInterruptGen(
  input                                                                                                                                                                                                                                                                                                                                                                                clock,
                                                                                                                                                                                                                                                                                                                                                                                       reset,
  input  struct packed {struct packed {logic valid; logic [63:0] bits; } stime; struct packed {logic valid; logic [63:0] bits; } vstime; struct packed {logic wen; logic [63:0] rdata; } stimecmp; struct packed {logic wen; logic [63:0] rdata; } vstimecmp; logic htimedeltaWen; struct packed {logic wen; logic STCE; } menvcfg; struct packed {logic wen; logic STCE; } henvcfg; } i,
  output struct packed {logic STIP; logic VSTIP; }                                                                                                                                                                                                                                                                                                                                     o
);

  reg o_STIP_r;
  reg o_VSTIP_r;
  always @(posedge clock or posedge reset) begin
    if (reset)
      o_STIP_r <= 1'h0;
    else if (i.stime.valid | i.stimecmp.wen | i.menvcfg.wen)
      o_STIP_r <= i.stime.bits >= i.stimecmp.rdata & i.menvcfg.STCE;
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      o_VSTIP_r <= 1'h0;
    else if (i.vstime.valid | i.vstimecmp.wen | i.htimedeltaWen | i.menvcfg.wen
             | i.henvcfg.wen)
      o_VSTIP_r <= i.vstime.bits >= i.vstimecmp.rdata & i.henvcfg.STCE;
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        o_STIP_r = 1'h0;
        o_VSTIP_r = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign o = '{STIP: o_STIP_r, VSTIP: o_VSTIP_r};
endmodule

