// Generated by CIRCT firtool-1.150.2
module SubModule(
  input  [1:0][63:0] io_src,
  output [64:0]      io_sub
);

  wire struct packed {logic [1:0][63:0] src; logic [64:0] sub; } io;
  assign io = '{src: io_src, sub: ({1'h0, io.src[1'h0]} + {1'h0, ~io.src[1'h1]} + 65'h1)};
  assign io_sub = io.sub;
endmodule

