// Generated by CIRCT firtool-1.150.2
module timeModule(
  input                                                                                                                                                      clock,
                                                                                                                                                             reset,
  input  struct packed {logic wen; logic [63:0] wdata; }                                                                                                     w,
  output [63:0]                                                                                                                                              rdata,
  input  struct packed {logic [63:0] cycle; struct packed {logic valid; logic [63:0] bits; } time_0; logic [63:0] instret; logic [28:0][63:0] hpmcounters; } mHPM,
  input                                                                                                                                                      v,
                                                                                                                                                             nextV,
  input  [63:0]                                                                                                                                              htimedelta,
  input                                                                                                                                                      debugModeStopTime,
  output                                                                                                                                                     updated,
  output [63:0]                                                                                                                                              stime,
                                                                                                                                                             vstime
);

  struct packed {logic [63:0] time_0; } reg_0;
  wire [63:0] vstimeTmp = mHPM.time_0.bits + htimedelta;
  reg         virtModeChanged;
  reg         updated_last_REG;
  wire        updated_last = updated_last_REG;
  wire struct packed {logic [63:0] time_0; } wdata = '{time_0: w.wdata};
  always @(posedge clock) begin
    automatic logic [63:0] _reg_time_WIRE_1 = v ? vstimeTmp : mHPM.time_0.bits;
    automatic logic [63:0] _GEN;
    _GEN =
      mHPM.time_0.valid & ~debugModeStopTime | virtModeChanged
        ? _reg_time_WIRE_1
        : reg_0.time_0;
    reg_0 <= '{time_0: _GEN};
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      virtModeChanged <= 1'h0;
    else
      virtModeChanged <= nextV != v;
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      updated_last_REG <= 1'h0;
    else
      updated_last_REG <= mHPM.time_0.valid & ~debugModeStopTime;
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        virtModeChanged = 1'h0;
        updated_last_REG = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign rdata = reg_0.time_0;
  assign updated = updated_last;
  assign stime = mHPM.time_0.bits;
  assign vstime = vstimeTmp;
endmodule

