// Generated by CIRCT firtool-1.150.2
module TinfoModule(
  input                                                           clock,
                                                                  reset,
  input  struct packed {logic wen; logic [63:0] wdata; }          w,
  output [63:0]                                                   rdata,
  output struct packed {logic [7:0] VERSION; logic MCONTROL6EN; } regOut
);

  struct packed {logic [7:0] VERSION; logic MCONTROL6EN; } reg_0;
  wire struct packed {logic [7:0] VERSION; logic MCONTROL6EN; } reg_init =
    '{VERSION: 8'h1, MCONTROL6EN: 1'h1};
  wire struct packed {logic [7:0] VERSION; logic MCONTROL6EN; } wdata =
    '{VERSION: (w.wdata[31:24]), MCONTROL6EN: (w.wdata[6])};
  always @(posedge clock or posedge reset) begin
    if (reset)
      reg_0 <= reg_init;
    else
      reg_0 <= reg_0;
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset)
        reg_0 = reg_init;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign rdata = {32'h0, reg_0.VERSION, 17'h0, reg_0.MCONTROL6EN, 6'h0};
  assign regOut = reg_0;
endmodule

