// Generated by CIRCT firtool-1.150.2
module Trace(
  input                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           clock,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  reset,
  input  struct packed {logic enable; logic stall; }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              io_in_fromEncoder,
  input  struct packed {struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; } bits; }[7:0] blocks; }                                                                                                                                                                                                                                                                                                                   io_in_fromRob,
  output struct packed {struct packed {struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; } bits; }[2:0] blocks; } toPcMem; struct packed {struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; } bits; }[2:0] blocks; } toEncoder; logic blockRobCommit; } io_out
);

  wire
    struct packed {logic blockCommit; struct packed {struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; } bits; }[2:0] blocks; } groups; }
    _traceBuffer_io_out;
  wire
    struct packed {struct packed {struct packed {logic enable; logic stall; } fromEncoder; struct packed {struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; } bits; }[7:0] blocks; } fromRob; } in; struct packed {struct packed {struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; } bits; }[2:0] blocks; } toPcMem; struct packed {struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; } bits; }[2:0] blocks; } toEncoder; logic blockRobCommit; } out; }
    io;
  wire
    struct packed {struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; } bits; }[7:0] blocks; }
    s1_out;
  reg  s1_out_blocks_0_valid_r;
  struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; }
    s1_out_blocks_0_bits_r;
  reg  s1_out_blocks_1_valid_r;
  struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; }
    s1_out_blocks_1_bits_r;
  reg  s1_out_blocks_2_valid_r;
  struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; }
    s1_out_blocks_2_bits_r;
  reg  s1_out_blocks_3_valid_r;
  struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; }
    s1_out_blocks_3_bits_r;
  reg  s1_out_blocks_4_valid_r;
  struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; }
    s1_out_blocks_4_bits_r;
  reg  s1_out_blocks_5_valid_r;
  struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; }
    s1_out_blocks_5_bits_r;
  reg  s1_out_blocks_6_valid_r;
  struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; }
    s1_out_blocks_6_bits_r;
  reg  s1_out_blocks_7_valid_r;
  struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; }
    s1_out_blocks_7_bits_r;
  wire blockCommit = _traceBuffer_io_out.blockCommit;
  struct packed {struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; } bits; }[2:0] blocks; }
    s3_out_groups;
  wire
    struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; } bits; }
    _GEN = '{valid: s1_out_blocks_7_valid_r, bits: s1_out_blocks_7_bits_r};
  wire
    struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; } bits; }
    _GEN_0 = '{valid: s1_out_blocks_6_valid_r, bits: s1_out_blocks_6_bits_r};
  wire
    struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; } bits; }
    _GEN_1 = '{valid: s1_out_blocks_5_valid_r, bits: s1_out_blocks_5_bits_r};
  wire
    struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; } bits; }
    _GEN_2 = '{valid: s1_out_blocks_4_valid_r, bits: s1_out_blocks_4_bits_r};
  wire
    struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; } bits; }
    _GEN_3 = '{valid: s1_out_blocks_3_valid_r, bits: s1_out_blocks_3_bits_r};
  wire
    struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; } bits; }
    _GEN_4 = '{valid: s1_out_blocks_2_valid_r, bits: s1_out_blocks_2_bits_r};
  wire
    struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; } bits; }
    _GEN_5 = '{valid: s1_out_blocks_1_valid_r, bits: s1_out_blocks_1_bits_r};
  wire
    struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; } bits; }
    _GEN_6 = '{valid: s1_out_blocks_0_valid_r, bits: s1_out_blocks_0_bits_r};
  assign s1_out =
    '{blocks:
        ({{_GEN}, {_GEN_0}, {_GEN_1}, {_GEN_2}, {_GEN_3}, {_GEN_4}, {_GEN_5}, {_GEN_6}})};
  wire struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } _GEN_7 =
    '{itype: s1_out.blocks[3'h7].bits.tracePipe.itype,
      iretire: {3'h0, s1_out.blocks[3'h7].bits.tracePipe.iretire},
      ilastsize: s1_out.blocks[3'h7].bits.tracePipe.ilastsize};
  wire struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } _GEN_8 =
    '{itype: s1_out.blocks[3'h6].bits.tracePipe.itype,
      iretire: {3'h0, s1_out.blocks[3'h6].bits.tracePipe.iretire},
      ilastsize: s1_out.blocks[3'h6].bits.tracePipe.ilastsize};
  wire struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } _GEN_9 =
    '{itype: s1_out.blocks[3'h5].bits.tracePipe.itype,
      iretire: {3'h0, s1_out.blocks[3'h5].bits.tracePipe.iretire},
      ilastsize: s1_out.blocks[3'h5].bits.tracePipe.ilastsize};
  wire struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } _GEN_10 =
    '{itype: s1_out.blocks[3'h4].bits.tracePipe.itype,
      iretire: {3'h0, s1_out.blocks[3'h4].bits.tracePipe.iretire},
      ilastsize: s1_out.blocks[3'h4].bits.tracePipe.ilastsize};
  wire struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } _GEN_11 =
    '{itype: s1_out.blocks[3'h3].bits.tracePipe.itype,
      iretire: {3'h0, s1_out.blocks[3'h3].bits.tracePipe.iretire},
      ilastsize: s1_out.blocks[3'h3].bits.tracePipe.ilastsize};
  wire struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } _GEN_12 =
    '{itype: s1_out.blocks[3'h2].bits.tracePipe.itype,
      iretire: {3'h0, s1_out.blocks[3'h2].bits.tracePipe.iretire},
      ilastsize: s1_out.blocks[3'h2].bits.tracePipe.ilastsize};
  wire struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } _GEN_13 =
    '{itype: s1_out.blocks[3'h1].bits.tracePipe.itype,
      iretire: {3'h0, s1_out.blocks[3'h1].bits.tracePipe.iretire},
      ilastsize: s1_out.blocks[3'h1].bits.tracePipe.ilastsize};
  wire struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } _GEN_14 =
    '{itype: s1_out.blocks[3'h0].bits.tracePipe.itype,
      iretire: {3'h0, s1_out.blocks[3'h0].bits.tracePipe.iretire},
      ilastsize: s1_out.blocks[3'h0].bits.tracePipe.ilastsize};
  wire
    struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; }
    _GEN_15 =
    '{ftqIdx: s1_out.blocks[3'h7].bits.ftqIdx,
      ftqOffset: s1_out.blocks[3'h7].bits.ftqOffset,
      tracePipe: _GEN_7};
  wire
    struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; }
    _GEN_16 =
    '{ftqIdx: s1_out.blocks[3'h6].bits.ftqIdx,
      ftqOffset: s1_out.blocks[3'h6].bits.ftqOffset,
      tracePipe: _GEN_8};
  wire
    struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; }
    _GEN_17 =
    '{ftqIdx: s1_out.blocks[3'h5].bits.ftqIdx,
      ftqOffset: s1_out.blocks[3'h5].bits.ftqOffset,
      tracePipe: _GEN_9};
  wire
    struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; }
    _GEN_18 =
    '{ftqIdx: s1_out.blocks[3'h4].bits.ftqIdx,
      ftqOffset: s1_out.blocks[3'h4].bits.ftqOffset,
      tracePipe: _GEN_10};
  wire
    struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; }
    _GEN_19 =
    '{ftqIdx: s1_out.blocks[3'h3].bits.ftqIdx,
      ftqOffset: s1_out.blocks[3'h3].bits.ftqOffset,
      tracePipe: _GEN_11};
  wire
    struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; }
    _GEN_20 =
    '{ftqIdx: s1_out.blocks[3'h2].bits.ftqIdx,
      ftqOffset: s1_out.blocks[3'h2].bits.ftqOffset,
      tracePipe: _GEN_12};
  wire
    struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; }
    _GEN_21 =
    '{ftqIdx: s1_out.blocks[3'h1].bits.ftqIdx,
      ftqOffset: s1_out.blocks[3'h1].bits.ftqOffset,
      tracePipe: _GEN_13};
  wire
    struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; }
    _GEN_22 =
    '{ftqIdx: s1_out.blocks[3'h0].bits.ftqIdx,
      ftqOffset: s1_out.blocks[3'h0].bits.ftqOffset,
      tracePipe: _GEN_14};
  wire
    struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; } bits; }
    _GEN_23 = '{valid: s1_out.blocks[3'h7].valid, bits: _GEN_15};
  wire
    struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; } bits; }
    _GEN_24 = '{valid: s1_out.blocks[3'h6].valid, bits: _GEN_16};
  wire
    struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; } bits; }
    _GEN_25 = '{valid: s1_out.blocks[3'h5].valid, bits: _GEN_17};
  wire
    struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; } bits; }
    _GEN_26 = '{valid: s1_out.blocks[3'h4].valid, bits: _GEN_18};
  wire
    struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; } bits; }
    _GEN_27 = '{valid: s1_out.blocks[3'h3].valid, bits: _GEN_19};
  wire
    struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; } bits; }
    _GEN_28 = '{valid: s1_out.blocks[3'h2].valid, bits: _GEN_20};
  wire
    struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; } bits; }
    _GEN_29 = '{valid: s1_out.blocks[3'h1].valid, bits: _GEN_21};
  wire
    struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; } bits; }
    _GEN_30 = '{valid: s1_out.blocks[3'h0].valid, bits: _GEN_22};
  wire
    struct packed {struct packed {logic enable; logic stall; } fromEncoder; struct packed {struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; } bits; }[7:0] blocks; } fromRob; }
    _GEN_31 = '{fromEncoder: io_in_fromEncoder, fromRob: io_in_fromRob};
  wire
    struct packed {struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; } bits; }[7:0] blocks; }
    _GEN_32 =
    '{blocks:
        ({{_GEN_23},
          {_GEN_24},
          {_GEN_25},
          {_GEN_26},
          {_GEN_27},
          {_GEN_28},
          {_GEN_29},
          {_GEN_30}})};
  wire
    struct packed {struct packed {struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; } bits; }[2:0] blocks; } toPcMem; struct packed {struct packed {logic valid; struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [7:0] iretire; logic ilastsize; } tracePipe; } bits; }[2:0] blocks; } toEncoder; logic blockRobCommit; }
    _GEN_33 =
    '{toPcMem: _traceBuffer_io_out.groups,
      toEncoder: s3_out_groups,
      blockRobCommit: blockCommit};
  assign io = '{in: _GEN_31, out: _GEN_33};
  always @(posedge clock or posedge reset) begin
    if (reset)
      s1_out_blocks_0_valid_r <= 1'h0;
    else if (blockCommit) begin
    end
    else
      s1_out_blocks_0_valid_r <= io.in.fromRob.blocks[3'h0].valid;
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      s1_out_blocks_0_bits_r <=
        '{ftqIdx: '{flag: 1'h0, value: 6'h0},
          ftqOffset: 5'h0,
          tracePipe: '{itype: 4'h0, iretire: 5'h0, ilastsize: 1'h0}};
    else begin
      automatic logic       _GEN_34;
      automatic logic [4:0] _GEN_35;
      automatic logic [3:0] _GEN_36;
      automatic
        struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } _GEN_37;
      automatic logic [5:0] _GEN_38;
      automatic logic       _GEN_39;
      automatic       struct packed {logic flag; logic [5:0] value; } _GEN_40;
      automatic logic [4:0] _GEN_41;
      _GEN_34 =
        io.in.fromRob.blocks[3'h0].valid
          ? io.in.fromRob.blocks[3'h0].bits.tracePipe.ilastsize
          : s1_out_blocks_0_bits_r.tracePipe.ilastsize;
      _GEN_35 =
        io.in.fromRob.blocks[3'h0].valid
          ? io.in.fromRob.blocks[3'h0].bits.tracePipe.iretire
          : s1_out_blocks_0_bits_r.tracePipe.iretire;
      _GEN_36 =
        io.in.fromRob.blocks[3'h0].valid
          ? io.in.fromRob.blocks[3'h0].bits.tracePipe.itype
          : s1_out_blocks_0_bits_r.tracePipe.itype;
      _GEN_37 = '{itype: _GEN_36, iretire: _GEN_35, ilastsize: _GEN_34};
      _GEN_38 =
        io.in.fromRob.blocks[3'h0].valid
          ? io.in.fromRob.blocks[3'h0].bits.ftqIdx.value
          : s1_out_blocks_0_bits_r.ftqIdx.value;
      _GEN_39 =
        io.in.fromRob.blocks[3'h0].valid
          ? io.in.fromRob.blocks[3'h0].bits.ftqIdx.flag
          : s1_out_blocks_0_bits_r.ftqIdx.flag;
      _GEN_40 = '{flag: _GEN_39, value: _GEN_38};
      _GEN_41 =
        io.in.fromRob.blocks[3'h0].valid
          ? io.in.fromRob.blocks[3'h0].bits.ftqOffset
          : s1_out_blocks_0_bits_r.ftqOffset;
      s1_out_blocks_0_bits_r <=
        '{ftqIdx: _GEN_40, ftqOffset: _GEN_41, tracePipe: _GEN_37};
    end
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      s1_out_blocks_1_valid_r <= 1'h0;
    else if (blockCommit) begin
    end
    else
      s1_out_blocks_1_valid_r <= io.in.fromRob.blocks[3'h1].valid;
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      s1_out_blocks_1_bits_r <=
        '{ftqIdx: '{flag: 1'h0, value: 6'h0},
          ftqOffset: 5'h0,
          tracePipe: '{itype: 4'h0, iretire: 5'h0, ilastsize: 1'h0}};
    else begin
      automatic logic       _GEN_42;
      automatic logic [4:0] _GEN_43;
      automatic logic [3:0] _GEN_44;
      automatic
        struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } _GEN_45;
      automatic logic [5:0] _GEN_46;
      automatic logic       _GEN_47;
      automatic       struct packed {logic flag; logic [5:0] value; } _GEN_48;
      automatic logic [4:0] _GEN_49;
      _GEN_42 =
        io.in.fromRob.blocks[3'h1].valid
          ? io.in.fromRob.blocks[3'h1].bits.tracePipe.ilastsize
          : s1_out_blocks_1_bits_r.tracePipe.ilastsize;
      _GEN_43 =
        io.in.fromRob.blocks[3'h1].valid
          ? io.in.fromRob.blocks[3'h1].bits.tracePipe.iretire
          : s1_out_blocks_1_bits_r.tracePipe.iretire;
      _GEN_44 =
        io.in.fromRob.blocks[3'h1].valid
          ? io.in.fromRob.blocks[3'h1].bits.tracePipe.itype
          : s1_out_blocks_1_bits_r.tracePipe.itype;
      _GEN_45 = '{itype: _GEN_44, iretire: _GEN_43, ilastsize: _GEN_42};
      _GEN_46 =
        io.in.fromRob.blocks[3'h1].valid
          ? io.in.fromRob.blocks[3'h1].bits.ftqIdx.value
          : s1_out_blocks_1_bits_r.ftqIdx.value;
      _GEN_47 =
        io.in.fromRob.blocks[3'h1].valid
          ? io.in.fromRob.blocks[3'h1].bits.ftqIdx.flag
          : s1_out_blocks_1_bits_r.ftqIdx.flag;
      _GEN_48 = '{flag: _GEN_47, value: _GEN_46};
      _GEN_49 =
        io.in.fromRob.blocks[3'h1].valid
          ? io.in.fromRob.blocks[3'h1].bits.ftqOffset
          : s1_out_blocks_1_bits_r.ftqOffset;
      s1_out_blocks_1_bits_r <=
        '{ftqIdx: _GEN_48, ftqOffset: _GEN_49, tracePipe: _GEN_45};
    end
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      s1_out_blocks_2_valid_r <= 1'h0;
    else if (blockCommit) begin
    end
    else
      s1_out_blocks_2_valid_r <= io.in.fromRob.blocks[3'h2].valid;
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      s1_out_blocks_2_bits_r <=
        '{ftqIdx: '{flag: 1'h0, value: 6'h0},
          ftqOffset: 5'h0,
          tracePipe: '{itype: 4'h0, iretire: 5'h0, ilastsize: 1'h0}};
    else begin
      automatic logic       _GEN_50;
      automatic logic [4:0] _GEN_51;
      automatic logic [3:0] _GEN_52;
      automatic
        struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } _GEN_53;
      automatic logic [5:0] _GEN_54;
      automatic logic       _GEN_55;
      automatic       struct packed {logic flag; logic [5:0] value; } _GEN_56;
      automatic logic [4:0] _GEN_57;
      _GEN_50 =
        io.in.fromRob.blocks[3'h2].valid
          ? io.in.fromRob.blocks[3'h2].bits.tracePipe.ilastsize
          : s1_out_blocks_2_bits_r.tracePipe.ilastsize;
      _GEN_51 =
        io.in.fromRob.blocks[3'h2].valid
          ? io.in.fromRob.blocks[3'h2].bits.tracePipe.iretire
          : s1_out_blocks_2_bits_r.tracePipe.iretire;
      _GEN_52 =
        io.in.fromRob.blocks[3'h2].valid
          ? io.in.fromRob.blocks[3'h2].bits.tracePipe.itype
          : s1_out_blocks_2_bits_r.tracePipe.itype;
      _GEN_53 = '{itype: _GEN_52, iretire: _GEN_51, ilastsize: _GEN_50};
      _GEN_54 =
        io.in.fromRob.blocks[3'h2].valid
          ? io.in.fromRob.blocks[3'h2].bits.ftqIdx.value
          : s1_out_blocks_2_bits_r.ftqIdx.value;
      _GEN_55 =
        io.in.fromRob.blocks[3'h2].valid
          ? io.in.fromRob.blocks[3'h2].bits.ftqIdx.flag
          : s1_out_blocks_2_bits_r.ftqIdx.flag;
      _GEN_56 = '{flag: _GEN_55, value: _GEN_54};
      _GEN_57 =
        io.in.fromRob.blocks[3'h2].valid
          ? io.in.fromRob.blocks[3'h2].bits.ftqOffset
          : s1_out_blocks_2_bits_r.ftqOffset;
      s1_out_blocks_2_bits_r <=
        '{ftqIdx: _GEN_56, ftqOffset: _GEN_57, tracePipe: _GEN_53};
    end
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      s1_out_blocks_3_valid_r <= 1'h0;
    else if (blockCommit) begin
    end
    else
      s1_out_blocks_3_valid_r <= io.in.fromRob.blocks[3'h3].valid;
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      s1_out_blocks_3_bits_r <=
        '{ftqIdx: '{flag: 1'h0, value: 6'h0},
          ftqOffset: 5'h0,
          tracePipe: '{itype: 4'h0, iretire: 5'h0, ilastsize: 1'h0}};
    else begin
      automatic logic       _GEN_58;
      automatic logic [4:0] _GEN_59;
      automatic logic [3:0] _GEN_60;
      automatic
        struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } _GEN_61;
      automatic logic [5:0] _GEN_62;
      automatic logic       _GEN_63;
      automatic       struct packed {logic flag; logic [5:0] value; } _GEN_64;
      automatic logic [4:0] _GEN_65;
      _GEN_58 =
        io.in.fromRob.blocks[3'h3].valid
          ? io.in.fromRob.blocks[3'h3].bits.tracePipe.ilastsize
          : s1_out_blocks_3_bits_r.tracePipe.ilastsize;
      _GEN_59 =
        io.in.fromRob.blocks[3'h3].valid
          ? io.in.fromRob.blocks[3'h3].bits.tracePipe.iretire
          : s1_out_blocks_3_bits_r.tracePipe.iretire;
      _GEN_60 =
        io.in.fromRob.blocks[3'h3].valid
          ? io.in.fromRob.blocks[3'h3].bits.tracePipe.itype
          : s1_out_blocks_3_bits_r.tracePipe.itype;
      _GEN_61 = '{itype: _GEN_60, iretire: _GEN_59, ilastsize: _GEN_58};
      _GEN_62 =
        io.in.fromRob.blocks[3'h3].valid
          ? io.in.fromRob.blocks[3'h3].bits.ftqIdx.value
          : s1_out_blocks_3_bits_r.ftqIdx.value;
      _GEN_63 =
        io.in.fromRob.blocks[3'h3].valid
          ? io.in.fromRob.blocks[3'h3].bits.ftqIdx.flag
          : s1_out_blocks_3_bits_r.ftqIdx.flag;
      _GEN_64 = '{flag: _GEN_63, value: _GEN_62};
      _GEN_65 =
        io.in.fromRob.blocks[3'h3].valid
          ? io.in.fromRob.blocks[3'h3].bits.ftqOffset
          : s1_out_blocks_3_bits_r.ftqOffset;
      s1_out_blocks_3_bits_r <=
        '{ftqIdx: _GEN_64, ftqOffset: _GEN_65, tracePipe: _GEN_61};
    end
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      s1_out_blocks_4_valid_r <= 1'h0;
    else if (blockCommit) begin
    end
    else
      s1_out_blocks_4_valid_r <= io.in.fromRob.blocks[3'h4].valid;
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      s1_out_blocks_4_bits_r <=
        '{ftqIdx: '{flag: 1'h0, value: 6'h0},
          ftqOffset: 5'h0,
          tracePipe: '{itype: 4'h0, iretire: 5'h0, ilastsize: 1'h0}};
    else begin
      automatic logic       _GEN_66;
      automatic logic [4:0] _GEN_67;
      automatic logic [3:0] _GEN_68;
      automatic
        struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } _GEN_69;
      automatic logic [5:0] _GEN_70;
      automatic logic       _GEN_71;
      automatic       struct packed {logic flag; logic [5:0] value; } _GEN_72;
      automatic logic [4:0] _GEN_73;
      _GEN_66 =
        io.in.fromRob.blocks[3'h4].valid
          ? io.in.fromRob.blocks[3'h4].bits.tracePipe.ilastsize
          : s1_out_blocks_4_bits_r.tracePipe.ilastsize;
      _GEN_67 =
        io.in.fromRob.blocks[3'h4].valid
          ? io.in.fromRob.blocks[3'h4].bits.tracePipe.iretire
          : s1_out_blocks_4_bits_r.tracePipe.iretire;
      _GEN_68 =
        io.in.fromRob.blocks[3'h4].valid
          ? io.in.fromRob.blocks[3'h4].bits.tracePipe.itype
          : s1_out_blocks_4_bits_r.tracePipe.itype;
      _GEN_69 = '{itype: _GEN_68, iretire: _GEN_67, ilastsize: _GEN_66};
      _GEN_70 =
        io.in.fromRob.blocks[3'h4].valid
          ? io.in.fromRob.blocks[3'h4].bits.ftqIdx.value
          : s1_out_blocks_4_bits_r.ftqIdx.value;
      _GEN_71 =
        io.in.fromRob.blocks[3'h4].valid
          ? io.in.fromRob.blocks[3'h4].bits.ftqIdx.flag
          : s1_out_blocks_4_bits_r.ftqIdx.flag;
      _GEN_72 = '{flag: _GEN_71, value: _GEN_70};
      _GEN_73 =
        io.in.fromRob.blocks[3'h4].valid
          ? io.in.fromRob.blocks[3'h4].bits.ftqOffset
          : s1_out_blocks_4_bits_r.ftqOffset;
      s1_out_blocks_4_bits_r <=
        '{ftqIdx: _GEN_72, ftqOffset: _GEN_73, tracePipe: _GEN_69};
    end
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      s1_out_blocks_5_valid_r <= 1'h0;
    else if (blockCommit) begin
    end
    else
      s1_out_blocks_5_valid_r <= io.in.fromRob.blocks[3'h5].valid;
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      s1_out_blocks_5_bits_r <=
        '{ftqIdx: '{flag: 1'h0, value: 6'h0},
          ftqOffset: 5'h0,
          tracePipe: '{itype: 4'h0, iretire: 5'h0, ilastsize: 1'h0}};
    else begin
      automatic logic       _GEN_74;
      automatic logic [4:0] _GEN_75;
      automatic logic [3:0] _GEN_76;
      automatic
        struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } _GEN_77;
      automatic logic [5:0] _GEN_78;
      automatic logic       _GEN_79;
      automatic       struct packed {logic flag; logic [5:0] value; } _GEN_80;
      automatic logic [4:0] _GEN_81;
      _GEN_74 =
        io.in.fromRob.blocks[3'h5].valid
          ? io.in.fromRob.blocks[3'h5].bits.tracePipe.ilastsize
          : s1_out_blocks_5_bits_r.tracePipe.ilastsize;
      _GEN_75 =
        io.in.fromRob.blocks[3'h5].valid
          ? io.in.fromRob.blocks[3'h5].bits.tracePipe.iretire
          : s1_out_blocks_5_bits_r.tracePipe.iretire;
      _GEN_76 =
        io.in.fromRob.blocks[3'h5].valid
          ? io.in.fromRob.blocks[3'h5].bits.tracePipe.itype
          : s1_out_blocks_5_bits_r.tracePipe.itype;
      _GEN_77 = '{itype: _GEN_76, iretire: _GEN_75, ilastsize: _GEN_74};
      _GEN_78 =
        io.in.fromRob.blocks[3'h5].valid
          ? io.in.fromRob.blocks[3'h5].bits.ftqIdx.value
          : s1_out_blocks_5_bits_r.ftqIdx.value;
      _GEN_79 =
        io.in.fromRob.blocks[3'h5].valid
          ? io.in.fromRob.blocks[3'h5].bits.ftqIdx.flag
          : s1_out_blocks_5_bits_r.ftqIdx.flag;
      _GEN_80 = '{flag: _GEN_79, value: _GEN_78};
      _GEN_81 =
        io.in.fromRob.blocks[3'h5].valid
          ? io.in.fromRob.blocks[3'h5].bits.ftqOffset
          : s1_out_blocks_5_bits_r.ftqOffset;
      s1_out_blocks_5_bits_r <=
        '{ftqIdx: _GEN_80, ftqOffset: _GEN_81, tracePipe: _GEN_77};
    end
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      s1_out_blocks_6_valid_r <= 1'h0;
    else if (blockCommit) begin
    end
    else
      s1_out_blocks_6_valid_r <= io.in.fromRob.blocks[3'h6].valid;
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      s1_out_blocks_6_bits_r <=
        '{ftqIdx: '{flag: 1'h0, value: 6'h0},
          ftqOffset: 5'h0,
          tracePipe: '{itype: 4'h0, iretire: 5'h0, ilastsize: 1'h0}};
    else begin
      automatic logic       _GEN_82;
      automatic logic [4:0] _GEN_83;
      automatic logic [3:0] _GEN_84;
      automatic
        struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } _GEN_85;
      automatic logic [5:0] _GEN_86;
      automatic logic       _GEN_87;
      automatic       struct packed {logic flag; logic [5:0] value; } _GEN_88;
      automatic logic [4:0] _GEN_89;
      _GEN_82 =
        io.in.fromRob.blocks[3'h6].valid
          ? io.in.fromRob.blocks[3'h6].bits.tracePipe.ilastsize
          : s1_out_blocks_6_bits_r.tracePipe.ilastsize;
      _GEN_83 =
        io.in.fromRob.blocks[3'h6].valid
          ? io.in.fromRob.blocks[3'h6].bits.tracePipe.iretire
          : s1_out_blocks_6_bits_r.tracePipe.iretire;
      _GEN_84 =
        io.in.fromRob.blocks[3'h6].valid
          ? io.in.fromRob.blocks[3'h6].bits.tracePipe.itype
          : s1_out_blocks_6_bits_r.tracePipe.itype;
      _GEN_85 = '{itype: _GEN_84, iretire: _GEN_83, ilastsize: _GEN_82};
      _GEN_86 =
        io.in.fromRob.blocks[3'h6].valid
          ? io.in.fromRob.blocks[3'h6].bits.ftqIdx.value
          : s1_out_blocks_6_bits_r.ftqIdx.value;
      _GEN_87 =
        io.in.fromRob.blocks[3'h6].valid
          ? io.in.fromRob.blocks[3'h6].bits.ftqIdx.flag
          : s1_out_blocks_6_bits_r.ftqIdx.flag;
      _GEN_88 = '{flag: _GEN_87, value: _GEN_86};
      _GEN_89 =
        io.in.fromRob.blocks[3'h6].valid
          ? io.in.fromRob.blocks[3'h6].bits.ftqOffset
          : s1_out_blocks_6_bits_r.ftqOffset;
      s1_out_blocks_6_bits_r <=
        '{ftqIdx: _GEN_88, ftqOffset: _GEN_89, tracePipe: _GEN_85};
    end
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      s1_out_blocks_7_valid_r <= 1'h0;
    else if (blockCommit) begin
    end
    else
      s1_out_blocks_7_valid_r <= io.in.fromRob.blocks[3'h7].valid;
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      s1_out_blocks_7_bits_r <=
        '{ftqIdx: '{flag: 1'h0, value: 6'h0},
          ftqOffset: 5'h0,
          tracePipe: '{itype: 4'h0, iretire: 5'h0, ilastsize: 1'h0}};
    else begin
      automatic logic       _GEN_90;
      automatic logic [4:0] _GEN_91;
      automatic logic [3:0] _GEN_92;
      automatic
        struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } _GEN_93;
      automatic logic [5:0] _GEN_94;
      automatic logic       _GEN_95;
      automatic       struct packed {logic flag; logic [5:0] value; } _GEN_96;
      automatic logic [4:0] _GEN_97;
      _GEN_90 =
        io.in.fromRob.blocks[3'h7].valid
          ? io.in.fromRob.blocks[3'h7].bits.tracePipe.ilastsize
          : s1_out_blocks_7_bits_r.tracePipe.ilastsize;
      _GEN_91 =
        io.in.fromRob.blocks[3'h7].valid
          ? io.in.fromRob.blocks[3'h7].bits.tracePipe.iretire
          : s1_out_blocks_7_bits_r.tracePipe.iretire;
      _GEN_92 =
        io.in.fromRob.blocks[3'h7].valid
          ? io.in.fromRob.blocks[3'h7].bits.tracePipe.itype
          : s1_out_blocks_7_bits_r.tracePipe.itype;
      _GEN_93 = '{itype: _GEN_92, iretire: _GEN_91, ilastsize: _GEN_90};
      _GEN_94 =
        io.in.fromRob.blocks[3'h7].valid
          ? io.in.fromRob.blocks[3'h7].bits.ftqIdx.value
          : s1_out_blocks_7_bits_r.ftqIdx.value;
      _GEN_95 =
        io.in.fromRob.blocks[3'h7].valid
          ? io.in.fromRob.blocks[3'h7].bits.ftqIdx.flag
          : s1_out_blocks_7_bits_r.ftqIdx.flag;
      _GEN_96 = '{flag: _GEN_95, value: _GEN_94};
      _GEN_97 =
        io.in.fromRob.blocks[3'h7].valid
          ? io.in.fromRob.blocks[3'h7].bits.ftqOffset
          : s1_out_blocks_7_bits_r.ftqOffset;
      s1_out_blocks_7_bits_r <=
        '{ftqIdx: _GEN_96, ftqOffset: _GEN_97, tracePipe: _GEN_93};
    end
  end // always @(posedge, posedge)
  always @(posedge clock)
    s3_out_groups <= _traceBuffer_io_out.groups;
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        automatic
          struct packed {struct packed {logic flag; logic [5:0] value; } ftqIdx; logic [4:0] ftqOffset; struct packed {logic [3:0] itype; logic [4:0] iretire; logic ilastsize; } tracePipe; }
          _s1_out_blocks_0_bits_r_WIRE =
          '{ftqIdx: '{flag: 1'h0, value: 6'h0},
            ftqOffset: 5'h0,
            tracePipe: '{itype: 4'h0, iretire: 5'h0, ilastsize: 1'h0}};
        s1_out_blocks_0_valid_r = 1'h0;
        s1_out_blocks_0_bits_r = _s1_out_blocks_0_bits_r_WIRE;
        s1_out_blocks_1_valid_r = 1'h0;
        s1_out_blocks_1_bits_r = _s1_out_blocks_0_bits_r_WIRE;
        s1_out_blocks_2_valid_r = 1'h0;
        s1_out_blocks_2_bits_r = _s1_out_blocks_0_bits_r_WIRE;
        s1_out_blocks_3_valid_r = 1'h0;
        s1_out_blocks_3_bits_r = _s1_out_blocks_0_bits_r_WIRE;
        s1_out_blocks_4_valid_r = 1'h0;
        s1_out_blocks_4_bits_r = _s1_out_blocks_0_bits_r_WIRE;
        s1_out_blocks_5_valid_r = 1'h0;
        s1_out_blocks_5_bits_r = _s1_out_blocks_0_bits_r_WIRE;
        s1_out_blocks_6_valid_r = 1'h0;
        s1_out_blocks_6_bits_r = _s1_out_blocks_0_bits_r_WIRE;
        s1_out_blocks_7_valid_r = 1'h0;
        s1_out_blocks_7_bits_r = _s1_out_blocks_0_bits_r_WIRE;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TraceBuffer traceBuffer (
    .clock             (clock),
    .reset             (reset),
    .io_in_fromEncoder (io.in.fromEncoder),
    .io_in_fromRob     (_GEN_32),
    .io_out            (_traceBuffer_io_out)
  );
  assign io_out = io.out;
endmodule

