// Generated by CIRCT firtool-1.150.2
module VecExceptionGen(
  input  [31:0]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      io_inst,
  input  struct packed {logic [9:0] foldpc; struct packed {logic _22; logic _20; logic _19; logic _12; logic _3; logic _2; logic _1; } exceptionVec; logic isFetchMalAddr; logic [3:0] trigger; logic isRVC; logic fixedTaken; logic predTaken; logic crossPageIPFFix; struct packed {logic flag; logic [5:0] value; } ftqPtr; logic [4:0] ftqOffset; logic isLastInFtqEntry; logic [31:0] instr; logic [1:0] commitType; logic [3:0][3:0] srcType; logic vlRen; logic [3:0][5:0] lsrc; logic [5:0] ldest; logic [35:0] fuType; logic [8:0] fuOpType; logic rfWen; logic fpWen; logic vecWen; logic v0Wen; logic vlWen; logic waitForward; logic blockBackward; logic flushPipe; logic canRobCompress; logic [3:0] selImm; logic [31:0] imm; struct packed {logic wflags; logic [1:0] fmt; logic [2:0] rm; } fpu; struct packed {logic vill; logic vma; logic vta; logic [1:0] vsew; logic [2:0] vlmul; logic specVill; logic specVma; logic specVta; logic [1:0] specVsew; logic [2:0] specVlmul; logic vm; logic [7:0] vstart; logic [2:0] frm; struct packed {logic isFpToVecInst; logic isFP32Instr; logic isFP64Instr; logic isReduction; logic isFoldTo1_2; logic isFoldTo1_4; logic isFoldTo1_8; } fpu; logic [1:0] vxrm; logic [6:0] vuopIdx; logic lastUop; logic [127:0] vmask; logic [7:0] vl; logic [2:0] nf; logic [1:0] veew; logic isReverse; logic isExt; logic isNarrow; logic isDstMask; logic isOpMask; logic isMove; logic isDependOldVd; logic isWritePartVd; logic isVleff; logic [15:0] maskVecGen; logic sew8; logic sew16; logic sew32; logic sew64; } vpu; logic vlsInstr; logic wfflags; logic isMove; logic [6:0] uopIdx; logic [5:0] uopSplitType; logic isVset; logic firstUop; logic lastUop; logic [6:0] numWB; struct packed {logic scalaNeedFrm; logic vectorNeedFrm; } needFrm; } io_decodedInst,
  input  struct packed {logic illegal; logic vma; logic vta; logic [1:0] vsew; logic [2:0] vlmul; }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  io_vtype,
  input  [7:0]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       io_vstart,
  output                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             io_illegalInst
);

  wire
    struct packed {logic [31:0] inst; struct packed {logic [9:0] foldpc; struct packed {logic _22; logic _20; logic _19; logic _12; logic _3; logic _2; logic _1; } exceptionVec; logic isFetchMalAddr; logic [3:0] trigger; logic isRVC; logic fixedTaken; logic predTaken; logic crossPageIPFFix; struct packed {logic flag; logic [5:0] value; } ftqPtr; logic [4:0] ftqOffset; logic isLastInFtqEntry; logic [31:0] instr; logic [1:0] commitType; logic [3:0][3:0] srcType; logic vlRen; logic [3:0][5:0] lsrc; logic [5:0] ldest; logic [35:0] fuType; logic [8:0] fuOpType; logic rfWen; logic fpWen; logic vecWen; logic v0Wen; logic vlWen; logic waitForward; logic blockBackward; logic flushPipe; logic canRobCompress; logic [3:0] selImm; logic [31:0] imm; struct packed {logic wflags; logic [1:0] fmt; logic [2:0] rm; } fpu; struct packed {logic vill; logic vma; logic vta; logic [1:0] vsew; logic [2:0] vlmul; logic specVill; logic specVma; logic specVta; logic [1:0] specVsew; logic [2:0] specVlmul; logic vm; logic [7:0] vstart; logic [2:0] frm; struct packed {logic isFpToVecInst; logic isFP32Instr; logic isFP64Instr; logic isReduction; logic isFoldTo1_2; logic isFoldTo1_4; logic isFoldTo1_8; } fpu; logic [1:0] vxrm; logic [6:0] vuopIdx; logic lastUop; logic [127:0] vmask; logic [7:0] vl; logic [2:0] nf; logic [1:0] veew; logic isReverse; logic isExt; logic isNarrow; logic isDstMask; logic isOpMask; logic isMove; logic isDependOldVd; logic isWritePartVd; logic isVleff; logic [15:0] maskVecGen; logic sew8; logic sew16; logic sew32; logic sew64; } vpu; logic vlsInstr; logic wfflags; logic isMove; logic [6:0] uopIdx; logic [5:0] uopSplitType; logic isVset; logic firstUop; logic lastUop; logic [6:0] numWB; struct packed {logic scalaNeedFrm; logic vectorNeedFrm; } needFrm; } decodedInst; struct packed {logic illegal; logic vma; logic vta; logic [1:0] vsew; logic [2:0] vlmul; } vtype; logic [7:0] vstart; logic illegalInst; }
    io;
  wire [1:0]  SEW = io.vtype.vsew;
  wire struct packed {logic [31:0] inst; } inst;
  assign inst = '{inst: io.inst};
  wire        isVArithMem =
    io.decodedInst.fuType[19] | io.decodedInst.fuType[20] | io.decodedInst.fuType[21]
    | io.decodedInst.fuType[22] | io.decodedInst.fuType[23] | io.decodedInst.fuType[24]
    | io.decodedInst.fuType[26] | io.decodedInst.fuType[27] | io.decodedInst.fuType[28]
    | io.decodedInst.fuType[32] | io.decodedInst.fuType[33] | io.decodedInst.fuType[34]
    | io.decodedInst.fuType[35];
  wire        isVArith =
    io.decodedInst.fuType[19] | io.decodedInst.fuType[20] | io.decodedInst.fuType[21]
    | io.decodedInst.fuType[22] | io.decodedInst.fuType[23] | io.decodedInst.fuType[24]
    | io.decodedInst.fuType[26] | io.decodedInst.fuType[27] | io.decodedInst.fuType[28];
  wire        isVset =
    io.decodedInst.fuType[29] | io.decodedInst.fuType[30] | io.decodedInst.fuType[31];
  wire        isVall =
    io.decodedInst.fuType[29] | io.decodedInst.fuType[30] | io.decodedInst.fuType[31]
    | io.decodedInst.fuType[19] | io.decodedInst.fuType[20] | io.decodedInst.fuType[21]
    | io.decodedInst.fuType[22] | io.decodedInst.fuType[23] | io.decodedInst.fuType[24]
    | io.decodedInst.fuType[26] | io.decodedInst.fuType[27] | io.decodedInst.fuType[28]
    | io.decodedInst.fuType[32] | io.decodedInst.fuType[33] | io.decodedInst.fuType[34]
    | io.decodedInst.fuType[35] | io.decodedInst.fuType[25];
  wire [2:0]  LMUL = {~(io.vtype.vlmul[2]), io.vtype.vlmul[1:0]};
  wire [17:0] _GEN =
    {inst.inst[28:26], inst.inst[24:20], inst.inst[14:12], inst.inst[6:0]};
  wire [12:0] _GEN_0 = {inst.inst[28:26], inst.inst[14:12], inst.inst[6:0]};
  wire        lsStrideInst =
    _GEN == 18'h7 | _GEN == 18'h287 | _GEN == 18'h307 | _GEN == 18'h387 | _GEN == 18'h27
    | _GEN == 18'h2A7 | _GEN == 18'h327 | _GEN == 18'h3A7 | _GEN_0 == 13'h807
    | _GEN_0 == 13'hA87 | _GEN_0 == 13'hB07 | _GEN_0 == 13'hB87 | _GEN_0 == 13'h827
    | _GEN_0 == 13'hAA7 | _GEN_0 == 13'hB27 | _GEN_0 == 13'hBA7 | _GEN == 18'h4007
    | _GEN == 18'h4287 | _GEN == 18'h4307 | _GEN == 18'h4387;
  wire [21:0] _GEN_1 = {inst.inst[31:20], inst.inst[14:12], inst.inst[6:0]};
  wire        lsMaskInst = _GEN_1 == 22'hAC07 | _GEN_1 == 22'hAC27;
  wire        lsIndexInst =
    _GEN_0 == 13'h407 | _GEN_0 == 13'h687 | _GEN_0 == 13'h707 | _GEN_0 == 13'h787
    | _GEN_0 == 13'hC07 | _GEN_0 == 13'hE87 | _GEN_0 == 13'hF07 | _GEN_0 == 13'hF87
    | _GEN_0 == 13'h427 | _GEN_0 == 13'h6A7 | _GEN_0 == 13'h727 | _GEN_0 == 13'h7A7
    | _GEN_0 == 13'hC27 | _GEN_0 == 13'hEA7 | _GEN_0 == 13'hF27 | _GEN_0 == 13'hFA7;
  wire        lsWholeInst =
    _GEN_1 == 22'hA007 | _GEN_1 == 22'hA287 | _GEN_1 == 22'hA307 | _GEN_1 == 22'hA387
    | _GEN_1 == 22'h8A007 | _GEN_1 == 22'h8A287 | _GEN_1 == 22'h8A307
    | _GEN_1 == 22'h8A387 | _GEN_1 == 22'h18A007 | _GEN_1 == 22'h18A287
    | _GEN_1 == 22'h18A307 | _GEN_1 == 22'h18A387 | _GEN_1 == 22'h38A007
    | _GEN_1 == 22'h38A287 | _GEN_1 == 22'h38A307 | _GEN_1 == 22'h38A387
    | _GEN_1 == 22'hA027 | _GEN_1 == 22'h8A027 | _GEN_1 == 22'h18A027
    | _GEN_1 == 22'h38A027;
  wire [15:0] _GEN_2 = {inst.inst[31:26], inst.inst[14:12], inst.inst[6:0]};
  wire [20:0] _GEN_3 = {inst.inst[31:26], inst.inst[19:12], inst.inst[6:0]};
  wire        vdWideningInst =
    _GEN_2 == 16'hC557 | _GEN_2 == 16'hC757 | _GEN_2 == 16'hD557 | _GEN_2 == 16'hD757
    | _GEN_2 == 16'hC157 | _GEN_2 == 16'hC357 | _GEN_2 == 16'hD157 | _GEN_2 == 16'hD357
    | _GEN_2 == 16'hF557 | _GEN_2 == 16'hF757 | _GEN_2 == 16'hFD57 | _GEN_2 == 16'hFF57
    | _GEN_2 == 16'hF157 | _GEN_2 == 16'hF357 | _GEN_2 == 16'hFB57 | _GEN_2 == 16'hED57
    | _GEN_2 == 16'hEF57 | _GEN_2 == 16'hE957 | _GEN_2 == 16'hEB57 | _GEN_2 == 16'hE157
    | _GEN_2 == 16'hE357 | _GEN_2 == 16'hCD57 | _GEN_2 == 16'hCF57 | _GEN_2 == 16'hDD57
    | _GEN_2 == 16'hDF57 | _GEN_2 == 16'hC957 | _GEN_2 == 16'hCB57 | _GEN_2 == 16'hD957
    | _GEN_2 == 16'hDB57 | _GEN_2 == 16'hC2D7 | _GEN_2 == 16'hC0D7 | _GEN_2 == 16'hD2D7
    | _GEN_2 == 16'hD0D7 | _GEN_2 == 16'hCAD7 | _GEN_2 == 16'hC8D7 | _GEN_2 == 16'hDAD7
    | _GEN_2 == 16'hD8D7 | _GEN_2 == 16'hE2D7 | _GEN_2 == 16'hE0D7 | _GEN_2 == 16'hF2D7
    | _GEN_2 == 16'hF0D7 | _GEN_2 == 16'hFAD7 | _GEN_2 == 16'hF8D7 | _GEN_2 == 16'hF6D7
    | _GEN_2 == 16'hF4D7 | _GEN_2 == 16'hFED7 | _GEN_2 == 16'hFCD7 | _GEN_3 == 21'h930D7
    | _GEN_3 == 21'h92CD7 | _GEN_3 == 21'h928D7 | _GEN_3 == 21'h93CD7
    | _GEN_3 == 21'h938D7 | _GEN_3 == 21'h924D7 | _GEN_3 == 21'h920D7 | _GEN_2 == 16'hD457
    | _GEN_2 == 16'hD657 | _GEN_2 == 16'hD5D7;
  wire        vs2WideningInst =
    _GEN_2 == 16'hD557 | _GEN_2 == 16'hD757 | _GEN_2 == 16'hD157 | _GEN_2 == 16'hD357
    | _GEN_2 == 16'hDD57 | _GEN_2 == 16'hDF57 | _GEN_2 == 16'hD957 | _GEN_2 == 16'hDB57
    | _GEN_2 == 16'hD2D7 | _GEN_2 == 16'hD0D7 | _GEN_2 == 16'hDAD7 | _GEN_2 == 16'hD8D7;
  wire        narrowingInst =
    _GEN_2 == 16'hBDD7 | _GEN_2 == 16'hBC57 | _GEN_2 == 16'hBE57 | _GEN_2 == 16'hB9D7
    | _GEN_2 == 16'hB857 | _GEN_2 == 16'hBA57 | _GEN_2 == 16'hB5D7 | _GEN_2 == 16'hB457
    | _GEN_2 == 16'hB657 | _GEN_2 == 16'hB1D7 | _GEN_2 == 16'hB057 | _GEN_2 == 16'hB257
    | _GEN_3 == 21'h950D7 | _GEN_3 == 21'h94CD7 | _GEN_3 == 21'h948D7
    | _GEN_3 == 21'h954D7 | _GEN_3 == 21'h95CD7 | _GEN_3 == 21'h958D7
    | _GEN_3 == 21'h944D7 | _GEN_3 == 21'h940D7;
  wire        intExtInst =
    _GEN_3 == 21'h91D57 | _GEN_3 == 21'h91557 | _GEN_3 == 21'h90D57 | _GEN_3 == 21'h91957
    | _GEN_3 == 21'h91157 | _GEN_3 == 21'h90957;
  wire [16:0] _GEN_4 = {inst.inst[31:25], inst.inst[14:12], inst.inst[6:0]};
  wire        acsbInst =
    _GEN_4 == 17'h8DD7 | _GEN_4 == 17'h89D7 | _GEN_4 == 17'h8C57 | _GEN_4 == 17'h8857
    | _GEN_4 == 17'h8E57 | _GEN_4 == 17'h8A57 | _GEN_4 == 17'h9C57 | _GEN_4 == 17'h9857
    | _GEN_4 == 17'h9E57 | _GEN_4 == 17'h9A57;
  wire        cmpInst =
    _GEN_2 == 16'h61D7 | _GEN_2 == 16'h6057 | _GEN_2 == 16'h6257 | _GEN_2 == 16'h7DD7
    | _GEN_2 == 16'h7E57 | _GEN_2 == 16'h79D7 | _GEN_2 == 16'h7A57 | _GEN_2 == 16'h75D7
    | _GEN_2 == 16'h7457 | _GEN_2 == 16'h7657 | _GEN_2 == 16'h71D7 | _GEN_2 == 16'h7057
    | _GEN_2 == 16'h7257 | _GEN_2 == 16'h6C57 | _GEN_2 == 16'h6E57 | _GEN_2 == 16'h6857
    | _GEN_2 == 16'h6A57 | _GEN_2 == 16'h65D7 | _GEN_2 == 16'h6457 | _GEN_2 == 16'h6657
    | _GEN_2 == 16'h62D7 | _GEN_2 == 16'h60D7 | _GEN_2 == 16'h72D7 | _GEN_2 == 16'h70D7
    | _GEN_2 == 16'h7ED7 | _GEN_2 == 16'h76D7 | _GEN_2 == 16'h66D7 | _GEN_2 == 16'h64D7
    | _GEN_2 == 16'h6ED7 | _GEN_2 == 16'h6CD7;
  wire        redInst =
    _GEN_2 == 16'h557 | _GEN_2 == 16'h1D57 | _GEN_2 == 16'h1957 | _GEN_2 == 16'h1557
    | _GEN_2 == 16'h1157 | _GEN_2 == 16'h957 | _GEN_2 == 16'h157 | _GEN_2 == 16'hD57
    | _GEN_2 == 16'h1CD7 | _GEN_2 == 16'h14D7 | _GEN_2 == 16'hCD7 | _GEN_2 == 16'h4D7;
  wire        redWideningInst =
    _GEN_2 == 16'hC457 | _GEN_2 == 16'hC057 | _GEN_2 == 16'hCCD7 | _GEN_2 == 16'hC4D7;
  wire        maskLogicalInst =
    _GEN_4 == 17'hCD57 | _GEN_4 == 17'hED57 | _GEN_4 == 17'hC557 | _GEN_4 == 17'hDD57
    | _GEN_4 == 17'hD557 | _GEN_4 == 17'hF557 | _GEN_4 == 17'hE557 | _GEN_4 == 17'hFD57;
  wire        maskArithmeticInst =
    _GEN_3 == 21'h84157 | _GEN_3 == 21'h84557 | _GEN_3 == 21'hA0557 | _GEN_3 == 21'hA0D57
    | _GEN_3 == 21'hA0957 | maskLogicalInst;
  wire        maskIndexInst =
    _GEN_3 == 21'hA4157
    | {inst.inst[31:26], inst.inst[24:12], inst.inst[6:0]} == 26'h1404557;
  wire [21:0] _GEN_5 = {inst.inst[31:25], inst.inst[19:12], inst.inst[6:0]};
  wire        vmvSingleInst =
    _GEN_5 == 22'h108157 | _GEN_1 == 22'h108357 | _GEN_5 == 22'h1080D7
    | _GEN_1 == 22'h1082D7;
  wire        vmvWholeInst =
    _GEN_5 == 22'h2781D7 | _GEN_5 == 22'h2785D7 | _GEN_5 == 22'h278DD7
    | _GEN_5 == 22'h279DD7;
  wire        vsetInst =
    {inst.inst[31], inst.inst[14:12], inst.inst[6:0]} == 11'h3D7
    | {inst.inst[31:30], inst.inst[14:12], inst.inst[6:0]} == 12'hFD7
    | _GEN_4 == 17'h103D7;
  wire        vrgather16 = _GEN_2 == 16'h3857;
  wire        vcompress = _GEN_4 == 17'hBD57;
  wire        intExt2 = _GEN_3 == 21'h91D57 | _GEN_3 == 21'h91957;
  wire        intExt4 = _GEN_3 == 21'h91557 | _GEN_3 == 21'h91157;
  wire        intExt8 = _GEN_3 == 21'h90D57 | _GEN_3 == 21'h90957;
  wire        notDependVtypeInst = vsetInst | lsWholeInst;
  wire        instIllegal = maskLogicalInst & ~(inst.inst[25]);
  wire        villIllegal = io.vtype.illegal & isVall & ~notDependVtypeInst;
  wire        doubleFpInst =
    _GEN_3 == 21'h92CD7 | _GEN_3 == 21'h928D7 | _GEN_3 == 21'h95CD7 | _GEN_3 == 21'h958D7
    | _GEN_3 == 21'h944D7 | _GEN_3 == 21'h940D7;
  wire        isFp = inst.inst[13:12] == 2'h1 & inst.inst[6:0] == 7'h57;
  wire        _intExtEewIllegal_T = SEW == 2'h0;
  wire        fpEewIllegal = isFp & _intExtEewIllegal_T & ~doubleFpInst;
  wire        intExtEewIllegal =
    intExt2 & _intExtEewIllegal_T | intExt4 & ~(SEW[1]) | intExt8 & SEW != 2'h3;
  wire        _wnEmulIllegal_T = vdWideningInst | narrowingInst;
  wire        wnEewIllegal = (_wnEmulIllegal_T | redWideningInst) & (&SEW);
  wire        eewIllegal = fpEewIllegal | intExtEewIllegal | wnEewIllegal;
  wire        _vdRegHi_T = lsStrideInst | lsIndexInst;
  wire [3:0]  _GEN_6 = {1'h0, LMUL};
  wire [2:0]  _GEN_7 = {1'h0, SEW};
  wire [2:0]  _vdEew_T_3 = _GEN_7 + 3'h1;
  wire [3:0]  _GEN_8 = {2'h0, SEW};
  wire        lsEmulIllegal =
    _vdRegHi_T
    & (_GEN_6 + {2'h0, inst.inst[13:12]} < {1'h0, _vdEew_T_3} | _GEN_6
       + {2'h0, inst.inst[13:12]} > _GEN_8 + 4'h7);
  wire        intExtEmulIllegal =
    intExt2 & LMUL == 3'h1 | intExt4 & LMUL < 3'h3 | intExt8 & ~(LMUL[2]);
  wire        wnEmulIllegal = _wnEmulIllegal_T & (&LMUL);
  wire        gather16EmulIllegal = vrgather16 & (LMUL < _GEN_7 | _GEN_6 > _GEN_8 + 4'h6);
  wire [3:0]  NFIELDS = {1'h0, inst.inst[31:29]} + 4'h1;
  wire [3:0]  segEmul = lsIndexInst ? _GEN_6 : _GEN_6 + {2'h0, inst.inst[13:12]} - _GEN_8;
  wire [1:0]  emulNumPow = segEmul[2] ? segEmul[1:0] : 2'h0;
  wire [6:0]  segRegNum = {3'h0, NFIELDS} << emulNumPow;
  wire [4:0]  vdRegLo = inst.inst[11:7];
  wire [7:0]  segRegMax = {3'h0, vdRegLo} + {1'h0, segRegNum};
  wire        lsSegIllegal =
    _vdRegHi_T & (|(inst.inst[31:29])) & (segRegNum > 7'h8 | segRegMax > 8'h20);
  wire        emulIllegal =
    lsEmulIllegal | intExtEmulIllegal | wnEmulIllegal | gather16EmulIllegal
    | lsSegIllegal;
  wire        vs1IsMask = maskArithmeticInst | vcompress;
  wire        vs1IsSingleElem = redInst | redWideningInst;
  wire [1:0]  vs1Eew = vrgather16 ? 2'h1 : SEW;
  wire [3:0]  _vdEmul_T = _GEN_6 + 4'h1;
  wire [3:0]  _vs1Emul_T_4 = vrgather16 ? _vdEmul_T - _GEN_8 : _GEN_6;
  wire [3:0]  vs1Emul = vs1IsMask | vs1IsSingleElem ? 4'h4 : _vs1Emul_T_4;
  wire [4:0]  vs1RegLo = inst.inst[19:15];
  wire        vs1NotAlign =
    io.decodedInst.srcType[2'h0][2]
    & (vs1Emul == 4'h5 & inst.inst[15] | vs1Emul == 4'h6 & (|(inst.inst[16:15]))
       | vs1Emul == 4'h7 & (|(inst.inst[17:15])));
  wire        vs2IsMask = maskArithmeticInst | maskIndexInst;
  wire        _vs2EmulSel_T_1 = vs2WideningInst | narrowingInst;
  wire [4:0]  vs2EewSel =
    {lsIndexInst, _vs2EmulSel_T_1 | redWideningInst, intExt2, intExt4, intExt8};
  wire [1:0]  _vs2Eew_T_11 = vs2EewSel == 5'h10 ? inst.inst[13:12] : SEW;
  wire [1:0]  _vs2Eew_T_13 = vs2EewSel == 5'h8 ? _vdEew_T_3[1:0] : _vs2Eew_T_11;
  wire [1:0]  _vs2Eew_T_15 = vs2EewSel == 5'h4 ? SEW - 2'h1 : _vs2Eew_T_13;
  wire [1:0]  _vs2Eew_T_17 = vs2EewSel == 5'h2 ? SEW - 2'h2 : _vs2Eew_T_15;
  wire [1:0]  vs2Eew = vs2EewSel == 5'h1 ? SEW + 2'h1 : _vs2Eew_T_17;
  wire [3:0]  vs2EmulSel =
    {vs2IsMask | vmvSingleInst, _vs2EmulSel_T_1, vmvWholeInst, intExtInst | lsIndexInst};
  wire [2:0]  _vs2Emul_T_9 = inst.inst[17:15] == 3'h1 ? 3'h5 : 3'h0;
  wire [2:0]  _vs2Emul_T_10 = inst.inst[17:15] == 3'h3 ? 3'h6 : 3'h0;
  wire [2:0]  _vs2Emul_T_19 = vs2EmulSel == 4'h8 ? 3'h4 : LMUL;
  wire [2:0]  _vs2Emul_T_21 = vs2EmulSel == 4'h4 ? _vdEmul_T[2:0] : _vs2Emul_T_19;
  wire [2:0]  _vs2Emul_T_23 =
    vs2EmulSel == 4'h2
      ? {inst.inst[17:15] == 3'h0, 2'h0} | _vs2Emul_T_9 | _vs2Emul_T_10
        | {3{&(inst.inst[17:15])}}
      : _vs2Emul_T_21;
  wire [3:0]  vs2Emul =
    vs2EmulSel == 4'h1 ? _GEN_6 + {2'h0, vs2Eew} - _GEN_8 : {1'h0, _vs2Emul_T_23};
  wire [4:0]  vs2RegLo = inst.inst[24:20];
  wire        vs2NotAlign =
    io.decodedInst.srcType[2'h1][2]
    & (vs2Emul == 4'h5 & inst.inst[20] | vs2Emul == 4'h6 & (|(inst.inst[21:20]))
       | vs2Emul == 4'h7 & (|(inst.inst[22:20])));
  wire        vdIsMask = lsMaskInst | acsbInst | cmpInst | maskArithmeticInst;
  wire        vdIsSingleElem = vs1IsSingleElem | vmvSingleInst;
  wire [1:0]  _vdEew_T_5 = vdWideningInst | redWideningInst ? _vdEew_T_3[1:0] : SEW;
  wire [1:0]  vdEew = lsStrideInst ? inst.inst[13:12] : _vdEew_T_5;
  wire        _v0AllowOverlap_T = vdIsMask | vdIsSingleElem;
  wire [4:0]  vdEmulSel =
    {_v0AllowOverlap_T, vdWideningInst, vmvWholeInst, lsWholeInst, lsStrideInst};
  wire [2:0]  _vdEmul_T_9 = inst.inst[17:15] == 3'h1 ? 3'h5 : 3'h0;
  wire [2:0]  _vdEmul_T_10 = inst.inst[17:15] == 3'h3 ? 3'h6 : 3'h0;
  wire [2:0]  _vdEmul_T_21 = inst.inst[31:29] == 3'h1 ? 3'h5 : 3'h0;
  wire [2:0]  _vdEmul_T_22 = inst.inst[31:29] == 3'h3 ? 3'h6 : 3'h0;
  wire [2:0]  _vdEmul_T_31 = vdEmulSel == 5'h10 ? 3'h4 : LMUL;
  wire [2:0]  _vdEmul_T_33 = vdEmulSel == 5'h8 ? _vdEmul_T[2:0] : _vdEmul_T_31;
  wire [2:0]  _vdEmul_T_35 =
    vdEmulSel == 5'h4
      ? {inst.inst[17:15] == 3'h0, 2'h0} | _vdEmul_T_9 | _vdEmul_T_10
        | {3{&(inst.inst[17:15])}}
      : _vdEmul_T_33;
  wire [2:0]  _vdEmul_T_37 =
    vdEmulSel == 5'h2
      ? {inst.inst[31:29] == 3'h0, 2'h0} | _vdEmul_T_21 | _vdEmul_T_22
        | {3{&(inst.inst[31:29])}}
      : _vdEmul_T_35;
  wire [3:0]  vdEmul =
    vdEmulSel == 5'h1 ? _GEN_6 + {2'h0, vdEew} - _GEN_8 : {1'h0, _vdEmul_T_37};
  wire        vdNotAlign =
    (io.decodedInst.srcType[2'h2][2] | io.decodedInst.vecWen)
    & (vdEmul == 4'h5 & inst.inst[7] | vdEmul == 4'h6 & (|(inst.inst[8:7]))
       | vdEmul == 4'h7 & (|(inst.inst[9:7])));
  wire        regNumIllegal = isVArithMem & (vs1NotAlign | vs2NotAlign | vdNotAlign);
  wire        v0AllowOverlap =
    _v0AllowOverlap_T
    & ~(_GEN_3 == 21'hA0557 | _GEN_3 == 21'hA0D57 | _GEN_3 == 21'hA0957);
  wire        v0Overlap =
    isVArithMem & io.decodedInst.vecWen & ~(inst.inst[25]) & vdRegLo == 5'h0
    & ~v0AllowOverlap;
  wire [1:0]  vs1RegHi_numPow = vs1Emul[2] ? vs1Emul[1:0] : 2'h0;
  wire [3:0]  vs1RegHi_regNum = 4'h1 << vs1RegHi_numPow;
  wire [5:0]  vs1RegHi = {1'h0, vs1RegLo} + {2'h0, vs1RegHi_regNum} - 6'h1;
  wire [1:0]  vs2RegHi_numPow = vs2Emul[2] ? vs2Emul[1:0] : 2'h0;
  wire [3:0]  vs2RegHi_regNum = 4'h1 << vs2RegHi_numPow;
  wire [5:0]  vs2RegHi = {1'h0, vs2RegLo} + {2'h0, vs2RegHi_regNum} - 6'h1;
  wire [1:0]  vdRegHi_numPow = vdEmul[2] ? vdEmul[1:0] : 2'h0;
  wire [3:0]  vdRegHi_regNum = 4'h1 << vdRegHi_numPow;
  wire [7:0]  vdRegHi =
    _vdRegHi_T ? segRegMax - 8'h1 : {3'h0, vdRegLo + {1'h0, vdRegHi_regNum} - 5'h1};
  wire        notAllowOverlapInst =
    lsIndexInst & (|(inst.inst[31:29])) | _GEN_3 == 21'hA0557 | _GEN_3 == 21'hA0D57
    | _GEN_3 == 21'hA0957 | _GEN_3 == 21'hA4157 | _GEN_2 == 16'h3A57 | _GEN_2 == 16'h39D7
    | _GEN_2 == 16'h3B57 | _GEN_2 == 16'h3AD7 | _GEN_2 == 16'h3057 | _GEN_2 == 16'h3857
    | _GEN_2 == 16'h3257 | _GEN_2 == 16'h31D7 | _GEN_4 == 17'hBD57;
  wire        vstartIllegal = isVArith & (|io.vstart);
  wire [5:0]  _GEN_9 = {1'h0, vdRegLo};
  wire        vs1vdRegNotOverlap = vs1RegHi < _GEN_9 | vdRegHi < {3'h0, vs1RegLo};
  wire        vs1Constraint1 =
    vs1IsMask & vdIsMask | ~vs1IsMask & ~vdIsMask & vs1Eew == vdEew;
  wire [7:0]  _GEN_10 = {2'h0, vs1RegHi};
  wire        vs1Constraint2 =
    (vdIsMask & ~vs1IsMask | ~vs1IsMask & ~vdIsMask & vs1Eew > vdEew)
    & vdRegLo == vs1RegLo & vdRegHi <= _GEN_10;
  wire        vs1Constraint3 =
    (~vdIsMask & vs1IsMask | ~vs1IsMask & ~vdIsMask & vs1Eew < vdEew) & (|(vs1Emul[3:2]))
    & vdRegHi == _GEN_10 & vdRegLo <= vs1RegLo;
  wire        vs1AllowOverlap =
    (vs1Constraint1 | vs1Constraint2 | vs1Constraint3 | vdIsSingleElem)
    & ~notAllowOverlapInst;
  wire        vs1vdOverlap =
    io.decodedInst.srcType[2'h0][2] & io.decodedInst.vecWen & ~vs1vdRegNotOverlap
    & ~vs1AllowOverlap;
  wire        vs2vdRegNotOverlap = vs2RegHi < _GEN_9 | vdRegHi < {3'h0, vs2RegLo};
  wire        vs2Constraint1 =
    vs2IsMask & vdIsMask | ~vs2IsMask & ~vdIsMask & vs2Eew == vdEew;
  wire [7:0]  _GEN_11 = {2'h0, vs2RegHi};
  wire        vs2Constraint2 =
    (vdIsMask & ~vs2IsMask | ~vs2IsMask & ~vdIsMask & vs2Eew > vdEew)
    & vdRegLo == vs2RegLo & vdRegHi <= _GEN_11;
  wire        vs2Constraint3 =
    (~vdIsMask & vs2IsMask | ~vs2IsMask & ~vdIsMask & vs2Eew < vdEew) & (|(vs2Emul[3:2]))
    & vdRegHi == _GEN_11 & vdRegLo <= vs2RegLo;
  wire        vs2AllowOverlap =
    (vs2Constraint1 | vs2Constraint2 | vs2Constraint3 | vdIsSingleElem)
    & ~notAllowOverlapInst;
  wire        vs2vdOverlap =
    io.decodedInst.srcType[2'h1][2] & io.decodedInst.vecWen & ~vs2vdRegNotOverlap
    & ~vs2AllowOverlap;
  wire        regOverlapIllegal = v0Overlap | vs1vdOverlap | vs2vdOverlap;
  assign io =
    '{inst: io_inst,
      decodedInst: io_decodedInst,
      vtype: io_vtype,
      vstart: io_vstart,
      illegalInst:
        (instIllegal | villIllegal | eewIllegal | emulIllegal | regNumIllegal
         | regOverlapIllegal | vstartIllegal)};
  assign io_illegalInst = io.illegalInst;
endmodule

