// Generated by CIRCT firtool-1.150.2
module VIMac64bStage3(
  input  struct packed {logic [151:0] sumFinalNonFixPS2; logic [151:0] sumFinalFixPS2; logic highHalfS2; logic [5:0] uopIdxS2; logic widenS2; logic [1:0] vxrmS2; logic isFixPS2; logic sewIs8S2; logic sewIs16S2; logic sewIs32S2; logic sewIs64S2; } io_in,
  output struct packed {logic [63:0] vd; logic [7:0] vxsat; }                                                                                                                                                                                          io_out
);

  wire [63:0] vdFixP;
  wire [63:0] vdRndInc;
  wire [7:0]  rndIncVec;
  wire [7:0]  vxsat;
  wire [63:0] vdSat;
  wire [63:0] vdNonFixP;
  wire [63:0] _outputMux_io_vdOut;
  wire [7:0]  _outputMux_io_vxsatOut;
  wire
    struct packed {struct packed {logic [151:0] sumFinalNonFixPS2; logic [151:0] sumFinalFixPS2; logic highHalfS2; logic [5:0] uopIdxS2; logic widenS2; logic [1:0] vxrmS2; logic isFixPS2; logic sewIs8S2; logic sewIs16S2; logic sewIs32S2; logic sewIs64S2; } in; struct packed {logic [63:0] vd; logic [7:0] vxsat; } out; }
    io;
  wire struct packed {logic [63:0] vd; logic [7:0] vxsat; } _GEN =
    '{vd: _outputMux_io_vdOut, vxsat: _outputMux_io_vxsatOut};
  assign io = '{in: io_in, out: _GEN};
  vdNonFixPGenerator vdNonFixPGen (
    .io_sumFinalNonFixP (io.in.sumFinalNonFixPS2),
    .io_highHalf        (io.in.highHalfS2),
    .io_widen           (io.in.widenS2),
    .io_uopIdx          (io.in.uopIdxS2),
    .io_sewIs8          (io.in.sewIs8S2),
    .io_sewIs16         (io.in.sewIs16S2),
    .io_sewIs32         (io.in.sewIs32S2),
    .io_sewIs64         (io.in.sewIs64S2),
    .io_vdNonFixP       (vdNonFixP)
  );
  vxsatGenerator vxsatGen (
    .io_sumFinalNonFixP (io.in.sumFinalNonFixPS2),
    .io_sewIs8          (io.in.sewIs8S2),
    .io_sewIs16         (io.in.sewIs16S2),
    .io_sewIs32         (io.in.sewIs32S2),
    .io_sewIs64         (io.in.sewIs64S2),
    .io_vdSat           (vdSat),
    .io_vxsat           (vxsat)
  );
  rndIncVecGenerator rndIncVecGen (
    .io_sumFinalNonFixP (io.in.sumFinalNonFixPS2),
    .io_vxrm            (io.in.vxrmS2),
    .io_sewIs8          (io.in.sewIs8S2),
    .io_sewIs16         (io.in.sewIs16S2),
    .io_sewIs32         (io.in.sewIs32S2),
    .io_sewIs64         (io.in.sewIs64S2),
    .io_rndIncVec       (rndIncVec)
  );
  vdRndGenerator vdRndGen (
    .io_sumFinalFixP (io.in.sumFinalFixPS2),
    .io_sewIs8       (io.in.sewIs8S2),
    .io_sewIs16      (io.in.sewIs16S2),
    .io_sewIs32      (io.in.sewIs32S2),
    .io_sewIs64      (io.in.sewIs64S2),
    .io_vdRndInc     (vdRndInc)
  );
  vdFixPGenerator vdFixPGen (
    .io_vdRndInc  (vdRndInc),
    .io_vdSat     (vdSat),
    .io_rndIncVec (rndIncVec),
    .io_sewIs8    (io.in.sewIs8S2),
    .io_sewIs16   (io.in.sewIs16S2),
    .io_sewIs32   (io.in.sewIs32S2),
    .io_sewIs64   (io.in.sewIs64S2),
    .io_vdFixP    (vdFixP)
  );
  outputSelect outputMux (
    .io_vdNonFixP (vdNonFixP),
    .io_vdFixP    (vdFixP),
    .io_vxsat     (vxsat),
    .io_isFixP    (io.in.isFixPS2),
    .io_vdOut     (_outputMux_io_vdOut),
    .io_vxsatOut  (_outputMux_io_vxsatOut)
  );
  assign io_out = io.out;
endmodule

