// Generated by CIRCT firtool-1.150.2
module VIMac64bStage2(
  input  struct packed {logic [6:0][151:0] compStage1ResultsS1; logic [151:0] wallaceLine34NonFixPS1; logic [151:0] wallaceLine34FixPS1; logic highHalfS1; logic [5:0] uopIdxS1; logic widenS1; logic [1:0] vxrmS1; logic isFixPS1; logic sewIs8S1; logic sewIs16S1; logic sewIs32S1; logic sewIs64S1; } io_in,
  output struct packed {logic [151:0] sumFinalNonFixPS2; logic [151:0] sumFinalFixPS2; logic highHalfS2; logic [5:0] uopIdxS2; logic widenS2; logic [1:0] vxrmS2; logic isFixPS2; logic sewIs8S2; logic sewIs16S2; logic sewIs32S2; logic sewIs64S2; }                                                   io_out
);

  wire [151:0] cout34to2FixP;
  wire [151:0] sum34to2FixP;
  wire [151:0] cout34to2NonFixP;
  wire [151:0] sum34to2NonFixP;
  wire
    struct packed {struct packed {logic [6:0][151:0] compStage1ResultsS1; logic [151:0] wallaceLine34NonFixPS1; logic [151:0] wallaceLine34FixPS1; logic highHalfS1; logic [5:0] uopIdxS1; logic widenS1; logic [1:0] vxrmS1; logic isFixPS1; logic sewIs8S1; logic sewIs16S1; logic sewIs32S1; logic sewIs64S1; } in; struct packed {logic [151:0] sumFinalNonFixPS2; logic [151:0] sumFinalFixPS2; logic highHalfS2; logic [5:0] uopIdxS2; logic widenS2; logic [1:0] vxrmS2; logic isFixPS2; logic sewIs8S2; logic sewIs16S2; logic sewIs32S2; logic sewIs64S2; } out; }
    io;
  wire [151:0] sumFinalNonFixP;
  wire [151:0] sumFinalFixP;
  wire
    struct packed {logic [151:0] sumFinalNonFixPS2; logic [151:0] sumFinalFixPS2; logic highHalfS2; logic [5:0] uopIdxS2; logic widenS2; logic [1:0] vxrmS2; logic isFixPS2; logic sewIs8S2; logic sewIs16S2; logic sewIs32S2; logic sewIs64S2; }
    _GEN =
    '{sumFinalNonFixPS2: sumFinalNonFixP,
      sumFinalFixPS2: sumFinalFixP,
      highHalfS2: io.in.highHalfS1,
      uopIdxS2: io.in.uopIdxS1,
      widenS2: io.in.widenS1,
      vxrmS2: io.in.vxrmS1,
      isFixPS2: io.in.isFixPS1,
      sewIs8S2: io.in.sewIs8S1,
      sewIs16S2: io.in.sewIs16S1,
      sewIs32S2: io.in.sewIs32S1,
      sewIs64S2: io.in.sewIs64S1};
  assign io = '{in: io_in, out: _GEN};
  wallace3to2CompressorStage2 wallace3to2CompStage2 (
    .io_compStage1Results    (io.in.compStage1ResultsS1),
    .io_wallaceLine34NonFixP (io.in.wallaceLine34NonFixPS1),
    .io_wallaceLine34FixP    (io.in.wallaceLine34FixPS1),
    .io_sum34to2NonFixP      (sum34to2NonFixP),
    .io_cout34to2NonFixP     (cout34to2NonFixP),
    .io_sum34to2FixP         (sum34to2FixP),
    .io_cout34to2FixP        (cout34to2FixP)
  );
  fullAdder152b finalSumAdderNonFixP (
    .io_sum34to2  (sum34to2NonFixP),
    .io_cout34to2 (cout34to2NonFixP),
    .io_sumFinal  (sumFinalNonFixP)
  );
  fullAdder152b finalSumAdderFixP (
    .io_sum34to2  (sum34to2FixP),
    .io_cout34to2 (cout34to2FixP),
    .io_sumFinal  (sumFinalFixP)
  );
  assign io_out = io.out;
endmodule

