// Generated by CIRCT firtool-1.150.2
module vxsatGenerator(
  input  [151:0] io_sumFinalNonFixP,
  input          io_sewIs8,
                 io_sewIs16,
                 io_sewIs32,
                 io_sewIs64,
  output [63:0]  io_vdSat,
  output [7:0]   io_vxsat
);

  wire
    struct packed {logic [151:0] sumFinalNonFixP; logic sewIs8; logic sewIs16; logic sewIs32; logic sewIs64; logic [63:0] vdSat; logic [7:0] vxsat; }
    io;
  wire [7:0]  _vxsat_T_54 =
    io.sewIs8
      ? {io.sumFinalNonFixP[148:147] == 2'h1,
         io.sumFinalNonFixP[129:128] == 2'h1,
         io.sumFinalNonFixP[110:109] == 2'h1,
         io.sumFinalNonFixP[91:90] == 2'h1,
         io.sumFinalNonFixP[72:71] == 2'h1,
         io.sumFinalNonFixP[53:52] == 2'h1,
         io.sumFinalNonFixP[34:33] == 2'h1,
         io.sumFinalNonFixP[15:14] == 2'h1}
      : 8'h0;
  wire [7:0]  _vxsat_T_55 =
    io.sewIs16
      ? {{2{io.sumFinalNonFixP[145:144] == 2'h1}},
         {2{io.sumFinalNonFixP[107:106] == 2'h1}},
         {2{io.sumFinalNonFixP[69:68] == 2'h1}},
         {2{io.sumFinalNonFixP[31:30] == 2'h1}}}
      : 8'h0;
  wire [7:0]  _vxsat_T_56 =
    io.sewIs32
      ? {{4{io.sumFinalNonFixP[139:138] == 2'h1}}, {4{io.sumFinalNonFixP[63:62] == 2'h1}}}
      : 8'h0;
  wire [7:0]  vxsat =
    _vxsat_T_54 | _vxsat_T_55 | _vxsat_T_56
    | {8{io.sewIs64 & io.sumFinalNonFixP[127:126] == 2'h1}};
  wire [7:0]  _vdSat_T_25 = vxsat[7] ? 8'h7F : io.sumFinalNonFixP[147:140];
  wire [7:0]  _vdSat_T_27 = vxsat[6] ? 8'h7F : io.sumFinalNonFixP[128:121];
  wire [7:0]  _vdSat_T_29 = vxsat[5] ? 8'h7F : io.sumFinalNonFixP[109:102];
  wire [7:0]  _vdSat_T_31 = vxsat[4] ? 8'h7F : io.sumFinalNonFixP[90:83];
  wire [7:0]  _vdSat_T_33 = vxsat[3] ? 8'h7F : io.sumFinalNonFixP[71:64];
  wire [7:0]  _vdSat_T_35 = vxsat[2] ? 8'h7F : io.sumFinalNonFixP[52:45];
  wire [7:0]  _vdSat_T_37 = vxsat[1] ? 8'h7F : io.sumFinalNonFixP[33:26];
  wire [7:0]  _vdSat_T_39 = vxsat[0] ? 8'h7F : io.sumFinalNonFixP[14:7];
  wire [15:0] _vdSat_T_54 = vxsat[6] ? 16'h7FFF : io.sumFinalNonFixP[144:129];
  wire [15:0] _vdSat_T_56 = vxsat[4] ? 16'h7FFF : io.sumFinalNonFixP[106:91];
  wire [15:0] _vdSat_T_58 = vxsat[2] ? 16'h7FFF : io.sumFinalNonFixP[68:53];
  wire [15:0] _vdSat_T_60 = vxsat[0] ? 16'h7FFF : io.sumFinalNonFixP[30:15];
  wire [31:0] _vdSat_T_69 = vxsat[4] ? 32'h7FFFFFFF : io.sumFinalNonFixP[138:107];
  wire [31:0] _vdSat_T_71 = vxsat[0] ? 32'h7FFFFFFF : io.sumFinalNonFixP[62:31];
  wire [63:0] _vdSat_T_75 = vxsat[0] ? 64'h7FFFFFFFFFFFFFFF : io.sumFinalNonFixP[126:63];
  wire [63:0] _vdSat_T_76 =
    io.sewIs8
      ? {_vdSat_T_25,
         _vdSat_T_27,
         _vdSat_T_29,
         _vdSat_T_31,
         _vdSat_T_33,
         _vdSat_T_35,
         _vdSat_T_37,
         _vdSat_T_39}
      : 64'h0;
  wire [63:0] _vdSat_T_77 =
    io.sewIs16 ? {_vdSat_T_54, _vdSat_T_56, _vdSat_T_58, _vdSat_T_60} : 64'h0;
  wire [63:0] _vdSat_T_78 = io.sewIs32 ? {_vdSat_T_69, _vdSat_T_71} : 64'h0;
  wire [63:0] _vdSat_T_79 = io.sewIs64 ? _vdSat_T_75 : 64'h0;
  wire [63:0] vdSat = _vdSat_T_76 | _vdSat_T_77 | _vdSat_T_78 | _vdSat_T_79;
  assign io =
    '{sumFinalNonFixP: io_sumFinalNonFixP,
      sewIs8: io_sewIs8,
      sewIs16: io_sewIs16,
      sewIs32: io_sewIs32,
      sewIs64: io_sewIs64,
      vdSat: vdSat,
      vxsat: vxsat};
  assign io_vdSat = io.vdSat;
  assign io_vxsat = io.vxsat;
endmodule

