// Generated by CIRCT firtool-1.150.2
module wallace3to2CompressorStage2(
  input  [6:0][151:0] io_compStage1Results,
  input  [151:0]      io_wallaceLine34NonFixP,
                      io_wallaceLine34FixP,
  output [151:0]      io_sum34to2NonFixP,
                      io_cout34to2NonFixP,
                      io_sum34to2FixP,
                      io_cout34to2FixP
);

  wire
    struct packed {logic [6:0][151:0] compStage1Results; logic [151:0] wallaceLine34NonFixP; logic [151:0] wallaceLine34FixP; logic [151:0] sum34to2NonFixP; logic [151:0] cout34to2NonFixP; logic [151:0] sum34to2FixP; logic [151:0] cout34to2FixP; }
    io;
  wire [1:0][151:0] interCompressResult_sum;
  wire [1:0][151:0] interCompressResult_cout;
  wire [151:0]      _interCompressResult_cout_0_sum_T =
    io.compStage1Results[3'h0] ^ io.compStage1Results[3'h1];
  wire [151:0]      interCompressResult_sum_0_sum =
    _interCompressResult_cout_0_sum_T ^ io.compStage1Results[3'h2];
  wire [151:0]      _interCompressResult_cout_0_cout_T =
    io.compStage1Results[3'h0] & io.compStage1Results[3'h1];
  wire [151:0]      _interCompressResult_cout_0_cout_T_1 =
    io.compStage1Results[3'h1] & io.compStage1Results[3'h2];
  wire [151:0]      _interCompressResult_cout_0_cout_T_3 =
    io.compStage1Results[3'h2] & io.compStage1Results[3'h0];
  wire [151:0]      interCompressResult_sum_0_cout =
    _interCompressResult_cout_0_cout_T | _interCompressResult_cout_0_cout_T_1
    | _interCompressResult_cout_0_cout_T_3;
  wire [151:0]      interCompressResult_cout_0_sum =
    _interCompressResult_cout_0_sum_T ^ io.compStage1Results[3'h2];
  wire [151:0]      interCompressResult_cout_0_cout =
    _interCompressResult_cout_0_cout_T | _interCompressResult_cout_0_cout_T_1
    | _interCompressResult_cout_0_cout_T_3;
  wire [151:0]      _interCompressResult_cout_1_sum_T =
    io.compStage1Results[3'h3] ^ io.compStage1Results[3'h4];
  wire [151:0]      interCompressResult_sum_1_sum =
    _interCompressResult_cout_1_sum_T ^ io.compStage1Results[3'h5];
  wire [151:0]      _interCompressResult_cout_1_cout_T =
    io.compStage1Results[3'h3] & io.compStage1Results[3'h4];
  wire [151:0]      _interCompressResult_cout_1_cout_T_1 =
    io.compStage1Results[3'h4] & io.compStage1Results[3'h5];
  wire [151:0]      _interCompressResult_cout_1_cout_T_3 =
    io.compStage1Results[3'h5] & io.compStage1Results[3'h3];
  wire [151:0]      interCompressResult_sum_1_cout =
    _interCompressResult_cout_1_cout_T | _interCompressResult_cout_1_cout_T_1
    | _interCompressResult_cout_1_cout_T_3;
  assign interCompressResult_sum =
    {{interCompressResult_sum_1_sum}, {interCompressResult_sum_0_sum}};
  wire [151:0]      interCompressResult_cout_1_sum =
    _interCompressResult_cout_1_sum_T ^ io.compStage1Results[3'h5];
  wire [151:0]      interCompressResult_cout_1_cout =
    _interCompressResult_cout_1_cout_T | _interCompressResult_cout_1_cout_T_1
    | _interCompressResult_cout_1_cout_T_3;
  assign interCompressResult_cout =
    {{{interCompressResult_cout_1_cout[150:0], 1'h0}},
     {{interCompressResult_cout_0_cout[150:0], 1'h0}}};
  wire [1:0][151:0] nonFixPResult_sum;
  wire [1:0][151:0] nonFixPResult_cout;
  wire [151:0]      _fixPResult_cout_0_sum_T =
    interCompressResult_sum[1'h0] ^ interCompressResult_sum[1'h1];
  wire [151:0]      nonFixPResult_sum_0_sum =
    _fixPResult_cout_0_sum_T ^ interCompressResult_cout[1'h0];
  wire [151:0]      _fixPResult_cout_0_cout_T =
    interCompressResult_sum[1'h0] & interCompressResult_sum[1'h1];
  wire [151:0]      _fixPResult_cout_0_cout_T_1 =
    interCompressResult_sum[1'h1] & interCompressResult_cout[1'h0];
  wire [151:0]      _fixPResult_cout_0_cout_T_3 =
    interCompressResult_cout[1'h0] & interCompressResult_sum[1'h0];
  wire [151:0]      nonFixPResult_sum_0_cout =
    _fixPResult_cout_0_cout_T | _fixPResult_cout_0_cout_T_1 | _fixPResult_cout_0_cout_T_3;
  wire [151:0]      nonFixPResult_cout_0_sum =
    _fixPResult_cout_0_sum_T ^ interCompressResult_cout[1'h0];
  wire [151:0]      nonFixPResult_cout_0_cout =
    _fixPResult_cout_0_cout_T | _fixPResult_cout_0_cout_T_1 | _fixPResult_cout_0_cout_T_3;
  wire [151:0]      _fixPResult_cout_1_sum_T =
    interCompressResult_cout[1'h1] ^ io.compStage1Results[3'h6];
  wire [151:0]      nonFixPResult_sum_1_sum =
    _fixPResult_cout_1_sum_T ^ io.wallaceLine34NonFixP;
  wire [151:0]      _fixPResult_cout_1_cout_T =
    interCompressResult_cout[1'h1] & io.compStage1Results[3'h6];
  wire [151:0]      _nonFixPResult_cout_1_cout_T_1 =
    io.compStage1Results[3'h6] & io.wallaceLine34NonFixP;
  wire [151:0]      _nonFixPResult_cout_1_cout_T_3 =
    io.wallaceLine34NonFixP & interCompressResult_cout[1'h1];
  wire [151:0]      nonFixPResult_sum_1_cout =
    _fixPResult_cout_1_cout_T | _nonFixPResult_cout_1_cout_T_1
    | _nonFixPResult_cout_1_cout_T_3;
  assign nonFixPResult_sum = {{nonFixPResult_sum_1_sum}, {nonFixPResult_sum_0_sum}};
  wire [151:0]      nonFixPResult_cout_1_sum =
    _fixPResult_cout_1_sum_T ^ io.wallaceLine34NonFixP;
  wire [151:0]      nonFixPResult_cout_1_cout =
    _fixPResult_cout_1_cout_T | _nonFixPResult_cout_1_cout_T_1
    | _nonFixPResult_cout_1_cout_T_3;
  assign nonFixPResult_cout =
    {{{nonFixPResult_cout_1_cout[150:0], 1'h0}},
     {{nonFixPResult_cout_0_cout[150:0], 1'h0}}};
  wire [0:0][151:0] nonFixPResult_sum_1;
  wire [0:0][151:0] nonFixPResult_cout_1;
  wire [151:0]      _nonFixPResult_cout_0_sum_T_2 =
    nonFixPResult_sum[1'h0] ^ nonFixPResult_sum[1'h1];
  wire [151:0]      nonFixPResult_sum_0_sum_1 =
    _nonFixPResult_cout_0_sum_T_2 ^ nonFixPResult_cout[1'h0];
  wire [151:0]      _nonFixPResult_cout_0_cout_T_5 =
    nonFixPResult_sum[1'h0] & nonFixPResult_sum[1'h1];
  wire [151:0]      _nonFixPResult_cout_0_cout_T_6 =
    nonFixPResult_sum[1'h1] & nonFixPResult_cout[1'h0];
  wire [151:0]      _nonFixPResult_cout_0_cout_T_8 =
    nonFixPResult_cout[1'h0] & nonFixPResult_sum[1'h0];
  wire [151:0]      nonFixPResult_sum_0_cout_1 =
    _nonFixPResult_cout_0_cout_T_5 | _nonFixPResult_cout_0_cout_T_6
    | _nonFixPResult_cout_0_cout_T_8;
  assign nonFixPResult_sum_1 = {1{nonFixPResult_sum_0_sum_1}};
  wire [151:0]      nonFixPResult_cout_0_sum_1 =
    _nonFixPResult_cout_0_sum_T_2 ^ nonFixPResult_cout[1'h0];
  wire [151:0]      nonFixPResult_cout_0_cout_1 =
    _nonFixPResult_cout_0_cout_T_5 | _nonFixPResult_cout_0_cout_T_6
    | _nonFixPResult_cout_0_cout_T_8;
  assign nonFixPResult_cout_1 = {1{{nonFixPResult_cout_0_cout_1[150:0], 1'h0}}};
  wire [0:0][151:0] nonFixPResult_sum_2;
  wire [0:0][151:0] nonFixPResult_cout_2;
  wire [151:0]      _nonFixPResult_cout_0_sum_T_4 =
    nonFixPResult_sum_1[1'h0] ^ nonFixPResult_cout_1[1'h0];
  wire [151:0]      nonFixPResult_sum_0_sum_2 =
    _nonFixPResult_cout_0_sum_T_4 ^ nonFixPResult_cout[1'h1];
  wire [151:0]      _nonFixPResult_cout_0_cout_T_10 =
    nonFixPResult_sum_1[1'h0] & nonFixPResult_cout_1[1'h0];
  wire [151:0]      _nonFixPResult_cout_0_cout_T_11 =
    nonFixPResult_cout_1[1'h0] & nonFixPResult_cout[1'h1];
  wire [151:0]      _nonFixPResult_cout_0_cout_T_13 =
    nonFixPResult_cout[1'h1] & nonFixPResult_sum_1[1'h0];
  wire [151:0]      nonFixPResult_sum_0_cout_2 =
    _nonFixPResult_cout_0_cout_T_10 | _nonFixPResult_cout_0_cout_T_11
    | _nonFixPResult_cout_0_cout_T_13;
  wire [151:0]      nonFixPResult_cout_0_sum_2 =
    _nonFixPResult_cout_0_sum_T_4 ^ nonFixPResult_cout[1'h1];
  wire [151:0]      nonFixPResult_cout_0_cout_2 =
    _nonFixPResult_cout_0_cout_T_10 | _nonFixPResult_cout_0_cout_T_11
    | _nonFixPResult_cout_0_cout_T_13;
  wire [1:0][151:0] fixPResult_sum;
  wire [1:0][151:0] fixPResult_cout;
  wire [151:0]      fixPResult_sum_0_sum =
    _fixPResult_cout_0_sum_T ^ interCompressResult_cout[1'h0];
  wire [151:0]      fixPResult_sum_0_cout =
    _fixPResult_cout_0_cout_T | _fixPResult_cout_0_cout_T_1 | _fixPResult_cout_0_cout_T_3;
  wire [151:0]      fixPResult_cout_0_sum =
    _fixPResult_cout_0_sum_T ^ interCompressResult_cout[1'h0];
  wire [151:0]      fixPResult_cout_0_cout =
    _fixPResult_cout_0_cout_T | _fixPResult_cout_0_cout_T_1 | _fixPResult_cout_0_cout_T_3;
  wire [151:0]      fixPResult_sum_1_sum =
    _fixPResult_cout_1_sum_T ^ io.wallaceLine34FixP;
  wire [151:0]      _fixPResult_cout_1_cout_T_1 =
    io.compStage1Results[3'h6] & io.wallaceLine34FixP;
  wire [151:0]      _fixPResult_cout_1_cout_T_3 =
    io.wallaceLine34FixP & interCompressResult_cout[1'h1];
  wire [151:0]      fixPResult_sum_1_cout =
    _fixPResult_cout_1_cout_T | _fixPResult_cout_1_cout_T_1 | _fixPResult_cout_1_cout_T_3;
  assign fixPResult_sum = {{fixPResult_sum_1_sum}, {fixPResult_sum_0_sum}};
  wire [151:0]      fixPResult_cout_1_sum =
    _fixPResult_cout_1_sum_T ^ io.wallaceLine34FixP;
  wire [151:0]      fixPResult_cout_1_cout =
    _fixPResult_cout_1_cout_T | _fixPResult_cout_1_cout_T_1 | _fixPResult_cout_1_cout_T_3;
  assign fixPResult_cout =
    {{{fixPResult_cout_1_cout[150:0], 1'h0}}, {{fixPResult_cout_0_cout[150:0], 1'h0}}};
  wire [0:0][151:0] fixPResult_sum_1;
  wire [0:0][151:0] fixPResult_cout_1;
  wire [151:0]      _fixPResult_cout_0_sum_T_2 =
    fixPResult_sum[1'h0] ^ fixPResult_sum[1'h1];
  wire [151:0]      fixPResult_sum_0_sum_1 =
    _fixPResult_cout_0_sum_T_2 ^ fixPResult_cout[1'h0];
  wire [151:0]      _fixPResult_cout_0_cout_T_5 =
    fixPResult_sum[1'h0] & fixPResult_sum[1'h1];
  wire [151:0]      _fixPResult_cout_0_cout_T_6 =
    fixPResult_sum[1'h1] & fixPResult_cout[1'h0];
  wire [151:0]      _fixPResult_cout_0_cout_T_8 =
    fixPResult_cout[1'h0] & fixPResult_sum[1'h0];
  wire [151:0]      fixPResult_sum_0_cout_1 =
    _fixPResult_cout_0_cout_T_5 | _fixPResult_cout_0_cout_T_6
    | _fixPResult_cout_0_cout_T_8;
  assign fixPResult_sum_1 = {1{fixPResult_sum_0_sum_1}};
  wire [151:0]      fixPResult_cout_0_sum_1 =
    _fixPResult_cout_0_sum_T_2 ^ fixPResult_cout[1'h0];
  wire [151:0]      fixPResult_cout_0_cout_1 =
    _fixPResult_cout_0_cout_T_5 | _fixPResult_cout_0_cout_T_6
    | _fixPResult_cout_0_cout_T_8;
  assign fixPResult_cout_1 = {1{{fixPResult_cout_0_cout_1[150:0], 1'h0}}};
  wire [0:0][151:0] fixPResult_sum_2;
  wire [0:0][151:0] fixPResult_cout_2;
  wire [151:0]      _fixPResult_cout_0_sum_T_4 =
    fixPResult_sum_1[1'h0] ^ fixPResult_cout_1[1'h0];
  wire [151:0]      fixPResult_sum_0_sum_2 =
    _fixPResult_cout_0_sum_T_4 ^ fixPResult_cout[1'h1];
  wire [151:0]      _fixPResult_cout_0_cout_T_10 =
    fixPResult_sum_1[1'h0] & fixPResult_cout_1[1'h0];
  wire [151:0]      _fixPResult_cout_0_cout_T_11 =
    fixPResult_cout_1[1'h0] & fixPResult_cout[1'h1];
  wire [151:0]      _fixPResult_cout_0_cout_T_13 =
    fixPResult_cout[1'h1] & fixPResult_sum_1[1'h0];
  wire [151:0]      fixPResult_sum_0_cout_2 =
    _fixPResult_cout_0_cout_T_10 | _fixPResult_cout_0_cout_T_11
    | _fixPResult_cout_0_cout_T_13;
  wire [151:0]      fixPResult_cout_0_sum_2 =
    _fixPResult_cout_0_sum_T_4 ^ fixPResult_cout[1'h1];
  wire [151:0]      fixPResult_cout_0_cout_2 =
    _fixPResult_cout_0_cout_T_10 | _fixPResult_cout_0_cout_T_11
    | _fixPResult_cout_0_cout_T_13;
  assign io =
    '{compStage1Results: io_compStage1Results,
      wallaceLine34NonFixP: io_wallaceLine34NonFixP,
      wallaceLine34FixP: io_wallaceLine34FixP,
      sum34to2NonFixP: nonFixPResult_sum_2[1'h0],
      cout34to2NonFixP: nonFixPResult_cout_2[1'h0],
      sum34to2FixP: fixPResult_sum_2[1'h0],
      cout34to2FixP: fixPResult_cout_2[1'h0]};
  assign nonFixPResult_sum_2 = {1{nonFixPResult_sum_0_sum_2}};
  assign nonFixPResult_cout_2 = {1{{nonFixPResult_cout_0_cout_2[150:0], 1'h0}}};
  assign fixPResult_sum_2 = {1{fixPResult_sum_0_sum_2}};
  assign fixPResult_cout_2 = {1{{fixPResult_cout_0_cout_2[150:0], 1'h0}}};
  assign io_sum34to2NonFixP = io.sum34to2NonFixP;
  assign io_cout34to2NonFixP = io.cout34to2NonFixP;
  assign io_sum34to2FixP = io.sum34to2FixP;
  assign io_cout34to2FixP = io.cout34to2FixP;
endmodule

