// Generated by CIRCT firtool-1.150.2
module DualIssueForwardingUnit(	// src/main/scala/components/dual/forwarding.scala:54:7
  input  [4:0] io_ex_pipeA_rs1,	// src/main/scala/components/dual/forwarding.scala:55:14
               io_ex_pipeA_rs2,	// src/main/scala/components/dual/forwarding.scala:55:14
               io_ex_pipeB_rs1,	// src/main/scala/components/dual/forwarding.scala:55:14
               io_ex_pipeB_rs2,	// src/main/scala/components/dual/forwarding.scala:55:14
               io_ex_pipeA_rd,	// src/main/scala/components/dual/forwarding.scala:55:14
  input        io_ex_pipeA_rw,	// src/main/scala/components/dual/forwarding.scala:55:14
  input  [4:0] io_mem_pipeA_rd,	// src/main/scala/components/dual/forwarding.scala:55:14
  input        io_mem_pipeA_rw,	// src/main/scala/components/dual/forwarding.scala:55:14
  input  [4:0] io_mem_pipeB_rd,	// src/main/scala/components/dual/forwarding.scala:55:14
  input        io_mem_pipeB_rw,	// src/main/scala/components/dual/forwarding.scala:55:14
  input  [4:0] io_wb_pipeA_rd,	// src/main/scala/components/dual/forwarding.scala:55:14
  input        io_wb_pipeA_rw,	// src/main/scala/components/dual/forwarding.scala:55:14
  input  [4:0] io_wb_pipeB_rd,	// src/main/scala/components/dual/forwarding.scala:55:14
  input        io_wb_pipeB_rw,	// src/main/scala/components/dual/forwarding.scala:55:14
  output [2:0] io_pipeA_forward1,	// src/main/scala/components/dual/forwarding.scala:55:14
               io_pipeA_forward2,	// src/main/scala/components/dual/forwarding.scala:55:14
               io_pipeB_forward1,	// src/main/scala/components/dual/forwarding.scala:55:14
               io_pipeB_forward2	// src/main/scala/components/dual/forwarding.scala:55:14
);

  wire
    struct packed {logic [4:0] ex_pipeA_rs1; logic [4:0] ex_pipeA_rs2; logic [4:0] ex_pipeB_rs1; logic [4:0] ex_pipeB_rs2; logic [4:0] ex_pipeA_rd; logic ex_pipeA_rw; logic [4:0] mem_pipeA_rd; logic mem_pipeA_rw; logic [4:0] mem_pipeB_rd; logic mem_pipeB_rw; logic [4:0] wb_pipeA_rd; logic wb_pipeA_rw; logic [4:0] wb_pipeB_rd; logic wb_pipeB_rw; logic [2:0] pipeA_forward1; logic [2:0] pipeA_forward2; logic [2:0] pipeB_forward1; logic [2:0] pipeB_forward2; }
    io;	// src/main/scala/components/dual/forwarding.scala:54:7
  wire       _GEN = |io.ex_pipeA_rs1;	// src/main/scala/components/dual/forwarding.scala:54:7, :79:101
  wire [2:0] _GEN_0 =
    io.wb_pipeA_rw & io.wb_pipeA_rd == io.ex_pipeA_rs1 & _GEN ? 3'h3 : 3'h0;	// src/main/scala/components/dual/forwarding.scala:54:7, :79:101, :85:{43,62,82,110}, :86:23, :88:23
  wire [2:0] _GEN_1 =
    io.wb_pipeB_rw & io.wb_pipeB_rd == io.ex_pipeA_rs1 & _GEN ? 3'h4 : _GEN_0;	// src/main/scala/components/dual/forwarding.scala:54:7, :79:101, :83:{43,62,82,110}, :84:23, :85:110, :86:23, :88:23
  wire [2:0] _GEN_2 =
    io.mem_pipeA_rw & io.mem_pipeA_rd == io.ex_pipeA_rs1 & _GEN ? 3'h1 : _GEN_1;	// src/main/scala/components/dual/forwarding.scala:54:7, :79:101, :81:{43,62,82,110}, :82:23, :83:110, :84:23, :85:110
  wire [2:0] _GEN_3 =
    io.mem_pipeB_rw & io.mem_pipeB_rd == io.ex_pipeA_rs1 & _GEN ? 3'h2 : _GEN_2;	// src/main/scala/components/dual/forwarding.scala:54:7, :79:{43,62,82,101,110}, :80:23, :81:110, :82:23, :83:110
  wire       _GEN_4 = |io.ex_pipeA_rs2;	// src/main/scala/components/dual/forwarding.scala:54:7, :92:101
  wire [2:0] _GEN_5 =
    io.wb_pipeA_rw & io.wb_pipeA_rd == io.ex_pipeA_rs2 & _GEN_4 ? 3'h3 : 3'h0;	// src/main/scala/components/dual/forwarding.scala:54:7, :92:101, :98:{43,62,82,110}, :99:23, :101:23
  wire [2:0] _GEN_6 =
    io.wb_pipeB_rw & io.wb_pipeB_rd == io.ex_pipeA_rs2 & _GEN_4 ? 3'h4 : _GEN_5;	// src/main/scala/components/dual/forwarding.scala:54:7, :84:23, :92:101, :96:{43,62,82,110}, :97:23, :98:110, :99:23, :101:23
  wire [2:0] _GEN_7 =
    io.mem_pipeA_rw & io.mem_pipeA_rd == io.ex_pipeA_rs2 & _GEN_4 ? 3'h1 : _GEN_6;	// src/main/scala/components/dual/forwarding.scala:54:7, :92:101, :94:{43,62,82,110}, :95:23, :96:110, :97:23, :98:110
  wire [2:0] _GEN_8 =
    io.mem_pipeB_rw & io.mem_pipeB_rd == io.ex_pipeA_rs2 & _GEN_4 ? 3'h2 : _GEN_7;	// src/main/scala/components/dual/forwarding.scala:54:7, :92:{43,62,82,101,110}, :93:23, :94:110, :95:23, :96:110
  wire       _GEN_9 = |io.ex_pipeB_rs1;	// src/main/scala/components/dual/forwarding.scala:54:7, :105:101
  wire [2:0] _GEN_10 =
    io.wb_pipeB_rw & io.wb_pipeB_rd == io.ex_pipeB_rs1 & _GEN_9
      ? 3'h5
      : {io.wb_pipeA_rw & io.wb_pipeA_rd == io.ex_pipeB_rs1 & _GEN_9, 2'h0};	// src/main/scala/components/dual/forwarding.scala:54:7, :105:101, :109:{43,62,82,110}, :110:23, :111:{43,62,82,110}, :112:23, :114:23
  wire [2:0] _GEN_11 =
    io.mem_pipeA_rw & io.mem_pipeA_rd == io.ex_pipeB_rs1 & _GEN_9 ? 3'h2 : _GEN_10;	// src/main/scala/components/dual/forwarding.scala:54:7, :105:101, :107:{43,62,82,110}, :108:23, :109:110, :110:23, :111:110
  wire [2:0] _GEN_12 =
    io.mem_pipeB_rw & io.mem_pipeB_rd == io.ex_pipeB_rs1 & _GEN_9 ? 3'h3 : _GEN_11;	// src/main/scala/components/dual/forwarding.scala:54:7, :105:{43,62,82,101,110}, :106:23, :107:110, :108:23, :109:110
  wire       _GEN_13 = |io.ex_pipeB_rs2;	// src/main/scala/components/dual/forwarding.scala:54:7, :118:101
  wire [2:0] _GEN_14 =
    io.wb_pipeB_rw & io.wb_pipeB_rd == io.ex_pipeB_rs2 & _GEN_13
      ? 3'h5
      : {io.wb_pipeA_rw & io.wb_pipeA_rd == io.ex_pipeB_rs2 & _GEN_13, 2'h0};	// src/main/scala/components/dual/forwarding.scala:54:7, :110:23, :118:101, :122:{43,62,82,110}, :123:23, :124:{43,62,82,110}, :125:23, :127:23
  wire [2:0] _GEN_15 =
    io.mem_pipeA_rw & io.mem_pipeA_rd == io.ex_pipeB_rs2 & _GEN_13 ? 3'h2 : _GEN_14;	// src/main/scala/components/dual/forwarding.scala:54:7, :118:101, :120:{43,62,82,110}, :121:23, :122:110, :123:23, :124:110
  wire [2:0] _GEN_16 =
    io.mem_pipeB_rw & io.mem_pipeB_rd == io.ex_pipeB_rs2 & _GEN_13 ? 3'h3 : _GEN_15;	// src/main/scala/components/dual/forwarding.scala:54:7, :118:{43,62,82,101,110}, :119:23, :120:110, :121:23, :122:110
  assign io =
    '{ex_pipeA_rs1: io_ex_pipeA_rs1,
      ex_pipeA_rs2: io_ex_pipeA_rs2,
      ex_pipeB_rs1: io_ex_pipeB_rs1,
      ex_pipeB_rs2: io_ex_pipeB_rs2,
      ex_pipeA_rd: io_ex_pipeA_rd,
      ex_pipeA_rw: io_ex_pipeA_rw,
      mem_pipeA_rd: io_mem_pipeA_rd,
      mem_pipeA_rw: io_mem_pipeA_rw,
      mem_pipeB_rd: io_mem_pipeB_rd,
      mem_pipeB_rw: io_mem_pipeB_rw,
      wb_pipeA_rd: io_wb_pipeA_rd,
      wb_pipeA_rw: io_wb_pipeA_rw,
      wb_pipeB_rd: io_wb_pipeB_rd,
      wb_pipeB_rw: io_wb_pipeB_rw,
      pipeA_forward1: _GEN_3,
      pipeA_forward2: _GEN_8,
      pipeB_forward1: _GEN_12,
      pipeB_forward2: _GEN_16};	// src/main/scala/components/dual/forwarding.scala:54:7, :79:110, :80:23, :81:110, :92:110, :93:23, :94:110, :105:110, :106:23, :107:110, :118:110, :119:23, :120:110
  assign io_pipeA_forward1 = io.pipeA_forward1;	// src/main/scala/components/dual/forwarding.scala:54:7
  assign io_pipeA_forward2 = io.pipeA_forward2;	// src/main/scala/components/dual/forwarding.scala:54:7
  assign io_pipeB_forward1 = io.pipeB_forward1;	// src/main/scala/components/dual/forwarding.scala:54:7
  assign io_pipeB_forward2 = io.pipeB_forward2;	// src/main/scala/components/dual/forwarding.scala:54:7
endmodule

