// Generated by CIRCT firtool-1.150.2
module StageReg_2(	// src/main/scala/pipelined/stage-register.scala:38:7
  input                                                                                                                                                   clock,	// src/main/scala/pipelined/stage-register.scala:38:7
                                                                                                                                                          reset,	// src/main/scala/pipelined/stage-register.scala:38:7
  input  struct packed {logic [63:0] pc; logic [63:0] instruction; logic [63:0] sextImm; logic [63:0] readdata1; logic [63:0] readdata2; logic isValid; } io_in,	// src/main/scala/pipelined/stage-register.scala:39:14
  input                                                                                                                                                   io_flush,	// src/main/scala/pipelined/stage-register.scala:39:14
  output struct packed {logic [63:0] pc; logic [63:0] instruction; logic [63:0] sextImm; logic [63:0] readdata1; logic [63:0] readdata2; logic isValid; } io_data	// src/main/scala/pipelined/stage-register.scala:39:14
);

  wire
    struct packed {struct packed {logic [63:0] pc; logic [63:0] instruction; logic [63:0] sextImm; logic [63:0] readdata1; logic [63:0] readdata2; logic isValid; } in; logic flush; logic valid; struct packed {logic [63:0] pc; logic [63:0] instruction; logic [63:0] sextImm; logic [63:0] readdata1; logic [63:0] readdata2; logic isValid; } data; }
    io;	// src/main/scala/pipelined/stage-register.scala:38:7
  struct packed {logic [63:0] pc; logic [63:0] instruction; logic [63:0] sextImm; logic [63:0] readdata1; logic [63:0] readdata2; logic isValid; }
    reg_0;	// src/main/scala/pipelined/stage-register.scala:42:21
  assign io = '{in: io_in, flush: io_flush, valid: (1'h1), data: reg_0};	// src/main/scala/pipelined/stage-register.scala:38:7, :42:21
  always @(posedge clock) begin	// src/main/scala/pipelined/stage-register.scala:38:7
    if (reset)	// src/main/scala/pipelined/stage-register.scala:38:7
      reg_0 <=
        '{pc: 64'h0,
          instruction: 64'h0,
          sextImm: 64'h0,
          readdata1: 64'h0,
          readdata2: 64'h0,
          isValid: 1'h0};	// <stdin>:1816:5, :1817:5, :1818:5, :1819:5, :1820:5, :1821:5, :1855:5, :1856:5, :1857:5, :1858:5, :1859:5, :1860:5, src/main/scala/pipelined/stage-register.scala:42:21
    else begin	// src/main/scala/pipelined/stage-register.scala:38:7
      automatic logic [63:0] _GEN = io.flush ? 64'h0 : io.in.pc;	// <stdin>:1817:42, :1856:42, src/main/scala/pipelined/stage-register.scala:38:7, :46:19, :47:9, :50:19, :51:9
      automatic logic [63:0] _GEN_0 = io.flush ? 64'h0 : io.in.instruction;	// <stdin>:1817:42, :1856:42, src/main/scala/pipelined/stage-register.scala:38:7, :46:19, :47:9, :50:19, :51:9
      automatic logic [63:0] _GEN_1 = io.flush ? 64'h0 : io.in.sextImm;	// <stdin>:1817:42, :1856:42, src/main/scala/pipelined/stage-register.scala:38:7, :46:19, :47:9, :50:19, :51:9
      automatic logic [63:0] _GEN_2 = io.flush ? 64'h0 : io.in.readdata1;	// <stdin>:1817:42, :1856:42, src/main/scala/pipelined/stage-register.scala:38:7, :46:19, :47:9, :50:19, :51:9
      automatic logic [63:0] _GEN_3 = io.flush ? 64'h0 : io.in.readdata2;	// <stdin>:1817:42, :1856:42, src/main/scala/pipelined/stage-register.scala:38:7, :46:19, :47:9, :50:19, :51:9
      reg_0 <=
        '{pc: _GEN,
          instruction: _GEN_0,
          sextImm: _GEN_1,
          readdata1: _GEN_2,
          readdata2: _GEN_3,
          isValid: (~io.flush & io.in.isValid)};	// src/main/scala/pipelined/stage-register.scala:38:7, :42:21, :46:19, :47:9, :50:19, :51:9
    end
  end // always @(posedge)
  assign io_data = io.data;	// src/main/scala/pipelined/stage-register.scala:38:7
endmodule

